// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ScreenDrafts.Modules.Reporting.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class Add_Play_Order_To_Pick_Facts : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<int>(
                name: "play_order",
                schema: "reporting",
                table: "pick_facts",
                type: "integer",
                nullable: false,
                defaultValue: 0);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "play_order",
                schema: "reporting",
                table: "pick_facts");
        }
    }
}

