// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ScreenDrafts.Modules.Reporting.Infrastructure.Database;

#nullable disable

namespace ScreenDrafts.Modules.Reporting.Infrastructure.Database.Migrations
{
    [DbContext(typeof(ReportingDbContext))]
    partial class ReportingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("reporting")
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ScreenDrafts.Common.Infrastructure.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_inbox_messages");

                    b.ToTable("inbox_messages", "reporting");
                });

            modelBuilder.Entity("ScreenDrafts.Common.Infrastructure.Inbox.InboxMessageConsumer", b =>
                {
                    b.Property<Guid>("InboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("inbox_message_id");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("InboxMessageId", "Name")
                        .HasName("pk_inbox_message_consumers");

                    b.ToTable("inbox_message_consumers", "reporting");
                });

            modelBuilder.Entity("ScreenDrafts.Common.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.ToTable("outbox_messages", "reporting");
                });

            modelBuilder.Entity("ScreenDrafts.Common.Infrastructure.Outbox.OutboxMessageConsumer", b =>
                {
                    b.Property<Guid>("OutboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_message_id");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("OutboxMessageId", "Name")
                        .HasName("pk_outbox_message_consumers");

                    b.ToTable("outbox_message_consumers", "reporting");
                });

            modelBuilder.Entity("ScreenDrafts.Modules.Reporting.Domain.Drafters.DrafterCanonicalAppearance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AppearedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("appeared_at");

                    b.Property<string>("DraftPartPublicId")
                        .IsRequired()
                        .HasMaxLength(19)
                        .HasColumnType("character varying(19)")
                        .HasColumnName("draft_part_public_id");

                    b.Property<Guid>("DrafterIdValue")
                        .HasColumnType("uuid")
                        .HasColumnName("drafter_id_value");

                    b.Property<bool>("HasMainFeedRelease")
                        .HasColumnType("boolean")
                        .HasColumnName("has_main_feed_release");

                    b.HasKey("Id")
                        .HasName("pk_drafter_canonical_appearances");

                    b.HasIndex("DrafterIdValue")
                        .HasDatabaseName("ix_drafter_canonical_appearances_drafter_id_value");

                    b.HasIndex("DrafterIdValue", "DraftPartPublicId")
                        .IsUnique()
                        .HasDatabaseName("ux_drafter_canonical_appearances_drafter_id_part_id");

                    b.ToTable("drafter_canonical_appearances", "reporting");
                });

            modelBuilder.Entity("ScreenDrafts.Modules.Reporting.Domain.Drafters.DrafterHonorificEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AppearanceCount")
                        .HasColumnType("integer")
                        .HasColumnName("appearance_count");

                    b.Property<Guid>("DrafterIdValue")
                        .HasColumnType("uuid")
                        .HasColumnName("drafter_id_value");

                    b.Property<int>("Honorific")
                        .HasColumnType("integer")
                        .HasColumnName("honorific");

                    b.Property<DateTime>("UpdateAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_drafter_honorifics");

                    b.HasIndex("DrafterIdValue")
                        .IsUnique()
                        .HasDatabaseName("ux_drafter_honorifics_drafter_id_value");

                    b.ToTable("drafter_honorifics", "reporting");
                });

            modelBuilder.Entity("ScreenDrafts.Modules.Reporting.Domain.Drafters.DrafterHonorificHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AchievedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("achieved_at");

                    b.Property<int>("AppearanceCount")
                        .HasColumnType("integer")
                        .HasColumnName("appearance_count");

                    b.Property<Guid>("DrafterIdValue")
                        .HasColumnType("uuid")
                        .HasColumnName("drafter_id_value");

                    b.Property<int>("Honorific")
                        .HasColumnType("integer")
                        .HasColumnName("honorific");

                    b.HasKey("Id")
                        .HasName("pk_drafters_honorifics_history");

                    b.HasIndex("DrafterIdValue", "AchievedAt")
                        .HasDatabaseName("ix_drafter_honorifics_history_drafter_id_achieved_at");

                    b.ToTable("drafters_honorifics_history", "reporting");
                });

            modelBuilder.Entity("ScreenDrafts.Modules.Reporting.Domain.Drafts.DraftPartRelease", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DraftId")
                        .HasColumnType("uuid")
                        .HasColumnName("draft_id");

                    b.Property<string>("DraftPartPublicId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("draft_part_public_id");

                    b.Property<string>("ReleaseChannel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("release_channel");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date")
                        .HasColumnName("release_date");

                    b.HasKey("Id")
                        .HasName("pk_draft_part_releases");

                    b.HasIndex("DraftId")
                        .HasDatabaseName("ix_draft_part_releases_draft_id");

                    b.HasIndex("DraftPartPublicId", "ReleaseChannel")
                        .IsUnique()
                        .HasDatabaseName("ux_draft_part_releases_part_public_id_channel");

                    b.ToTable("draft_part_releases", "reporting");
                });

            modelBuilder.Entity("ScreenDrafts.Modules.Reporting.Domain.Drafts.DraftSpotlight", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ActivatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activated_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DraftPublicId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("draft_public_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("boolean")
                        .HasColumnName("is_pinned");

                    b.Property<string>("SpotifyUrl")
                        .HasColumnType("text")
                        .HasColumnName("spotify_url");

                    b.Property<string>("SpotlightDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("spotlight_description");

                    b.HasKey("Id")
                        .HasName("pk_draft_spotlights");

                    b.HasIndex("IsActive")
                        .IsUnique()
                        .HasDatabaseName("uix_draft_spotlights_active")
                        .HasFilter("is_active = true");

                    b.ToTable("draft_spotlights", "reporting");
                });

            modelBuilder.Entity("ScreenDrafts.Modules.Reporting.Domain.Drafts.DraftSummary", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("DraftId")
                        .HasColumnType("uuid")
                        .HasColumnName("draft_id");

                    b.Property<string>("DraftPartPublicId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("draft_part_public_id");

                    b.Property<string>("DraftPublicId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("draft_public_id");

                    b.Property<string>("DraftType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("draft_type");

                    b.Property<int?>("EpisodeNumber")
                        .HasColumnType("integer")
                        .HasColumnName("episode_number");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("boolean")
                        .HasColumnName("is_complete");

                    b.Property<bool>("IsPatreon")
                        .HasColumnType("boolean")
                        .HasColumnName("is_patreon");

                    b.Property<int>("PartIndex")
                        .HasColumnType("integer")
                        .HasColumnName("part_index");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("TotalParts")
                        .HasColumnType("integer")
                        .HasColumnName("total_parts");

                    b.HasKey("Id")
                        .HasName("pk_draft_summaries");

                    b.HasIndex("DraftId")
                        .HasDatabaseName("ix_draft_summaries_draft_id");

                    b.HasIndex("DraftPublicId")
                        .HasDatabaseName("ix_draft_summaries_draft_public_id");

                    b.HasIndex("DraftId", "DraftPartPublicId")
                        .IsUnique()
                        .HasDatabaseName("ux_draft_summaries_draft_id_part_public_id");

                    b.ToTable("draft_summaries", "reporting");
                });

            modelBuilder.Entity("ScreenDrafts.Modules.Reporting.Domain.Drafts.SiteStats", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("VetoesCount")
                        .HasColumnType("integer")
                        .HasColumnName("vetoes_count");

                    b.HasKey("Id")
                        .HasName("pk_site_stats");

                    b.ToTable("site_stats", "reporting");
                });

            modelBuilder.Entity("ScreenDrafts.Modules.Reporting.Domain.Movies.MovieCanonicalPick", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BoardPosition")
                        .HasColumnType("integer")
                        .HasColumnName("board_position");

                    b.Property<string>("DraftPartPublicId")
                        .IsRequired()
                        .HasMaxLength(19)
                        .HasColumnType("character varying(19)")
                        .HasColumnName("draft_part_public_id");

                    b.Property<string>("MoviePublicId")
                        .IsRequired()
                        .HasMaxLength(19)
                        .HasColumnType("character varying(19)")
                        .HasColumnName("movie_public_id");

                    b.Property<DateTime>("PickedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("picked_at");

                    b.HasKey("Id")
                        .HasName("pk_movie_canonical_picks");

                    b.HasIndex("MoviePublicId")
                        .HasDatabaseName("ix_movie_canonical_picks_movie_public_id");

                    b.HasIndex("MoviePublicId", "DraftPartPublicId")
                        .IsUnique()
                        .HasDatabaseName("ux_movie_canonical_picks_movie_public_id_part_public_id");

                    b.ToTable("movie_canonical_picks", "reporting");
                });

            modelBuilder.Entity("ScreenDrafts.Modules.Reporting.Domain.Movies.MovieHonorificEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AppearanceCount")
                        .HasColumnType("integer")
                        .HasColumnName("appearance_count");

                    b.Property<int>("AppearanceHonorific")
                        .HasColumnType("integer")
                        .HasColumnName("appearance_honorific");

                    b.Property<string>("MoviePublicId")
                        .IsRequired()
                        .HasMaxLength(19)
                        .HasColumnType("character varying(19)")
                        .HasColumnName("movie_public_id");

                    b.Property<string>("MovieTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("movie_title");

                    b.Property<int>("PositionHonorific")
                        .HasColumnType("integer")
                        .HasColumnName("position_honorific");

                    b.Property<DateTime>("UpdateAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_movie_honorifics");

                    b.HasIndex("MoviePublicId")
                        .IsUnique()
                        .HasDatabaseName("ux_movie_honorifics_movie_public_id");

                    b.ToTable("movie_honorifics", "reporting");
                });

            modelBuilder.Entity("ScreenDrafts.Modules.Reporting.Domain.Movies.MovieHonorificHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AchievedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("achieved_at");

                    b.Property<int>("AppearanceCount")
                        .HasColumnType("integer")
                        .HasColumnName("appearance_count");

                    b.Property<int>("AppearanceHonorific")
                        .HasColumnType("integer")
                        .HasColumnName("appearance_honorific");

                    b.Property<string>("MoviePublicId")
                        .IsRequired()
                        .HasMaxLength(19)
                        .HasColumnType("character varying(19)")
                        .HasColumnName("movie_public_id");

                    b.Property<int>("PositionHonorific")
                        .HasColumnType("integer")
                        .HasColumnName("position_honorific");

                    b.HasKey("Id")
                        .HasName("pk_movies_honorifics_history");

                    b.HasIndex("MoviePublicId", "AchievedAt")
                        .HasDatabaseName("ix_movie_honorifics_history_movie_public_id_achieved_at");

                    b.ToTable("movies_honorifics_history", "reporting");
                });
#pragma warning restore 612, 618
        }
    }
}
