CREATE SCHEMA IF NOT EXISTS reporting;

GRANT USAGE ON SCHEMA reporting TO reporting_user;
GRANT CREATE ON SCHEMA reporting TO reporting_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA reporting
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO reporting_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA reporting
    GRANT USAGE, SELECT ON SEQUENCES TO reporting_user;