CREATE SCHEMA IF NOT EXISTS movies;

GRANT USAGE ON SCHEMA movies TO movies_user;
GRANT CREATE ON SCHEMA movies TO movies_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA movies
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO movies_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA movies
    GRANT USAGE, SELECT ON SEQUENCES TO movies_user;