CREATE SCHEMA IF NOT EXISTS users;

GRANT USAGE ON SCHEMA users TO users_user;
GRANT CREATE ON SCHEMA users TO users_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA users
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO users_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA users
    GRANT USAGE, SELECT ON SEQUENCES TO users_user;