CREATE SCHEMA IF NOT EXISTS audit;

GRANT USAGE ON SCHEMA audit TO audit_user;
GRANT CREATE ON SCHEMA audit TO audit_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA audit
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO audit_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA audit
    GRANT USAGE, SELECT ON SEQUENCES TO audit_user;