// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ScreenDrafts.Modules.Drafts.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class Update_RolloverVeto : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<Guid>(
                name: "drafter_id",
                schema: "drafts",
                table: "rollover_vetoes",
                type: "uuid",
                nullable: true,
                oldClrType: typeof(Guid),
                oldType: "uuid");

            migrationBuilder.AddColumn<Guid>(
                name: "drafter_team_id",
                schema: "drafts",
                table: "rollover_vetoes",
                type: "uuid",
                nullable: true);

            migrationBuilder.AlterColumn<Guid>(
                name: "drafter_id",
                schema: "drafts",
                table: "rollover_veto_overrides",
                type: "uuid",
                nullable: true,
                oldClrType: typeof(Guid),
                oldType: "uuid");

            migrationBuilder.AddColumn<Guid>(
                name: "drafter_team_id",
                schema: "drafts",
                table: "rollover_veto_overrides",
                type: "uuid",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "number_of_drafters",
                schema: "drafts",
                table: "drafter_teams",
                type: "integer",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.CreateIndex(
                name: "ix_rollover_vetoes_drafter_team_id",
                schema: "drafts",
                table: "rollover_vetoes",
                column: "drafter_team_id",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_rollover_veto_overrides_drafter_team_id",
                schema: "drafts",
                table: "rollover_veto_overrides",
                column: "drafter_team_id",
                unique: true);

            migrationBuilder.AddForeignKey(
                name: "fk_rollover_veto_overrides_drafter_teams_drafter_team_id",
                schema: "drafts",
                table: "rollover_veto_overrides",
                column: "drafter_team_id",
                principalSchema: "drafts",
                principalTable: "drafter_teams",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "fk_rollover_vetoes_drafter_teams_drafter_team_id",
                schema: "drafts",
                table: "rollover_vetoes",
                column: "drafter_team_id",
                principalSchema: "drafts",
                principalTable: "drafter_teams",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "fk_rollover_veto_overrides_drafter_teams_drafter_team_id",
                schema: "drafts",
                table: "rollover_veto_overrides");

            migrationBuilder.DropForeignKey(
                name: "fk_rollover_vetoes_drafter_teams_drafter_team_id",
                schema: "drafts",
                table: "rollover_vetoes");

            migrationBuilder.DropIndex(
                name: "ix_rollover_vetoes_drafter_team_id",
                schema: "drafts",
                table: "rollover_vetoes");

            migrationBuilder.DropIndex(
                name: "ix_rollover_veto_overrides_drafter_team_id",
                schema: "drafts",
                table: "rollover_veto_overrides");

            migrationBuilder.DropColumn(
                name: "drafter_team_id",
                schema: "drafts",
                table: "rollover_vetoes");

            migrationBuilder.DropColumn(
                name: "drafter_team_id",
                schema: "drafts",
                table: "rollover_veto_overrides");

            migrationBuilder.DropColumn(
                name: "number_of_drafters",
                schema: "drafts",
                table: "drafter_teams");

            migrationBuilder.AlterColumn<Guid>(
                name: "drafter_id",
                schema: "drafts",
                table: "rollover_vetoes",
                type: "uuid",
                nullable: false,
                defaultValue: new Guid("00000000-0000-0000-0000-000000000000"),
                oldClrType: typeof(Guid),
                oldType: "uuid",
                oldNullable: true);

            migrationBuilder.AlterColumn<Guid>(
                name: "drafter_id",
                schema: "drafts",
                table: "rollover_veto_overrides",
                type: "uuid",
                nullable: false,
                defaultValue: new Guid("00000000-0000-0000-0000-000000000000"),
                oldClrType: typeof(Guid),
                oldType: "uuid",
                oldNullable: true);
        }
    }
}
