// <auto-generated />
using System;

using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ScreenDrafts.Modules.Drafts.Infrastructure.Database.Migrations
{
  /// <inheritdoc />
  public partial class AddMultipleReleaseDates : Migration
  {
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
      migrationBuilder.DropColumn(
          name: "release_date",
          schema: "drafts",
          table: "drafts");

      migrationBuilder.AddColumn<bool>(
          name: "is_patreon_only",
          schema: "drafts",
          table: "drafts",
          type: "boolean",
          nullable: true);

      migrationBuilder.CreateTable(
          name: "draft_release_date",
          schema: "drafts",
          columns: table => new
          {
            draft_id = table.Column<Guid>(type: "uuid", nullable: false),
            release_date = table.Column<DateOnly>(type: "date", nullable: false)
          },
          constraints: table =>
          {
            table.PrimaryKey("pk_draft_release_date", x => new { x.draft_id, x.release_date });
            table.ForeignKey(
                      name: "fk_draft_release_date_drafts_draft_id",
                      column: x => x.draft_id,
                      principalSchema: "drafts",
                      principalTable: "drafts",
                      principalColumn: "id",
                      onDelete: ReferentialAction.Cascade);
          });

      migrationBuilder.CreateIndex(
          name: "ix_drafts_readable_id",
          schema: "drafts",
          table: "drafts",
          column: "readable_id",
          unique: true);

        migrationBuilder.CreateIndex(
          name: "ix_draft_release_date_draft_id_release_date",
          schema: "drafts",
          table: "draft_release_date",
          columns: new[] { "draft_id", "release_date" },
          unique: true);
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
      migrationBuilder.DropTable(
          name: "draft_release_date",
          schema: "drafts");

      migrationBuilder.DropIndex(
          name: "ix_drafts_readable_id",
          schema: "drafts",
          table: "drafts");

      migrationBuilder.DropColumn(
          name: "is_patreon_only",
          schema: "drafts",
          table: "drafts");

      migrationBuilder.AddColumn<DateOnly>(
          name: "release_date",
          schema: "drafts",
          table: "drafts",
          type: "date",
          nullable: true);
    }
  }
}
