// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ScreenDrafts.Modules.Drafts.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class Update_Pick_Index : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "ix_picks_draft_id",
                schema: "drafts",
                table: "picks");

            migrationBuilder.CreateIndex(
                name: "ix_picks_draft_id_position_movie_id",
                schema: "drafts",
                table: "picks",
                columns: new[] { "draft_id", "position", "movie_id" },
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "ix_picks_draft_id_position_movie_id",
                schema: "drafts",
                table: "picks");

            migrationBuilder.CreateIndex(
                name: "ix_picks_draft_id",
                schema: "drafts",
                table: "picks",
                column: "draft_id");
        }
    }
}
