// <autogenerated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ScreenDrafts.Modules.Drafts.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class UpdatePickConfigurations : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "ix_picks_drafter_id",
                schema: "drafts",
                table: "picks");

            migrationBuilder.DropIndex(
                name: "ix_picks_movie_id",
                schema: "drafts",
                table: "picks");

            migrationBuilder.CreateIndex(
                name: "ix_picks_drafter_id",
                schema: "drafts",
                table: "picks",
                column: "drafter_id");

            migrationBuilder.CreateIndex(
                name: "ix_picks_movie_id",
                schema: "drafts",
                table: "picks",
                column: "movie_id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "ix_picks_drafter_id",
                schema: "drafts",
                table: "picks");

            migrationBuilder.DropIndex(
                name: "ix_picks_movie_id",
                schema: "drafts",
                table: "picks");

            migrationBuilder.CreateIndex(
                name: "ix_picks_drafter_id",
                schema: "drafts",
                table: "picks",
                column: "drafter_id",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_picks_movie_id",
                schema: "drafts",
                table: "picks",
                column: "movie_id",
                unique: true);
        }
    }
}
