// <auto-generated />
using System;

using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Migrations;

using ScreenDrafts.Modules.Drafts.Domain.Drafts.Entities;

using StackExchange.Redis;

#nullable disable

namespace ScreenDrafts.Modules.Drafts.Infrastructure.Database.Migrations
{
  /// <inheritdoc />
  public partial class Update_Drafts_with_Series_Parts : Migration
  {
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
      // ========= SEEDING HELPERS ==================

      var kind = new
      {
        Regular = SeriesKind.Regular.Value,
        FranchiseMiniSuper = SeriesKind.FranchiseMiniSuper.Value,
        InMemoriam = SeriesKind.InMemoriam.Value,
        Legends = SeriesKind.Legends.Value,
        BestPictureNominee = SeriesKind.BestPictureNominee.Value,
        PatreonVs = SeriesKind.PatreonVs.Value,
        LiveDraft = SeriesKind.LiveDraft.Value,
        Special = SeriesKind.Special.Value,
        SpeedDrafts = SeriesKind.SpeedDrafts.Value
      };

      var policy = new
      {
        Always = CanonicalPolicy.Always.Value,
        Never = CanonicalPolicy.Never.Value,
        OnMainFeed = CanonicalPolicy.OnMainFeed.Value
      };

      var scope = new
      {
        None = ContinuityScope.None.Value,
        Series = ContinuityScope.Series.Value,
        Global = ContinuityScope.Global.Value
      };

      var dateRule = new
      {
        AnyChannelFirstRelease = ContinuityDateRule.AnyChannelFirstRelease.Value,
        MainFeedOnly = ContinuityDateRule.MainFeedOnly.Value
      };

      var draftType = new
      {
        Standard = DraftType.Standard.Value,
        MiniMega = DraftType.MiniMega.Value,
        Mega = DraftType.Mega.Value,
        Super = DraftType.Super.Value,
        MiniSuper = DraftType.MiniSuper.Value
      };

      var draftTypeMask = new
      {
        None = 0,
        Standard = 1 << DraftType.Standard.Value,
        MiniMega = 1 << DraftType.MiniMega.Value,
        Mega = 1 << DraftType.Mega.Value,
        Super = 1 << DraftType.Super.Value,
        MiniSuper = 1 << DraftType.MiniSuper.Value,
        All = (1 << (DraftType.MiniSuper.Value + 1)) - 1
      };

      var campaignSlugs = new
      {
        ScreamDrafts = CampaignSlugs.ScreamDrafts,
        BillyRay = CampaignSlugs.BillyRayVsKyle,
        KristmasEve = CampaignSlugs.KristmasEve,
        PhilVsDana = CampaignSlugs.PhilVsDana,
      };

      var releaseChannel = new
      {
        MainFeed = ReleaseChannel.MainFeed.Value,
        Patreon = ReleaseChannel.Patreon.Value

      };

      // ============ SERIES ========================

      migrationBuilder.CreateTable(
          name: "series",
          schema: "drafts",
          columns: table => new
          {
            id = table.Column<Guid>(type: "uuid", nullable: false),
            name = table.Column<string>(type: "text", nullable: false),
            kind = table.Column<int>(type: "integer", nullable: false), // Series Kind
            canonical_policy = table.Column<int>(type: "integer", nullable: false), // Canonical Policy
            continuity_scope = table.Column<int>(type: "integer", nullable: false), // Continuity Scope
            continuity_date_rule = table.Column<int>(type: "integer", nullable: false), // Continuity Date Rulu
            required_draft_type = table.Column<int>(type: "integer", nullable: true),
            default_draft_type = table.Column<int>(type: "integer", nullable: true),
            allowed_draft_types = table.Column<int>(type: "integer", nullable: false)
          },
          constraints: table =>
          {
            table.PrimaryKey("pk_series", x => x.id);
          });

      // ============ DRAFTS <-- SERIES (nullable FK) ========================

      migrationBuilder.AddColumn<Guid>(
          name: "series_id",
          schema: "drafts",
          table: "drafts",
          type: "uuid",
          nullable: true);

      migrationBuilder.CreateIndex(
          name: "ix_drafts_series_id",
          schema: "drafts",
          table: "drafts",
          column: "series_id");

      migrationBuilder.AddForeignKey(
          name: "fk_drafts_series_series_id",
          schema: "drafts",
          table: "drafts",
          column: "series_id",
          principalSchema: "drafts",
          principalTable: "series",
          principalColumn: "id");

      // ============ CAMPAIGNS ========================

      migrationBuilder.CreateTable(
          name: "campaigns",
          schema: "drafts",
          columns: table => new
          {
            id = table.Column<Guid>(type: "uuid", nullable: false),
            slug = table.Column<string>(type: "text", nullable: false),
            name = table.Column<string>(type: "text", nullable: false)
          },
          constraints: table =>
          {
            table.PrimaryKey("pk_campaigns", x => x.id);
          });

      migrationBuilder.CreateIndex(
          name: "ix_campaigns_id",
          schema: "drafts",
          table: "campaigns",
          column: "id");

      migrationBuilder.CreateIndex(
          name: "ix_campaigns_slug",
          schema: "drafts",
          table: "campaigns",
          column: "slug",
          unique: true);

      // ============ DRAFTS <-> CAMPAIGNS (M:N) ========================

      migrationBuilder.CreateTable(
          name: "drafts_campaigns",
          schema: "drafts",
          columns: table => new
          {
            campaign_id = table.Column<Guid>(type: "uuid", nullable: false),
            draft_id = table.Column<Guid>(type: "uuid", nullable: false)
          },
          constraints: table =>
          {
            table.PrimaryKey("pk_drafts_campaigns", x => new { x.campaign_id, x.draft_id });
            table.ForeignKey(
                      name: "fk_drafts_campaigns_campaign_id",
                      column: x => x.campaign_id,
                      principalSchema: "drafts",
                      principalTable: "campaigns",
                      principalColumn: "id",
                      onDelete: ReferentialAction.Cascade);
            table.ForeignKey(
                      name: "fk_drafts_campaigns_draft_id",
                      column: x => x.draft_id,
                      principalSchema: "drafts",
                      principalTable: "drafts",
                      principalColumn: "id",
                      onDelete: ReferentialAction.Cascade);
          });

      migrationBuilder.CreateIndex(
          name: "ix_drafts_campaigns_draft_id",
          schema: "drafts",
          table: "drafts_campaigns",
          column: "draft_id");

      // ============ DRAFT PARTS & RELEASES ========================

      migrationBuilder.CreateTable(
          name: "draft_parts",
          schema: "drafts",
          columns: table => new
          {
            id = table.Column<Guid>(type: "uuid", nullable: false),
            draft_id = table.Column<Guid>(type: "uuid", nullable: false),
            part_index = table.Column<int>(type: "integer", nullable: false)
          },
          constraints: table =>
          {
            table.PrimaryKey("pk_draft_parts", x => x.id);
            table.ForeignKey(
                      name: "fk_draft_parts_drafts_draft_id",
                      column: x => x.draft_id,
                      principalSchema: "drafts",
                      principalTable: "drafts",
                      principalColumn: "id",
                      onDelete: ReferentialAction.Cascade);
          });

      migrationBuilder.CreateIndex(
          name: "ix_draft_parts_draft_id_part_index",
          schema: "drafts",
          table: "draft_parts",
          columns: new[] { "draft_id", "part_index" },
          unique: true);

      migrationBuilder.CreateTable(
          name: "draft_releases",
          schema: "drafts",
          columns: table => new
          {
            part_id = table.Column<Guid>(type: "uuid", nullable: false),
            release_channel = table.Column<int>(type: "integer", nullable: false),
            release_date = table.Column<DateOnly>(type: "date", nullable: false),
            created_on_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false)
          },
          constraints: table =>
          {
            table.PrimaryKey("pk_draft_releases", x => new { x.part_id, x.release_channel, x.release_date });
            table.ForeignKey(
                      name: "fk_draft_releases_draft_parts_part_id",
                      column: x => x.part_id,
                      principalSchema: "drafts",
                      principalTable: "draft_parts",
                      principalColumn: "id",
                      onDelete: ReferentialAction.Restrict);
          });

      migrationBuilder.CreateIndex(
          name: "ix_draft_releases_release_channel_release_date",
          schema: "drafts",
          table: "draft_releases",
          columns: new[] { "release_channel", "release_date" });

      // --- SEED: SERIES rows (names/ kinds/ policies)----
      migrationBuilder.InsertData(
        schema: "drafts",
        table: "series",
        columns: new[]
        {
          "id", "name", "kind", "canonical_policy", "continuity_scope", "continuity_date_rule", "required_draft_type", "default_draft_type", "allowed_draft_types"
        },
        values: new object[,]
        {
          { Guid.NewGuid(), "Default",                                        kind.Regular,             policy.Always,      scope.Global,   dateRule.AnyChannelFirstRelease,  null,                 null,                   draftTypeMask.All },
          { Guid.NewGuid(), "Franchise mini-Super",                           kind.FranchiseMiniSuper,  policy.Never,       scope.None,     dateRule.AnyChannelFirstRelease,  draftType.MiniSuper,  draftType.MiniSuper,    draftTypeMask.MiniSuper },
          { Guid.NewGuid(), "Bryan and Billy Ray's Nonagenarian In-Memoream", kind.InMemoriam,          policy.OnMainFeed,  scope.Series,   dateRule.MainFeedOnly,            draftType.Standard,   draftType.Standard,     draftTypeMask.Standard },
          { Guid.NewGuid(), "Legends Invitational",                           kind.Legends,             policy.Never,       scope.None,     dateRule.AnyChannelFirstRelease,  draftType.Mega,       draftType.Mega,         draftTypeMask.Mega },
          { Guid.NewGuid(), "Best Picture Nominee mini-Super",                kind.BestPictureNominee,  policy.Never,       scope.None,     dateRule.AnyChannelFirstRelease,  draftType.MiniSuper,  draftType.MiniSuper,    draftTypeMask.MiniSuper },
          { Guid.NewGuid(), "Patreon vs.",                                    kind.PatreonVs,           policy.OnMainFeed,  scope.Global,   dateRule.MainFeedOnly,            draftType.Standard,   draftType.Standard,     draftTypeMask.Standard },
          { Guid.NewGuid(), "Live Drafts",                                    kind.LiveDraft,           policy.OnMainFeed,  scope.Global,   dateRule.MainFeedOnly,            null,                 null,                   draftTypeMask.Standard | draftTypeMask.Super | draftTypeMask.Mega | draftTypeMask.MiniMega },
          { Guid.NewGuid(), "Special Drafts",                                 kind.Special,             policy.Never,       scope.None,     dateRule.AnyChannelFirstRelease,  null,                 draftType.Standard,     draftTypeMask.Standard | draftTypeMask.Super | draftTypeMask.Mega | draftTypeMask.MiniMega },
          { Guid.NewGuid(), "Speed Drafts",                                   kind.SpeedDrafts,         policy.Never,       scope.Series,   dateRule.AnyChannelFirstRelease,  draftType.Standard,   draftType.Standard,     draftTypeMask.Standard },
        });

      // --- SEED: CAMPAIGNS rows (slugs/ names)----
      migrationBuilder.InsertData(
        schema: "drafts",
        table: "campaigns",
        columns: new[] { "id", "slug", "name" },
        values: new object[,]
        {
          { Guid.NewGuid(), campaignSlugs.ScreamDrafts, "Scream Drafts" },
          { Guid.NewGuid(), campaignSlugs.BillyRay, "Billy Ray vs. Kyle" },
          { Guid.NewGuid(), campaignSlugs.KristmasEve, "Kristmas Eve" },
          { Guid.NewGuid(), campaignSlugs.PhilVsDana, "Phil vs. Dana" },
        }
        );

      // --- BACKFILL: 1 Part per Existing Draft ----
      migrationBuilder.Sql($"""
          insert into drafts.draft_parts (id, draft_id, part_index)
          select gen_random_uuid(), d.id, 1
          from drafts.drafts d
          where not exists (
            select 1 
            from drafts.draft_parts dp 
            where dp.draft_id = d.id
          );
        """);

      // --- Build a temporary map draft_id -> part_id for use in next step ----
      migrationBuilder.Sql($"""
          create temporary table temp_draft_part_map(
            draft_id uuid primary key,
            part_id uuid not null
          ) on commit drop;

          insert into temp_draft_part_map (draft_id, part_id)
          select dp.draft_id, dp.id
          from drafts.draft_parts dp
          where dp.part_index = 1;
        """);

      // --- BACKFILL: release dates -> per-part releases w/ channel inference ----
      // (Assumes old table `draft_release_dates(draft_id, release_date)` exists.
      //  Channel inference: episode_type==MainFeed => 'MainFeed', else 'Patreon'.)

      // Variant A: if episode_type is INT (values assumed: 0=MainFeed, 1=FranchiseMiniSuper, 2=InMemorium, 3=Legends, 4=BestPictureNominee, 5=PatreonsVs, 6=LiveDraft, 7=Special)
      migrationBuilder.Sql("""
      do $$
      begin
        if exists (select 1 from information_schema.columns
                   where table_schema='drafts' and table_name='drafts' and column_name='episode_type' and data_type in ('integer','smallint','bigint')) then
          insert into drafts.draft_releases(part_id, release_channel, release_date, created_on_utc)
          select m.part_id,
                 case when d.episode_type = 0 then 0 else 1 end,
                 drd.release_date,
                 now()
          from drafts.draft_release_date drd
          join temp_draft_part_map m on m.draft_id = drd.draft_id
          join drafts.drafts d on d.id = drd.draft_id;
        end if;
      end$$;
    """);

      // --- BACKFILL: attach SeriesId by legacy EpisodeType (if INT) -------------
      migrationBuilder.Sql("""
      do $$
      begin
        if exists (select 1 from information_schema.columns
                   where table_schema='drafts' and table_name='drafts' and column_name='episode_type' and data_type in ('integer','smallint','bigint')) then
          update drafts.drafts d set series_id = s.id
          from drafts.series s
          where (d.episode_type = 3 and s.name = 'Legends')      
             or (d.episode_type = 1 and s.name = 'Franchise mini-Super')       
             or (d.episode_type = 4 and s.name = 'Best Picture Nominee')      
             or (d.episode_type = 2 and s.name = 'In Memoriam')               
             or (d.episode_type = 5 and s.name = 'Patreon vs')                
             or (d.episode_type = 6 and s.name = 'Live Draft')
             or (d.episode_type = 7 and s.name = 'Special');                  
        end if;
      end$$;
    """);

      // --- BACKFILL: Scream Drafts (if legacy bool column exists) ---------------
      migrationBuilder.Sql("""
      do $$
      declare scream_id uuid;
      begin
        select id into scream_id from drafts.campaigns where slug='scream-drafts';
        if exists (select 1 from information_schema.columns
                    where table_schema='drafts' and table_name='drafts' and column_name='is_screamdrafts') then
          insert into drafts.draft_campaigns(draft_id, campaign_id)
          select d.id, scream_id
          from drafts.drafts d
          where coalesce((d.is_screamdrafts)::boolean, false) = true
          on conflict do nothing;
        end if;
      end$$;
    """);

      migrationBuilder.Sql($"""
      do $$
      begin
        -- 1) ALWAYS (Regular) => every legacy date is MainFeed
        insert into drafts.draft_releases(part_id, release_channel, release_date, created_on_utc)
        select distinct
          m.part_id,
          {releaseChannel.MainFeed},
          drd.release_date,
          now()
        from drafts.draft_release_date drd
        join temp_draft_part_map m on m.draft_id = drd.draft_id
        left join drafts.drafts d on d.id = drd.draft_id
        left join drafts.series s on s.id = d.series_id
        where d.series_id is null or s.canonical_policy = {policy.Always}
        on conflict (part_id, release_channel, release_date) do nothing;

        -- 2) NEVER => every legacy date is Patreon
        insert into drafts.draft_releases(part_id, release_channel, release_date, created_on_utc)
        select distinct
          m.part_id,
          {releaseChannel.Patreon},
          drd.release_date,
          now()
        from drafts.draft_release_date drd
        join temp_draft_part_map m on m.draft_id = drd.draft_id
        join drafts.drafts d on d.id = drd.draft_id
        join drafts.series s on s.id = d.series_id
        where s.canonical_policy = {policy.Never}
        on conflict (part_id, release_channel, release_date) do nothing;

        -- 3) ON_MAIN_FEED:
        -- 3a) Insert Patreon for the earliest date
        insert into drafts.draft_releases(part_id, release_channel, release_date, created_on_utc)
        select distinct
          m.part_id,
          {releaseChannel.Patreon},
          drd.release_date,
          now()
        from drafts.draft_release_date drd
        join temp_draft_part_map m on m.draft_id = drd.draft_id
        join drafts.drafts d on d.id = drd.draft_id
        join drafts.series s on s.id = d.series_id
        join (
          select drd.draft_id, min(drd.release_date) as min_date
          from drafts.draft_release_date drd
          group by drd.draft_id
        ) mi on mi.draft_id = drd.draft_id
        where s.canonical_policy = {policy.OnMainFeed}
          and drd.release_date = mi.min_date
        on conflict (part_id, release_channel, release_date) do nothing;

        -- 3b) If the earliest date appears twice (Patreon + MainFeed same day), also insert MainFeed for that date
        insert into drafts.draft_releases(part_id, release_channel, release_date, created_on_utc)
        select distinct
          m.part_id,
          {releaseChannel.MainFeed},
          dc.release_date,
          now()
        from (
          select drd.draft_id, drd.release_date, count(*) as cnt
          from drafts.draft_release_date drd
          group by drd.draft_id, drd.release_date
        ) dc
        join temp_draft_part_map m on m.draft_id = dc.draft_id
        join drafts.drafts d on d.id = dc.draft_id
        join drafts.series s on s.id = d.series_id
        join (
          select drd.draft_id, min(drd.release_date) as min_date
          from drafts.draft_release_date drd
          group by drd.draft_id
        ) mi on mi.draft_id = dc.draft_id
        where s.canonical_policy = {policy.OnMainFeed}
          and dc.release_date = mi.min_date
          and dc.cnt >= 2
        on conflict (part_id, release_channel, release_date) do nothing;

        -- 3c) Any later dates (strictly after the min) are MainFeed
        insert into drafts.draft_releases(part_id, release_channel, release_date, created_on_utc)
        select distinct
          m.part_id,
          {releaseChannel.MainFeed},
          drd.release_date,
          now()
        from drafts.draft_release_date drd
        join temp_draft_part_map m on m.draft_id = drd.draft_id
        join drafts.drafts d on d.id = drd.draft_id
        join drafts.series s on s.id = d.series_id
        join (
          select drd.draft_id, min(drd.release_date) as min_date
          from drafts.draft_release_date drd
          group by drd.draft_id
        ) mi on mi.draft_id = drd.draft_id
        where s.canonical_policy = {policy.OnMainFeed}
          and drd.release_date > mi.min_date
        on conflict (part_id, release_channel, release_date) do nothing;
      end $$;
      """);

      // --- CLEAN UP: drop legacy flags + old release table ----------------------
      // If an earlier experiment added draft_id to draft_releases, remove it safely.
      migrationBuilder.Sql("""
        do $$ begin
          if exists (select 1 from information_schema.columns
                     where table_schema='drafts' and table_name='draft_releases' and column_name='draft_id')
          then
            alter table drafts.draft_releases drop column draft_id;
          end if;
        end$$;
        """);

      // Drop Tables & Columns
      migrationBuilder.DropTable(
          name: "draft_release_date",
          schema: "drafts");

      migrationBuilder.DropColumn(
          name: "episode_type",
          schema: "drafts",
          table: "drafts");

      migrationBuilder.DropColumn(
          name: "is_patreon_only",
          schema: "drafts",
          table: "drafts");

      migrationBuilder.DropColumn(
          name: "is_scream_drafts",
          schema: "drafts",
          table: "drafts");

      migrationBuilder.DropColumn(
          name: "non_canonical",
          schema: "drafts",
          table: "drafts");

    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
      migrationBuilder.DropForeignKey(
          name: "fk_drafts_series_series_id",
          schema: "drafts",
          table: "drafts");

      migrationBuilder.DropTable(
          name: "draft_releases",
          schema: "drafts");

      migrationBuilder.DropTable(
          name: "drafts_campaigns",
          schema: "drafts");

      migrationBuilder.DropTable(
          name: "series",
          schema: "drafts");

      migrationBuilder.DropTable(
          name: "draft_parts",
          schema: "drafts");

      migrationBuilder.DropTable(
          name: "campaigns",
          schema: "drafts");

      migrationBuilder.DropIndex(
          name: "ix_drafts_series_id",
          schema: "drafts",
          table: "drafts");

      migrationBuilder.DropColumn(
          name: "series_id",
          schema: "drafts",
          table: "drafts");

      migrationBuilder.AddColumn<int>(
          name: "episode_type",
          schema: "drafts",
          table: "drafts",
          type: "integer",
          nullable: false,
          defaultValue: 0);

      migrationBuilder.AddColumn<bool>(
          name: "is_patreon_only",
          schema: "drafts",
          table: "drafts",
          type: "boolean",
          nullable: false,
          defaultValue: false);

      migrationBuilder.AddColumn<bool>(
          name: "is_scream_drafts",
          schema: "drafts",
          table: "drafts",
          type: "boolean",
          nullable: false,
          defaultValue: false);

      migrationBuilder.AddColumn<bool>(
          name: "non_canonical",
          schema: "drafts",
          table: "drafts",
          type: "boolean",
          nullable: false,
          defaultValue: false);

      migrationBuilder.CreateTable(
          name: "draft_release_date",
          schema: "drafts",
          columns: table => new
          {
            draft_id = table.Column<Guid>(type: "uuid", nullable: false),
            release_date = table.Column<DateOnly>(type: "date", nullable: false)
          },
          constraints: table =>
          {
            table.PrimaryKey("pk_draft_release_date", x => new { x.draft_id, x.release_date });
            table.ForeignKey(
                      name: "fk_draft_release_date_drafts_draft_id",
                      column: x => x.draft_id,
                      principalSchema: "drafts",
                      principalTable: "drafts",
                      principalColumn: "id",
                      onDelete: ReferentialAction.Cascade);
          });
    }
  }
}
