// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ScreenDrafts.Modules.Drafts.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class Add_Person_Profile_Fields : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "biography",
                schema: "drafts",
                table: "people",
                type: "text",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "bluesky_handle",
                schema: "drafts",
                table: "people",
                type: "character varying(100)",
                maxLength: 100,
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "instagram_handle",
                schema: "drafts",
                table: "people",
                type: "character varying(100)",
                maxLength: 100,
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "letterboxd_handle",
                schema: "drafts",
                table: "people",
                type: "character varying(100)",
                maxLength: 100,
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "location",
                schema: "drafts",
                table: "people",
                type: "character varying(200)",
                maxLength: 200,
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "twitter_handle",
                schema: "drafts",
                table: "people",
                type: "character varying(100)",
                maxLength: 100,
                nullable: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "biography",
                schema: "drafts",
                table: "people");

            migrationBuilder.DropColumn(
                name: "bluesky_handle",
                schema: "drafts",
                table: "people");

            migrationBuilder.DropColumn(
                name: "instagram_handle",
                schema: "drafts",
                table: "people");

            migrationBuilder.DropColumn(
                name: "letterboxd_handle",
                schema: "drafts",
                table: "people");

            migrationBuilder.DropColumn(
                name: "location",
                schema: "drafts",
                table: "people");

            migrationBuilder.DropColumn(
                name: "twitter_handle",
                schema: "drafts",
                table: "people");
        }
    }
}
