// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ScreenDrafts.Modules.Drafts.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class Add_Draft_Image_To_Draft : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "image_path",
                schema: "drafts",
                table: "drafts",
                type: "text",
                nullable: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "image_path",
                schema: "drafts",
                table: "drafts");
        }
    }
}

