// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ScreenDrafts.Modules.Drafts.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class Add_Draft_Part_Attendance : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "draft_part_attendances",
                schema: "drafts",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    public_id = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: false),
                    draft_part_id = table.Column<Guid>(type: "uuid", nullable: false),
                    person_public_id = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: false),
                    status = table.Column<int>(type: "integer", nullable: false),
                    created_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    updated_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_draft_part_attendances", x => x.id);
                });

            migrationBuilder.CreateIndex(
                name: "ix_draft_part_attendances_draft_part_id_person_public_id",
                schema: "drafts",
                table: "draft_part_attendances",
                columns: new[] { "draft_part_id", "person_public_id" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_draft_part_attendances_public_id",
                schema: "drafts",
                table: "draft_part_attendances",
                column: "public_id",
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "draft_part_attendances",
                schema: "drafts");
        }
    }
}

