// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ScreenDrafts.Modules.Drafts.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class Add_Tmdb_Id_Null : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<int>(
                name: "tmdb_id",
                schema: "drafts",
                table: "movies",
                type: "integer",
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "ix_movies_tmdb_id",
                schema: "drafts",
                table: "movies",
                column: "tmdb_id",
                unique: true,
                filter: "tmdb_id IS NOT NULL");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "ix_movies_tmdb_id",
                schema: "drafts",
                table: "movies");

            migrationBuilder.DropColumn(
                name: "tmdb_id",
                schema: "drafts",
                table: "movies");
        }
    }
}
