// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ScreenDrafts.Modules.Drafts.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class Update_Media : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<int>(
                name: "igdb_id",
                schema: "drafts",
                table: "movies",
                type: "integer",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "media_type",
                schema: "drafts",
                table: "movies",
                type: "integer",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<string>(
                name: "public_id",
                schema: "drafts",
                table: "movies",
                type: "text",
                nullable: false,
                defaultValue: "");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "igdb_id",
                schema: "drafts",
                table: "movies");

            migrationBuilder.DropColumn(
                name: "media_type",
                schema: "drafts",
                table: "movies");

            migrationBuilder.DropColumn(
                name: "public_id",
                schema: "drafts",
                table: "movies");
        }
    }
}
