// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ScreenDrafts.Modules.Drafts.Infrastructure.Database.Migrations
{
  /// <inheritdoc />
  public partial class RemoveCommissionerOverrideIdFromPick : Migration
  {
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
      migrationBuilder.DropForeignKey(
          name: "fk_picks_commissioner_overrides_commissioner_override_id",
          schema: "drafts",
          table: "picks");

      migrationBuilder.DropIndex(
          name: "ix_veto_overrides_veto_id_issued_by_participant_id",
          schema: "drafts",
          table: "veto_overrides");

      migrationBuilder.DropIndex(
          name: "ix_picks_commissioner_override_id",
          schema: "drafts",
          table: "picks");

      migrationBuilder.DropColumn(
          name: "commissioner_override_id",
          schema: "drafts",
          table: "picks");

      migrationBuilder.AlterColumn<int>(
          name: "min_position",
          schema: "drafts",
          table: "draft_parts",
          type: "integer",
          nullable: true,
          oldClrType: typeof(int),
          oldType: "integer");

      migrationBuilder.AlterColumn<int>(
          name: "max_position",
          schema: "drafts",
          table: "draft_parts",
          type: "integer",
          nullable: true,
          oldClrType: typeof(int),
          oldType: "integer");
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
      migrationBuilder.AddColumn<Guid>(
          name: "commissioner_override_id",
          schema: "drafts",
          table: "picks",
          type: "uuid",
          nullable: false,
          defaultValue: new Guid("00000000-0000-0000-0000-000000000000"));

      migrationBuilder.AlterColumn<int>(
          name: "min_position",
          schema: "drafts",
          table: "draft_parts",
          type: "integer",
          nullable: false,
          defaultValue: 0,
          oldClrType: typeof(int),
          oldType: "integer",
          oldNullable: true);

      migrationBuilder.AlterColumn<int>(
          name: "max_position",
          schema: "drafts",
          table: "draft_parts",
          type: "integer",
          nullable: false,
          defaultValue: 0,
          oldClrType: typeof(int),
          oldType: "integer",
          oldNullable: true);

      migrationBuilder.CreateIndex(
          name: "ix_veto_overrides_veto_id_issued_by_participant_id",
          schema: "drafts",
          table: "veto_overrides",
          columns: new[] { "veto_id", "issued_by_participant_id" },
          unique: true);

      migrationBuilder.CreateIndex(
          name: "ix_picks_commissioner_override_id",
          schema: "drafts",
          table: "picks",
          column: "commissioner_override_id",
          unique: true);

      migrationBuilder.AddForeignKey(
          name: "fk_picks_commissioner_overrides_commissioner_override_id",
          schema: "drafts",
          table: "picks",
          column: "commissioner_override_id",
          principalSchema: "drafts",
          principalTable: "commissioner_overrides",
          principalColumn: "id",
          onDelete: ReferentialAction.Cascade);
    }
  }
}
