// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ScreenDrafts.Modules.Drafts.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class Refactor_Movie_Configuration : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "ix_movies_tmdb_id",
                schema: "drafts",
                table: "movies");

            migrationBuilder.CreateIndex(
                name: "ix_movies_tmdb_id_media_type",
                schema: "drafts",
                table: "movies",
                columns: new[] { "tmdb_id", "media_type" },
                unique: true,
                filter: "tmdb_id IS NOT NULL");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "ix_movies_tmdb_id_media_type",
                schema: "drafts",
                table: "movies");

            migrationBuilder.CreateIndex(
                name: "ix_movies_tmdb_id",
                schema: "drafts",
                table: "movies",
                column: "tmdb_id",
                unique: true,
                filter: "tmdb_id IS NOT NULL");
        }
    }
}

