// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ScreenDrafts.Modules.Drafts.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class Add_SpeedDrafts : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<Guid>(
                name: "sub_draft_id",
                schema: "drafts",
                table: "vetoes",
                type: "uuid",
                nullable: true);

            migrationBuilder.AddColumn<Guid>(
                name: "sub_draft_id",
                schema: "drafts",
                table: "trivia_results",
                type: "uuid",
                nullable: true);

            migrationBuilder.AlterColumn<Guid>(
                name: "draft_part_id",
                schema: "drafts",
                table: "game_boards",
                type: "uuid",
                nullable: true,
                oldClrType: typeof(Guid),
                oldType: "uuid");

            migrationBuilder.AddColumn<Guid>(
                name: "sub_draft_id",
                schema: "drafts",
                table: "game_boards",
                type: "uuid",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "sub_draft_count",
                schema: "drafts",
                table: "draft_parts",
                type: "integer",
                nullable: true);

            migrationBuilder.CreateTable(
                name: "sub_drafts",
                schema: "drafts",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    public_id = table.Column<string>(type: "text", nullable: false),
                    draft_part_id = table.Column<Guid>(type: "uuid", nullable: false),
                    index = table.Column<int>(type: "integer", nullable: false),
                    subject_kind = table.Column<int>(type: "integer", nullable: false),
                    subject_name = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_sub_drafts", x => x.id);
                    table.ForeignKey(
                        name: "fk_sub_drafts_draft_parts_draft_part_id",
                        column: x => x.draft_part_id,
                        principalSchema: "drafts",
                        principalTable: "draft_parts",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "ix_game_boards_sub_draft_id",
                schema: "drafts",
                table: "game_boards",
                column: "sub_draft_id",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_sub_drafts_draft_part_id_index",
                schema: "drafts",
                table: "sub_drafts",
                columns: new[] { "draft_part_id", "index" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_sub_drafts_public_id",
                schema: "drafts",
                table: "sub_drafts",
                column: "public_id",
                unique: true);

            migrationBuilder.AddForeignKey(
                name: "fk_game_boards_sub_drafts_sub_draft_id",
                schema: "drafts",
                table: "game_boards",
                column: "sub_draft_id",
                principalSchema: "drafts",
                principalTable: "sub_drafts",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "fk_game_boards_sub_drafts_sub_draft_id",
                schema: "drafts",
                table: "game_boards");

            migrationBuilder.DropTable(
                name: "sub_drafts",
                schema: "drafts");

            migrationBuilder.DropIndex(
                name: "ix_game_boards_sub_draft_id",
                schema: "drafts",
                table: "game_boards");

            migrationBuilder.DropColumn(
                name: "sub_draft_id",
                schema: "drafts",
                table: "vetoes");

            migrationBuilder.DropColumn(
                name: "sub_draft_id",
                schema: "drafts",
                table: "trivia_results");

            migrationBuilder.DropColumn(
                name: "sub_draft_id",
                schema: "drafts",
                table: "game_boards");

            migrationBuilder.DropColumn(
                name: "sub_draft_count",
                schema: "drafts",
                table: "draft_parts");

            migrationBuilder.AlterColumn<Guid>(
                name: "draft_part_id",
                schema: "drafts",
                table: "game_boards",
                type: "uuid",
                nullable: false,
                defaultValue: new Guid("00000000-0000-0000-0000-000000000000"),
                oldClrType: typeof(Guid),
                oldType: "uuid",
                oldNullable: true);
        }
    }
}
