// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ScreenDrafts.Modules.Drafts.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class Add_DraftPosition_PublicId_NotNull : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<string>(
                name: "public_id",
                schema: "drafts",
                table: "draft_positions",
                type: "character varying(19)",
                maxLength: 19,
                nullable: false,
                defaultValue: "",
                oldClrType: typeof(string),
                oldType: "character varying(19)",
                oldMaxLength: 19,
                oldNullable: true);

            migrationBuilder.CreateIndex(
                name: "ix_draft_positions_public_id",
                schema: "drafts",
                table: "draft_positions",
                column: "public_id",
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "ix_draft_positions_public_id",
                schema: "drafts",
                table: "draft_positions");

            migrationBuilder.AlterColumn<string>(
                name: "public_id",
                schema: "drafts",
                table: "draft_positions",
                type: "character varying(19)",
                maxLength: 19,
                nullable: true,
                oldClrType: typeof(string),
                oldType: "character varying(19)",
                oldMaxLength: 19);
        }
    }
}
