// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ScreenDrafts.Modules.Drafts.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class Add_PlayedByParticipantIdentity_ToPicks : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<Guid>(
                name: "played_by_participant_id_value",
                schema: "drafts",
                table: "picks",
                type: "uuid",
                nullable: false,
                defaultValue: new Guid("00000000-0000-0000-0000-000000000000"));

            migrationBuilder.AddColumn<int>(
                name: "played_by_participant_kind_value",
                schema: "drafts",
                table: "picks",
                type: "integer",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.CreateIndex(
                name: "ix_picks_draft_part_id_played_by_participant_id_value_played_b",
                schema: "drafts",
                table: "picks",
                columns: new[] { "draft_part_id", "played_by_participant_id_value", "played_by_participant_kind_value" });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "ix_picks_draft_part_id_played_by_participant_id_value_played_b",
                schema: "drafts",
                table: "picks");

            migrationBuilder.DropColumn(
                name: "played_by_participant_id_value",
                schema: "drafts",
                table: "picks");

            migrationBuilder.DropColumn(
                name: "played_by_participant_kind_value",
                schema: "drafts",
                table: "picks");
        }
    }
}
