// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ScreenDrafts.Modules.Drafts.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class Add_DraftChannelRelease : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "fk_draft_releases_drafts_draft_id",
                schema: "drafts",
                table: "draft_releases");

            migrationBuilder.DropIndex(
                name: "ix_draft_releases_draft_id",
                schema: "drafts",
                table: "draft_releases");

            migrationBuilder.DropIndex(
                name: "ux_draft_releases_channel_episode_number",
                schema: "drafts",
                table: "draft_releases");

            migrationBuilder.DropColumn(
                name: "draft_id",
                schema: "drafts",
                table: "draft_releases");

            migrationBuilder.DropColumn(
                name: "episode_number",
                schema: "drafts",
                table: "draft_releases");

            migrationBuilder.CreateTable(
                name: "draft_channel_releases",
                schema: "drafts",
                columns: table => new
                {
                    draft_id = table.Column<Guid>(type: "uuid", nullable: false),
                    release_channel = table.Column<int>(type: "integer", nullable: false),
                    episode_number = table.Column<int>(type: "integer", nullable: true),
                    created_on_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_draft_channel_releases", x => new { x.draft_id, x.release_channel });
                    table.ForeignKey(
                        name: "fk_draft_channel_releases_drafts_draft_id",
                        column: x => x.draft_id,
                        principalSchema: "drafts",
                        principalTable: "drafts",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "ux_draft_channel_releases_channel_episode_number",
                schema: "drafts",
                table: "draft_channel_releases",
                columns: new[] { "release_channel", "episode_number" },
                unique: true,
                filter: "episode_number is not null");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "draft_channel_releases",
                schema: "drafts");

            migrationBuilder.AddColumn<Guid>(
                name: "draft_id",
                schema: "drafts",
                table: "draft_releases",
                type: "uuid",
                nullable: false,
                defaultValue: new Guid("00000000-0000-0000-0000-000000000000"));

            migrationBuilder.AddColumn<int>(
                name: "episode_number",
                schema: "drafts",
                table: "draft_releases",
                type: "integer",
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "ix_draft_releases_draft_id",
                schema: "drafts",
                table: "draft_releases",
                column: "draft_id");

            migrationBuilder.CreateIndex(
                name: "ux_draft_releases_channel_episode_number",
                schema: "drafts",
                table: "draft_releases",
                columns: new[] { "release_channel", "episode_number", "draft_id" },
                unique: true,
                filter: "episode_number is not null");

            migrationBuilder.AddForeignKey(
                name: "fk_draft_releases_drafts_draft_id",
                schema: "drafts",
                table: "draft_releases",
                column: "draft_id",
                principalSchema: "drafts",
                principalTable: "drafts",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);
        }
    }
}
