// <auto-generated />
using System;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

using ScreenDrafts.Modules.Drafts.Infrastructure.Database;

#nullable disable

namespace ScreenDrafts.Modules.Drafts.Infrastructure.Database.Migrations
{
  [DbContext(typeof(DraftsDbContext))]
  partial class DraftsDbContextModelSnapshot : ModelSnapshot
  {
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
          .HasDefaultSchema("drafts")
          .HasAnnotation("ProductVersion", "9.0.8")
          .HasAnnotation("Relational:MaxIdentifierLength", 63);

      NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

      modelBuilder.Entity("ScreenDrafts.Common.Infrastructure.Inbox.InboxMessage", b =>
          {
            b.Property<Guid>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("uuid")
                      .HasColumnName("id");

            b.Property<string>("Content")
                      .IsRequired()
                      .HasMaxLength(2000)
                      .HasColumnType("jsonb")
                      .HasColumnName("content");

            b.Property<string>("Error")
                      .HasColumnType("text")
                      .HasColumnName("error");

            b.Property<DateTime>("OccurredOnUtc")
                      .HasColumnType("timestamp with time zone")
                      .HasColumnName("occurred_on_utc");

            b.Property<DateTime?>("ProcessedOnUtc")
                      .HasColumnType("timestamp with time zone")
                      .HasColumnName("processed_on_utc");

            b.Property<string>("Type")
                      .IsRequired()
                      .HasColumnType("text")
                      .HasColumnName("type");

            b.HasKey("Id")
                      .HasName("pk_inbox_messages");

            b.ToTable("inbox_messages", "drafts");
          });

      modelBuilder.Entity("ScreenDrafts.Common.Infrastructure.Inbox.InboxMessageConsumer", b =>
          {
            b.Property<Guid>("InboxMessageId")
                      .HasColumnType("uuid")
                      .HasColumnName("inbox_message_id");

            b.Property<string>("Name")
                      .HasMaxLength(500)
                      .HasColumnType("character varying(500)")
                      .HasColumnName("name");

            b.HasKey("InboxMessageId", "Name")
                      .HasName("pk_inbox_message_consumers");

            b.ToTable("inbox_message_consumers", "drafts");
          });

      modelBuilder.Entity("ScreenDrafts.Common.Infrastructure.Outbox.OutboxMessage", b =>
          {
            b.Property<Guid>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("uuid")
                      .HasColumnName("id");

            b.Property<string>("Content")
                      .IsRequired()
                      .HasMaxLength(2000)
                      .HasColumnType("jsonb")
                      .HasColumnName("content");

            b.Property<string>("Error")
                      .HasColumnType("text")
                      .HasColumnName("error");

            b.Property<DateTime>("OccurredOnUtc")
                      .HasColumnType("timestamp with time zone")
                      .HasColumnName("occurred_on_utc");

            b.Property<DateTime?>("ProcessedOnUtc")
                      .HasColumnType("timestamp with time zone")
                      .HasColumnName("processed_on_utc");

            b.Property<string>("Type")
                      .IsRequired()
                      .HasColumnType("text")
                      .HasColumnName("type");

            b.HasKey("Id")
                      .HasName("pk_outbox_messages");

            b.ToTable("outbox_messages", "drafts");
          });

      modelBuilder.Entity("ScreenDrafts.Common.Infrastructure.Outbox.OutboxMessageConsumer", b =>
          {
            b.Property<Guid>("OutboxMessageId")
                      .HasColumnType("uuid")
                      .HasColumnName("outbox_message_id");

            b.Property<string>("Name")
                      .HasMaxLength(500)
                      .HasColumnType("character varying(500)")
                      .HasColumnName("name");

            b.HasKey("OutboxMessageId", "Name")
                      .HasName("pk_outbox_message_consumers");

            b.ToTable("outbox_message_consumers", "drafts");
          });

      modelBuilder.Entity("ScreenDrafts.Modules.Drafts.Domain.Drafters.Drafter", b =>
          {
            b.Property<Guid>("Id")
                      .HasColumnType("uuid")
                      .HasColumnName("id");

            b.Property<Guid>("PersonId")
                      .HasColumnType("uuid")
                      .HasColumnName("person_id");

            b.Property<int>("ReadableId")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("integer")
                      .HasColumnName("readable_id");

            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReadableId"));

            b.HasKey("Id")
                      .HasName("pk_drafters");

            b.HasIndex("PersonId")
                      .IsUnique()
                      .HasDatabaseName("ix_drafters_person_id");

            b.ToTable("drafters", "drafts");
          });

      modelBuilder.Entity("ScreenDrafts.Modules.Drafts.Domain.Drafters.DrafterTeam", b =>
          {
            b.Property<Guid>("Id")
                      .HasColumnType("uuid")
                      .HasColumnName("id");

            b.Property<string>("Name")
                      .IsRequired()
                      .HasMaxLength(100)
                      .HasColumnType("character varying(100)")
                      .HasColumnName("name");

            b.Property<int>("NumberOfDrafters")
                      .HasColumnType("integer")
                      .HasColumnName("number_of_drafters");

            b.HasKey("Id")
                      .HasName("pk_drafter_teams");

            b.ToTable("drafter_teams", "drafts");
          });

      modelBuilder.Entity("ScreenDrafts.Modules.Drafts.Domain.Drafters.Entities.RolloverVeto", b =>
          {
            b.Property<Guid>("Id")
                      .HasColumnType("uuid")
                      .HasColumnName("id");

            b.Property<Guid?>("DrafterId")
                      .HasColumnType("uuid")
                      .HasColumnName("drafter_id");

            b.Property<Guid?>("DrafterTeamId")
                      .HasColumnType("uuid")
                      .HasColumnName("drafter_team_id");

            b.Property<Guid>("FromDraftId")
                      .HasColumnType("uuid")
                      .HasColumnName("from_draft_id");

            b.Property<bool>("IsUsed")
                      .HasColumnType("boolean")
                      .HasColumnName("is_used");

            b.Property<Guid?>("ToDraftId")
                      .HasColumnType("uuid")
                      .HasColumnName("to_draft_id");

            b.HasKey("Id")
                      .HasName("pk_rollover_vetoes");

            b.HasIndex("DrafterId")
                      .IsUnique()
                      .HasDatabaseName("ix_rollover_vetoes_drafter_id");

            b.HasIndex("DrafterTeamId")
                      .IsUnique()
                      .HasDatabaseName("ix_rollover_vetoes_drafter_team_id");

            b.ToTable("rollover_vetoes", "drafts");
          });

      modelBuilder.Entity("ScreenDrafts.Modules.Drafts.Domain.Drafters.Entities.RolloverVetoOverride", b =>
          {
            b.Property<Guid>("Id")
                      .HasColumnType("uuid")
                      .HasColumnName("id");

            b.Property<Guid?>("DrafterId")
                      .HasColumnType("uuid")
                      .HasColumnName("drafter_id");

            b.Property<Guid?>("DrafterTeamId")
                      .HasColumnType("uuid")
                      .HasColumnName("drafter_team_id");

            b.Property<Guid>("FromDraftId")
                      .HasColumnType("uuid")
                      .HasColumnName("from_draft_id");

            b.Property<bool>("IsUsed")
                      .HasColumnType("boolean")
                      .HasColumnName("is_used");

            b.Property<Guid?>("ToDraftId")
                      .HasColumnType("uuid")
                      .HasColumnName("to_draft_id");

            b.HasKey("Id")
                      .HasName("pk_rollover_veto_overrides");

            b.HasIndex("DrafterId")
                      .IsUnique()
                      .HasDatabaseName("ix_rollover_veto_overrides_drafter_id");

            b.HasIndex("DrafterTeamId")
                      .IsUnique()
                      .HasDatabaseName("ix_rollover_veto_overrides_drafter_team_id");

            b.ToTable("rollover_veto_overrides", "drafts");
          });

      modelBuilder.Entity("ScreenDrafts.Modules.Drafts.Domain.Drafters.Entities.Veto", b =>
          {
            b.Property<Guid>("Id")
                      .HasColumnType("uuid")
                      .HasColumnName("id");

            b.Property<Guid?>("DrafterId")
                      .HasColumnType("uuid")
                      .HasColumnName("drafter_id");

            b.Property<Guid?>("DrafterTeamId")
                      .HasColumnType("uuid")
                      .HasColumnName("drafter_team_id");

            b.Property<Guid>("PickId")
                      .HasColumnType("uuid")
                      .HasColumnName("pick_id");

            b.HasKey("Id")
                      .HasName("pk_vetoes");

            b.HasIndex("DrafterId")
                      .HasDatabaseName("ix_vetoes_drafter_id");

            b.HasIndex("DrafterTeamId")
                      .HasDatabaseName("ix_vetoes_drafter_team_id");

            b.HasIndex("PickId")
                      .IsUnique()
                      .HasDatabaseName("ix_vetoes_pick_id");

            b.ToTable("vetoes", "drafts");
          });

      modelBuilder.Entity("ScreenDrafts.Modules.Drafts.Domain.Drafters.Entities.VetoOverride", b =>
          {
            b.Property<Guid>("Id")
                      .HasColumnType("uuid")
                      .HasColumnName("id");

            b.Property<Guid?>("DrafterId")
                      .HasColumnType("uuid")
                      .HasColumnName("drafter_id");

            b.Property<Guid?>("DrafterTeamId")
                      .HasColumnType("uuid")
                      .HasColumnName("drafter_team_id");

            b.Property<Guid>("VetoId")
                      .HasColumnType("uuid")
                      .HasColumnName("veto_id");

            b.HasKey("Id")
                      .HasName("pk_veto_overrides");

            b.HasIndex("DrafterId")
                      .HasDatabaseName("ix_veto_overrides_drafter_id");

            b.HasIndex("DrafterTeamId")
                      .HasDatabaseName("ix_veto_overrides_drafter_team_id");

            b.HasIndex("VetoId")
                      .IsUnique()
                      .HasDatabaseName("ix_veto_overrides_veto_id");

            b.ToTable("veto_overrides", "drafts");
          });

      modelBuilder.Entity("ScreenDrafts.Modules.Drafts.Domain.Drafts.Draft", b =>
          {
            b.Property<Guid>("Id")
                      .HasColumnType("uuid")
                      .HasColumnName("id");

            b.Property<DateTime>("CreatedAtUtc")
                      .HasColumnType("timestamp with time zone")
                      .HasColumnName("created_at_utc");

            b.Property<string>("Description")
                      .HasColumnType("text")
                      .HasColumnName("description");

            b.Property<int>("DraftStatus")
                      .HasColumnType("integer")
                      .HasColumnName("draft_status");

            b.Property<int>("DraftType")
                      .HasColumnType("integer")
                      .HasColumnName("draft_type");

            b.Property<int?>("EpisodeNumber")
                      .HasColumnType("integer")
                      .HasColumnName("episode_number");

            b.Property<int>("ReadableId")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("integer")
                      .HasColumnName("readable_id");

            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReadableId"));

            b.Property<Guid?>("SeriesId")
                      .HasColumnType("uuid")
                      .HasColumnName("series_id");

            b.Property<string>("Title")
                      .IsRequired()
                      .HasMaxLength(255)
                      .HasColumnType("character varying(255)")
                      .HasColumnName("title");

            b.Property<int>("TotalDrafterTeams")
                      .HasColumnType("integer")
                      .HasColumnName("total_drafter_teams");

            b.Property<int>("TotalDrafters")
                      .HasColumnType("integer")
                      .HasColumnName("total_drafters");

            b.Property<int>("TotalHosts")
                      .HasColumnType("integer")
                      .HasColumnName("total_hosts");

            b.Property<int>("TotalPicks")
                      .HasColumnType("integer")
                      .HasColumnName("total_picks");

            b.Property<DateTime?>("UpdatedAtUtc")
                      .HasColumnType("timestamp with time zone")
                      .HasColumnName("updated_at_utc");

            b.HasKey("Id")
                      .HasName("pk_drafts");

            b.HasIndex("ReadableId")
                      .IsUnique()
                      .HasDatabaseName("ix_drafts_readable_id");

            b.HasIndex("SeriesId")
                      .HasDatabaseName("ix_drafts_series_id");

            b.ToTable("drafts", "drafts");
          });

      modelBuilder.Entity("ScreenDrafts.Modules.Drafts.Domain.Drafts.Entities.Campaign", b =>
          {
            b.Property<Guid>("Id")
                      .HasColumnType("uuid")
                      .HasColumnName("id");

            b.Property<string>("Name")
                      .IsRequired()
                      .HasColumnType("text")
                      .HasColumnName("name");

            b.Property<string>("Slug")
                      .IsRequired()
                      .HasColumnType("text")
                      .HasColumnName("slug");

            b.HasKey("Id")
                      .HasName("pk_campaigns");

            b.HasIndex("Id")
                      .HasDatabaseName("ix_campaigns_id");

            b.HasIndex("Slug")
                      .IsUnique()
                      .HasDatabaseName("ix_campaigns_slug");

            b.ToTable("campaigns", "drafts");
          });

      modelBuilder.Entity("ScreenDrafts.Modules.Drafts.Domain.Drafts.Entities.Category", b =>
          {
            b.Property<Guid>("Id")
                      .HasColumnType("uuid")
                      .HasColumnName("id");

            b.Property<DateTime>("CreatedOnUtc")
                      .HasColumnType("timestamp with time zone")
                      .HasColumnName("created_on_utc");

            b.Property<string>("Description")
                      .HasMaxLength(500)
                      .HasColumnType("character varying(500)")
                      .HasColumnName("description");

            b.Property<DateTime?>("ModifiedOnUtc")
                      .HasColumnType("timestamp with time zone")
                      .HasColumnName("modified_on_utc");

            b.Property<string>("Name")
                      .IsRequired()
                      .HasMaxLength(100)
                      .HasColumnType("character varying(100)")
                      .HasColumnName("name");

            b.HasKey("Id")
                      .HasName("pk_categories");

            b.ToTable("categories", "drafts");
          });

      modelBuilder.Entity("ScreenDrafts.Modules.Drafts.Domain.Drafts.Entities.CommissionerOverride", b =>
          {
            b.Property<Guid>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("uuid")
                      .HasColumnName("id");

            b.Property<Guid>("PickId")
                      .HasColumnType("uuid")
                      .HasColumnName("pick_id");

            b.HasKey("Id")
                      .HasName("pk_commissioner_overrides");

            b.HasIndex("PickId")
                      .IsUnique()
                      .HasDatabaseName("ix_commissioner_overrides_pick_id");

            b.ToTable("commissioner_overrides", "drafts");
          });

      modelBuilder.Entity("ScreenDrafts.Modules.Drafts.Domain.Drafts.Entities.DraftCategory", b =>
          {
            b.Property<Guid>("DraftId")
                      .HasColumnType("uuid")
                      .HasColumnName("draft_id");

            b.Property<Guid>("CategoryId")
                      .HasColumnType("uuid")
                      .HasColumnName("category_id");

            b.HasKey("DraftId", "CategoryId")
                      .HasName("pk_draft_categories");

            b.HasIndex("CategoryId")
                      .HasDatabaseName("ix_draft_categories_category_id");

            b.ToTable("draft_categories", "drafts");
          });

      modelBuilder.Entity("ScreenDrafts.Modules.Drafts.Domain.Drafts.Entities.DraftHost", b =>
          {
            b.Property<Guid>("DraftId")
                      .HasColumnType("uuid")
                      .HasColumnName("draft_id");

            b.Property<Guid>("HostId")
                      .HasColumnType("uuid")
                      .HasColumnName("host_id");

            b.Property<int>("Role")
                      .HasColumnType("integer")
                      .HasColumnName("role");

            b.HasKey("DraftId", "HostId")
                      .HasName("pk_draft_hosts");

            b.HasIndex("DraftId")
                      .IsUnique()
                      .HasDatabaseName("ux_draft_hosts_one_primary_per_draft")
                      .HasFilter("role = 0");

            b.HasIndex("HostId")
                      .HasDatabaseName("ix_draft_hosts_host_id");

            b.ToTable("draft_hosts", "drafts");
          });

      modelBuilder.Entity("ScreenDrafts.Modules.Drafts.Domain.Drafts.Entities.DraftPart", b =>
          {
            b.Property<Guid>("Id")
                      .HasColumnType("uuid")
                      .HasColumnName("id");

            b.Property<Guid>("DraftId")
                      .HasColumnType("uuid")
                      .HasColumnName("draft_id");

            b.Property<int>("PartIndex")
                      .HasColumnType("integer")
                      .HasColumnName("part_index");

            b.HasKey("Id")
                      .HasName("pk_draft_parts");

            b.HasIndex("DraftId", "PartIndex")
                      .IsUnique()
                      .HasDatabaseName("ix_draft_parts_draft_id_part_index");

            b.ToTable("draft_parts", "drafts");
          });

      modelBuilder.Entity("ScreenDrafts.Modules.Drafts.Domain.Drafts.Entities.DraftPosition", b =>
          {
            b.Property<Guid>("Id")
                      .HasColumnType("uuid")
                      .HasColumnName("id");

            b.Property<Guid?>("DrafterId")
                      .HasColumnType("uuid")
                      .HasColumnName("drafter_id");

            b.Property<Guid?>("DrafterTeamId")
                      .HasColumnType("uuid")
                      .HasColumnName("drafter_team_id");

            b.Property<Guid>("GameBoardId")
                      .HasColumnType("uuid")
                      .HasColumnName("game_board_id");

            b.Property<bool>("HasBonusVeto")
                      .HasColumnType("boolean")
                      .HasColumnName("has_bonus_veto");

            b.Property<bool>("HasBonusVetoOverride")
                      .HasColumnType("boolean")
                      .HasColumnName("has_bonus_veto_override");

            b.Property<string>("Name")
                      .IsRequired()
                      .HasMaxLength(50)
                      .HasColumnType("character varying(50)")
                      .HasColumnName("name");

            b.Property<string>("Picks")
                      .IsRequired()
                      .HasColumnType("text")
                      .HasColumnName("picks");

            b.HasKey("Id")
                      .HasName("pk_draft_positions");

            b.HasIndex("DrafterId")
                      .HasDatabaseName("ix_draft_positions_drafter_id");

            b.HasIndex("DrafterTeamId")
                      .HasDatabaseName("ix_draft_positions_drafter_team_id");

            b.HasIndex("GameBoardId")
                      .HasDatabaseName("ix_draft_positions_game_board_id");

            b.ToTable("draft_positions", "drafts");
          });

      modelBuilder.Entity("ScreenDrafts.Modules.Drafts.Domain.Drafts.Entities.DraftRelease", b =>
          {
            b.Property<Guid>("PartId")
                      .HasColumnType("uuid")
                      .HasColumnName("part_id");

            b.Property<int>("ReleaseChannel")
                      .HasColumnType("integer")
                      .HasColumnName("release_channel");

            b.Property<DateOnly>("ReleaseDate")
                      .HasColumnType("date")
                      .HasColumnName("release_date");

            b.Property<DateTime>("CreatedOnUtc")
                      .HasColumnType("timestamp with time zone")
                      .HasColumnName("created_on_utc");

            b.HasKey("PartId", "ReleaseChannel", "ReleaseDate")
                      .HasName("pk_draft_releases");

            b.HasIndex("ReleaseChannel", "ReleaseDate")
                      .HasDatabaseName("ix_draft_releases_release_channel_release_date");

            b.ToTable("draft_releases", "drafts");
          });

      modelBuilder.Entity("ScreenDrafts.Modules.Drafts.Domain.Drafts.Entities.DrafterDraftStats", b =>
          {
            b.Property<Guid>("Id")
                      .HasColumnType("uuid")
                      .HasColumnName("id");

            b.Property<Guid>("DraftId")
                      .HasColumnType("uuid")
                      .HasColumnName("draft_id");

            b.Property<int>("CommissionerOverrides")
                      .HasColumnType("integer")
                      .HasColumnName("commissioner_overrides");

            b.Property<Guid?>("DrafterId")
                      .HasColumnType("uuid")
                      .HasColumnName("drafter_id");

            b.Property<Guid?>("DrafterTeamId")
                      .HasColumnType("uuid")
                      .HasColumnName("drafter_team_id");

            b.Property<int>("RolloverVeto")
                      .HasColumnType("integer")
                      .HasColumnName("rollover_veto");

            b.Property<int?>("RolloverVetoOverride")
                      .HasColumnType("integer")
                      .HasColumnName("rollover_veto_override");

            b.Property<int>("StartingVetoes")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("integer")
                      .HasDefaultValue(1)
                      .HasColumnName("starting_vetoes");

            b.Property<int?>("TriviaVetoOverrides")
                      .HasColumnType("integer")
                      .HasColumnName("trivia_veto_overrides");

            b.Property<int>("TriviaVetoes")
                      .HasColumnType("integer")
                      .HasColumnName("trivia_vetoes");

            b.Property<int?>("VetoOverridesUsed")
                      .HasColumnType("integer")
                      .HasColumnName("veto_overrides_used");

            b.Property<int>("VetoesUsed")
                      .HasColumnType("integer")
                      .HasColumnName("vetoes_used");

            b.HasKey("Id", "DraftId")
                      .HasName("pk_drafter_draft_stats");

            b.HasIndex("DraftId")
                      .HasDatabaseName("ix_drafter_draft_stats_draft_id");

            b.HasIndex("DrafterId")
                      .HasDatabaseName("ix_drafter_draft_stats_drafter_id");

            b.HasIndex("DrafterTeamId")
                      .HasDatabaseName("ix_drafter_draft_stats_drafter_team_id");

            b.ToTable("drafter_draft_stats", "drafts");
          });

      modelBuilder.Entity("ScreenDrafts.Modules.Drafts.Domain.Drafts.Entities.GameBoard", b =>
          {
            b.Property<Guid>("Id")
                      .HasColumnType("uuid")
                      .HasColumnName("id");

            b.Property<Guid>("DraftId")
                      .HasColumnType("uuid")
                      .HasColumnName("draft_id");

            b.HasKey("Id")
                      .HasName("pk_game_boards");

            b.HasIndex("DraftId")
                      .IsUnique()
                      .HasDatabaseName("ix_game_boards_draft_id");

            b.ToTable("game_boards", "drafts");
          });

      modelBuilder.Entity("ScreenDrafts.Modules.Drafts.Domain.Drafts.Entities.Host", b =>
          {
            b.Property<Guid>("Id")
                      .HasColumnType("uuid")
                      .HasColumnName("id");

            b.Property<Guid>("PersonId")
                      .HasColumnType("uuid")
                      .HasColumnName("person_id");

            b.Property<int>("ReadableId")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("integer")
                      .HasColumnName("readable_id");

            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReadableId"));

            b.HasKey("Id")
                      .HasName("pk_hosts");

            b.HasIndex("PersonId")
                      .IsUnique()
                      .HasDatabaseName("ix_hosts_person_id");

            b.ToTable("hosts", "drafts");
          });

      modelBuilder.Entity("ScreenDrafts.Modules.Drafts.Domain.Drafts.Entities.Movie", b =>
          {
            b.Property<Guid>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("uuid")
                      .HasColumnName("id");

            b.Property<string>("ImdbId")
                      .IsRequired()
                      .HasColumnType("text")
                      .HasColumnName("imdb_id");

            b.Property<string>("MovieTitle")
                      .IsRequired()
                      .HasColumnType("text")
                      .HasColumnName("movie_title");

            b.HasKey("Id")
                      .HasName("pk_movies");

            b.ToTable("movies", "drafts");
          });

      modelBuilder.Entity("ScreenDrafts.Modules.Drafts.Domain.Drafts.Entities.Pick", b =>
          {
            b.Property<Guid>("Id")
                      .HasColumnType("uuid")
                      .HasColumnName("id");

            b.Property<Guid>("DraftId")
                      .HasColumnType("uuid")
                      .HasColumnName("draft_id");

            b.Property<Guid?>("DrafterId")
                      .HasColumnType("uuid")
                      .HasColumnName("drafter_id");

            b.Property<Guid?>("DrafterTeamId")
                      .HasColumnType("uuid")
                      .HasColumnName("drafter_team_id");

            b.Property<Guid>("MovieId")
                      .HasColumnType("uuid")
                      .HasColumnName("movie_id");

            b.Property<int>("PlayOrder")
                      .HasColumnType("integer")
                      .HasColumnName("play_order");

            b.Property<int>("Position")
                      .HasColumnType("integer")
                      .HasColumnName("position");

            b.HasKey("Id")
                      .HasName("pk_picks");

            b.HasIndex("DrafterId")
                      .HasDatabaseName("ix_picks_drafter_id");

            b.HasIndex("DrafterTeamId")
                      .HasDatabaseName("ix_picks_drafter_team_id");

            b.HasIndex("MovieId")
                      .HasDatabaseName("ix_picks_movie_id");

            b.HasIndex("DraftId", "PlayOrder")
                      .HasDatabaseName("ix_picks_draft_id_play_order");

            b.HasIndex("DraftId", "Position", "MovieId", "PlayOrder")
                      .IsUnique()
                      .HasDatabaseName("ix_picks_draft_id_position_movie_id_play_order");

            b.ToTable("picks", "drafts");
          });

      modelBuilder.Entity("ScreenDrafts.Modules.Drafts.Domain.Drafts.Entities.Series", b =>
          {
            b.Property<Guid>("Id")
                      .HasColumnType("uuid")
                      .HasColumnName("id");

            b.Property<int>("AllowedDraftTypes")
                      .HasColumnType("integer")
                      .HasColumnName("allowed_draft_types");

            b.Property<int>("CanonicalPolicy")
                      .HasColumnType("integer")
                      .HasColumnName("canonical_policy");

            b.Property<int>("ContinuityDateRule")
                      .HasColumnType("integer")
                      .HasColumnName("continuity_date_rule");

            b.Property<int>("ContinuityScope")
                      .HasColumnType("integer")
                      .HasColumnName("continuity_scope");

            b.Property<int?>("DefaultDraftType")
                      .HasColumnType("integer")
                      .HasColumnName("default_draft_type");

            b.Property<int>("Kind")
                      .HasColumnType("integer")
                      .HasColumnName("kind");

            b.Property<string>("Name")
                      .IsRequired()
                      .HasColumnType("text")
                      .HasColumnName("name");

            b.Property<int?>("RequiredDraftType")
                      .HasColumnType("integer")
                      .HasColumnName("required_draft_type");

            b.HasKey("Id")
                      .HasName("pk_series");

            b.ToTable("series", "drafts");
          });

      modelBuilder.Entity("ScreenDrafts.Modules.Drafts.Domain.Drafts.Entities.TriviaResult", b =>
          {
            b.Property<Guid>("Id")
                      .HasColumnType("uuid")
                      .HasColumnName("id");

            b.Property<Guid>("DraftId")
                      .HasColumnType("uuid")
                      .HasColumnName("draft_id");

            b.Property<Guid?>("DrafterId")
                      .HasColumnType("uuid")
                      .HasColumnName("drafter_id");

            b.Property<Guid?>("DrafterTeamId")
                      .HasColumnType("uuid")
                      .HasColumnName("drafter_team_id");

            b.Property<int>("Position")
                      .HasColumnType("integer")
                      .HasColumnName("position");

            b.Property<int>("QuestionsWon")
                      .HasColumnType("integer")
                      .HasColumnName("questions_won");

            b.HasKey("Id")
                      .HasName("pk_trivia_results");

            b.HasIndex("DraftId")
                      .HasDatabaseName("ix_trivia_results_draft_id");

            b.HasIndex("DrafterId")
                      .HasDatabaseName("ix_trivia_results_drafter_id");

            b.HasIndex("DrafterTeamId")
                      .HasDatabaseName("ix_trivia_results_drafter_team_id");

            b.ToTable("trivia_results", "drafts");
          });

      modelBuilder.Entity("ScreenDrafts.Modules.Drafts.Domain.People.Person", b =>
          {
            b.Property<Guid>("Id")
                      .HasColumnType("uuid")
                      .HasColumnName("id");

            b.Property<string>("DisplayName")
                      .HasColumnType("text")
                      .HasColumnName("display_name");

            b.Property<string>("FirstName")
                      .IsRequired()
                      .HasColumnType("text")
                      .HasColumnName("first_name");

            b.Property<string>("LastName")
                      .IsRequired()
                      .HasColumnType("text")
                      .HasColumnName("last_name");

            b.Property<Guid?>("UserId")
                      .HasColumnType("uuid")
                      .HasColumnName("user_id");

            b.HasKey("Id")
                      .HasName("pk_people");

            b.ToTable("people", "drafts");
          });

      modelBuilder.Entity("drafter_team_drafter", b =>
          {
            b.Property<Guid>("drafter_id")
                      .HasColumnType("uuid")
                      .HasColumnName("drafter_id");

            b.Property<Guid>("drafter_team_id")
                      .HasColumnType("uuid")
                      .HasColumnName("drafter_team_id");

            b.HasKey("drafter_id", "drafter_team_id")
                      .HasName("pk_drafter_team_drafter");

            b.HasIndex("drafter_team_id")
                      .HasDatabaseName("ix_drafter_team_drafter_drafter_team_id");

            b.ToTable("drafter_team_drafter", "drafts");
          });

      modelBuilder.Entity("drafts_campaigns", b =>
          {
            b.Property<Guid>("campaign_id")
                      .HasColumnType("uuid")
                      .HasColumnName("campaign_id");

            b.Property<Guid>("draft_id")
                      .HasColumnType("uuid")
                      .HasColumnName("draft_id");

            b.HasKey("campaign_id", "draft_id")
                      .HasName("pk_drafts_campaigns");

            b.HasIndex("draft_id")
                      .HasDatabaseName("ix_drafts_campaigns_draft_id");

            b.ToTable("drafts_campaigns", "drafts");
          });

      modelBuilder.Entity("drafts_drafter_teams", b =>
          {
            b.Property<Guid>("draft_id")
                      .HasColumnType("uuid")
                      .HasColumnName("draft_id");

            b.Property<Guid>("drafter_team_id")
                      .HasColumnType("uuid")
                      .HasColumnName("drafter_team_id");

            b.HasKey("draft_id", "drafter_team_id")
                      .HasName("pk_drafts_drafter_teams");

            b.HasIndex("drafter_team_id")
                      .HasDatabaseName("ix_drafts_drafter_teams_drafter_team_id");

            b.ToTable("drafts_drafter_teams", "drafts");
          });

      modelBuilder.Entity("drafts_drafters", b =>
          {
            b.Property<Guid>("draft_id")
                      .HasColumnType("uuid")
                      .HasColumnName("draft_id");

            b.Property<Guid>("drafter_id")
                      .HasColumnType("uuid")
                      .HasColumnName("drafter_id");

            b.HasKey("draft_id", "drafter_id")
                      .HasName("pk_drafts_drafters");

            b.HasIndex("drafter_id")
                      .HasDatabaseName("ix_drafts_drafters_drafter_id");

            b.ToTable("drafts_drafters", "drafts");
          });

      modelBuilder.Entity("ScreenDrafts.Modules.Drafts.Domain.Drafters.Drafter", b =>
          {
            b.HasOne("ScreenDrafts.Modules.Drafts.Domain.People.Person", "Person")
                      .WithOne("DrafterProfile")
                      .HasForeignKey("ScreenDrafts.Modules.Drafts.Domain.Drafters.Drafter", "PersonId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired()
                      .HasConstraintName("fk_drafters_people_person_id");

            b.Navigation("Person");
          });

      modelBuilder.Entity("ScreenDrafts.Modules.Drafts.Domain.Drafters.Entities.RolloverVeto", b =>
          {
            b.HasOne("ScreenDrafts.Modules.Drafts.Domain.Drafters.Drafter", "Drafter")
                      .WithOne("RolloverVeto")
                      .HasForeignKey("ScreenDrafts.Modules.Drafts.Domain.Drafters.Entities.RolloverVeto", "DrafterId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .HasConstraintName("fk_rollover_vetoes_drafters_drafter_id");

            b.HasOne("ScreenDrafts.Modules.Drafts.Domain.Drafters.DrafterTeam", "DrafterTeam")
                      .WithOne("RolloverVeto")
                      .HasForeignKey("ScreenDrafts.Modules.Drafts.Domain.Drafters.Entities.RolloverVeto", "DrafterTeamId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .HasConstraintName("fk_rollover_vetoes_drafter_teams_drafter_team_id");

            b.Navigation("Drafter");

            b.Navigation("DrafterTeam");
          });

      modelBuilder.Entity("ScreenDrafts.Modules.Drafts.Domain.Drafters.Entities.RolloverVetoOverride", b =>
          {
            b.HasOne("ScreenDrafts.Modules.Drafts.Domain.Drafters.Drafter", "Drafter")
                      .WithOne("RolloverVetoOverride")
                      .HasForeignKey("ScreenDrafts.Modules.Drafts.Domain.Drafters.Entities.RolloverVetoOverride", "DrafterId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .HasConstraintName("fk_rollover_veto_overrides_drafters_drafter_id");

            b.HasOne("ScreenDrafts.Modules.Drafts.Domain.Drafters.DrafterTeam", "DrafterTeam")
                      .WithOne("RolloverVetoOverride")
                      .HasForeignKey("ScreenDrafts.Modules.Drafts.Domain.Drafters.Entities.RolloverVetoOverride", "DrafterTeamId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .HasConstraintName("fk_rollover_veto_overrides_drafter_teams_drafter_team_id");

            b.Navigation("Drafter");

            b.Navigation("DrafterTeam");
          });

      modelBuilder.Entity("ScreenDrafts.Modules.Drafts.Domain.Drafters.Entities.Veto", b =>
          {
            b.HasOne("ScreenDrafts.Modules.Drafts.Domain.Drafters.Drafter", "Drafter")
                      .WithMany("Vetoes")
                      .HasForeignKey("DrafterId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .HasConstraintName("fk_vetoes_drafters_drafter_id");

            b.HasOne("ScreenDrafts.Modules.Drafts.Domain.Drafters.DrafterTeam", "DrafterTeam")
                      .WithMany("Vetoes")
                      .HasForeignKey("DrafterTeamId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .HasConstraintName("fk_vetoes_drafter_teams_drafter_team_id");

            b.HasOne("ScreenDrafts.Modules.Drafts.Domain.Drafts.Entities.Pick", "Pick")
                      .WithOne("Veto")
                      .HasForeignKey("ScreenDrafts.Modules.Drafts.Domain.Drafters.Entities.Veto", "PickId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired()
                      .HasConstraintName("fk_vetoes_picks_pick_id");

            b.Navigation("Drafter");

            b.Navigation("DrafterTeam");

            b.Navigation("Pick");
          });

      modelBuilder.Entity("ScreenDrafts.Modules.Drafts.Domain.Drafters.Entities.VetoOverride", b =>
          {
            b.HasOne("ScreenDrafts.Modules.Drafts.Domain.Drafters.Drafter", "Drafter")
                      .WithMany("VetoOverrides")
                      .HasForeignKey("DrafterId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .HasConstraintName("fk_veto_overrides_drafters_drafter_id");

            b.HasOne("ScreenDrafts.Modules.Drafts.Domain.Drafters.DrafterTeam", "DrafterTeam")
                      .WithMany("VetoOverrides")
                      .HasForeignKey("DrafterTeamId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .HasConstraintName("fk_veto_overrides_drafter_teams_drafter_team_id");

            b.HasOne("ScreenDrafts.Modules.Drafts.Domain.Drafters.Entities.Veto", "Veto")
                      .WithOne("VetoOverride")
                      .HasForeignKey("ScreenDrafts.Modules.Drafts.Domain.Drafters.Entities.VetoOverride", "VetoId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired()
                      .HasConstraintName("fk_veto_overrides_vetoes_veto_id");

            b.Navigation("Drafter");

            b.Navigation("DrafterTeam");

            b.Navigation("Veto");
          });

      modelBuilder.Entity("ScreenDrafts.Modules.Drafts.Domain.Drafts.Draft", b =>
          {
            b.HasOne("ScreenDrafts.Modules.Drafts.Domain.Drafts.Entities.Series", "Series")
                      .WithMany()
                      .HasForeignKey("SeriesId")
                      .HasConstraintName("fk_drafts_series_series_id");

            b.Navigation("Series");
          });

      modelBuilder.Entity("ScreenDrafts.Modules.Drafts.Domain.Drafts.Entities.CommissionerOverride", b =>
          {
            b.HasOne("ScreenDrafts.Modules.Drafts.Domain.Drafts.Entities.Pick", "Pick")
                      .WithOne("CommissionerOverride")
                      .HasForeignKey("ScreenDrafts.Modules.Drafts.Domain.Drafts.Entities.CommissionerOverride", "PickId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired()
                      .HasConstraintName("fk_commissioner_overrides_picks_pick_id");

            b.Navigation("Pick");
          });

      modelBuilder.Entity("ScreenDrafts.Modules.Drafts.Domain.Drafts.Entities.DraftCategory", b =>
          {
            b.HasOne("ScreenDrafts.Modules.Drafts.Domain.Drafts.Entities.Category", "Category")
                      .WithMany("DraftCategories")
                      .HasForeignKey("CategoryId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired()
                      .HasConstraintName("fk_draft_categories_categories_category_id");

            b.HasOne("ScreenDrafts.Modules.Drafts.Domain.Drafts.Draft", "Draft")
                      .WithMany("DraftCategories")
                      .HasForeignKey("DraftId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired()
                      .HasConstraintName("fk_draft_categories_drafts_draft_id");

            b.Navigation("Category");

            b.Navigation("Draft");
          });

      modelBuilder.Entity("ScreenDrafts.Modules.Drafts.Domain.Drafts.Entities.DraftHost", b =>
          {
            b.HasOne("ScreenDrafts.Modules.Drafts.Domain.Drafts.Draft", "Draft")
                      .WithMany("DraftHosts")
                      .HasForeignKey("DraftId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired()
                      .HasConstraintName("fk_draft_hosts_drafts_draft_id");

            b.HasOne("ScreenDrafts.Modules.Drafts.Domain.Drafts.Entities.Host", "Host")
                      .WithMany("Drafts")
                      .HasForeignKey("HostId")
                      .OnDelete(DeleteBehavior.Restrict)
                      .IsRequired()
                      .HasConstraintName("fk_draft_hosts_hosts_host_id");

            b.Navigation("Draft");

            b.Navigation("Host");
          });

      modelBuilder.Entity("ScreenDrafts.Modules.Drafts.Domain.Drafts.Entities.DraftPart", b =>
          {
            b.HasOne("ScreenDrafts.Modules.Drafts.Domain.Drafts.Draft", "Draft")
                      .WithMany("Parts")
                      .HasForeignKey("DraftId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired()
                      .HasConstraintName("fk_draft_parts_drafts_draft_id");

            b.Navigation("Draft");
          });

      modelBuilder.Entity("ScreenDrafts.Modules.Drafts.Domain.Drafts.Entities.DraftPosition", b =>
          {
            b.HasOne("ScreenDrafts.Modules.Drafts.Domain.Drafters.Drafter", "Drafter")
                      .WithMany()
                      .HasForeignKey("DrafterId")
                      .OnDelete(DeleteBehavior.Restrict)
                      .HasConstraintName("fk_draft_positions_drafters_drafter_id");

            b.HasOne("ScreenDrafts.Modules.Drafts.Domain.Drafters.DrafterTeam", "DrafterTeam")
                      .WithMany()
                      .HasForeignKey("DrafterTeamId")
                      .OnDelete(DeleteBehavior.Restrict)
                      .HasConstraintName("fk_draft_positions_drafter_teams_drafter_team_id");

            b.HasOne("ScreenDrafts.Modules.Drafts.Domain.Drafts.Entities.GameBoard", "GameBoard")
                      .WithMany("DraftPositions")
                      .HasForeignKey("GameBoardId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired()
                      .HasConstraintName("fk_draft_positions_game_boards_game_board_id");

            b.Navigation("Drafter");

            b.Navigation("DrafterTeam");

            b.Navigation("GameBoard");
          });

      modelBuilder.Entity("ScreenDrafts.Modules.Drafts.Domain.Drafts.Entities.DraftRelease", b =>
          {
            b.HasOne("ScreenDrafts.Modules.Drafts.Domain.Drafts.Entities.DraftPart", "DraftPart")
                      .WithMany("Releases")
                      .HasForeignKey("PartId")
                      .OnDelete(DeleteBehavior.Restrict)
                      .IsRequired()
                      .HasConstraintName("fk_draft_releases_draft_parts_part_id");

            b.Navigation("DraftPart");
          });

      modelBuilder.Entity("ScreenDrafts.Modules.Drafts.Domain.Drafts.Entities.DrafterDraftStats", b =>
          {
            b.HasOne("ScreenDrafts.Modules.Drafts.Domain.Drafts.Draft", "Draft")
                      .WithMany("DrafterStats")
                      .HasForeignKey("DraftId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired()
                      .HasConstraintName("fk_drafter_draft_stats_drafts_draft_id");

            b.HasOne("ScreenDrafts.Modules.Drafts.Domain.Drafters.Drafter", "Drafter")
                      .WithMany("DraftStats")
                      .HasForeignKey("DrafterId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .HasConstraintName("fk_drafter_draft_stats_drafters_drafter_id");

            b.HasOne("ScreenDrafts.Modules.Drafts.Domain.Drafters.DrafterTeam", "DrafterTeam")
                      .WithMany("DraftStats")
                      .HasForeignKey("DrafterTeamId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .HasConstraintName("fk_drafter_draft_stats_drafter_teams_drafter_team_id");

            b.Navigation("Draft");

            b.Navigation("Drafter");

            b.Navigation("DrafterTeam");
          });

      modelBuilder.Entity("ScreenDrafts.Modules.Drafts.Domain.Drafts.Entities.GameBoard", b =>
          {
            b.HasOne("ScreenDrafts.Modules.Drafts.Domain.Drafts.Draft", "Draft")
                      .WithOne("GameBoard")
                      .HasForeignKey("ScreenDrafts.Modules.Drafts.Domain.Drafts.Entities.GameBoard", "DraftId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired()
                      .HasConstraintName("fk_game_boards_drafts_draft_id");

            b.Navigation("Draft");
          });

      modelBuilder.Entity("ScreenDrafts.Modules.Drafts.Domain.Drafts.Entities.Host", b =>
          {
            b.HasOne("ScreenDrafts.Modules.Drafts.Domain.People.Person", "Person")
                      .WithOne("HostProfile")
                      .HasForeignKey("ScreenDrafts.Modules.Drafts.Domain.Drafts.Entities.Host", "PersonId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired()
                      .HasConstraintName("fk_hosts_people_person_id");

            b.Navigation("Person");
          });

      modelBuilder.Entity("ScreenDrafts.Modules.Drafts.Domain.Drafts.Entities.Pick", b =>
          {
            b.HasOne("ScreenDrafts.Modules.Drafts.Domain.Drafts.Draft", "Draft")
                      .WithMany("Picks")
                      .HasForeignKey("DraftId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired()
                      .HasConstraintName("fk_picks_drafts_draft_id");

            b.HasOne("ScreenDrafts.Modules.Drafts.Domain.Drafters.Drafter", "Drafter")
                      .WithMany("Picks")
                      .HasForeignKey("DrafterId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .HasConstraintName("fk_picks_drafters_drafter_id");

            b.HasOne("ScreenDrafts.Modules.Drafts.Domain.Drafters.DrafterTeam", "DrafterTeam")
                      .WithMany("Picks")
                      .HasForeignKey("DrafterTeamId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .HasConstraintName("fk_picks_drafter_teams_drafter_team_id");

            b.HasOne("ScreenDrafts.Modules.Drafts.Domain.Drafts.Entities.Movie", "Movie")
                      .WithMany("Picks")
                      .HasForeignKey("MovieId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired()
                      .HasConstraintName("fk_picks_movies_movie_id");

            b.Navigation("Draft");

            b.Navigation("Drafter");

            b.Navigation("DrafterTeam");

            b.Navigation("Movie");
          });

      modelBuilder.Entity("ScreenDrafts.Modules.Drafts.Domain.Drafts.Entities.TriviaResult", b =>
          {
            b.HasOne("ScreenDrafts.Modules.Drafts.Domain.Drafts.Draft", "Draft")
                      .WithMany("TriviaResults")
                      .HasForeignKey("DraftId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired()
                      .HasConstraintName("fk_trivia_results_drafts_draft_id");

            b.HasOne("ScreenDrafts.Modules.Drafts.Domain.Drafters.Drafter", "Drafter")
                      .WithMany()
                      .HasForeignKey("DrafterId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .HasConstraintName("fk_trivia_results_drafters_drafter_id");

            b.HasOne("ScreenDrafts.Modules.Drafts.Domain.Drafters.DrafterTeam", "DrafterTeam")
                      .WithMany()
                      .HasForeignKey("DrafterTeamId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .HasConstraintName("fk_trivia_results_drafter_teams_drafter_team_id");

            b.Navigation("Draft");

            b.Navigation("Drafter");

            b.Navigation("DrafterTeam");
          });

      modelBuilder.Entity("drafter_team_drafter", b =>
          {
            b.HasOne("ScreenDrafts.Modules.Drafts.Domain.Drafters.Drafter", null)
                      .WithMany()
                      .HasForeignKey("drafter_id")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired()
                      .HasConstraintName("fk_drafter_team_drafter_drafters_drafter_id");

            b.HasOne("ScreenDrafts.Modules.Drafts.Domain.Drafters.DrafterTeam", null)
                      .WithMany()
                      .HasForeignKey("drafter_team_id")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired()
                      .HasConstraintName("fk_drafter_team_drafter_drafter_teams_drafter_team_id");
          });

      modelBuilder.Entity("drafts_campaigns", b =>
          {
            b.HasOne("ScreenDrafts.Modules.Drafts.Domain.Drafts.Entities.Campaign", null)
                      .WithMany()
                      .HasForeignKey("campaign_id")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired()
                      .HasConstraintName("fk_drafts_campaigns_campaign_id");

            b.HasOne("ScreenDrafts.Modules.Drafts.Domain.Drafts.Draft", null)
                      .WithMany()
                      .HasForeignKey("draft_id")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired()
                      .HasConstraintName("fk_drafts_campaigns_draft_id");
          });

      modelBuilder.Entity("drafts_drafter_teams", b =>
          {
            b.HasOne("ScreenDrafts.Modules.Drafts.Domain.Drafts.Draft", null)
                      .WithMany()
                      .HasForeignKey("draft_id")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired()
                      .HasConstraintName("fk_drafts_drafter_teams_drafts_draft_id");

            b.HasOne("ScreenDrafts.Modules.Drafts.Domain.Drafters.DrafterTeam", null)
                      .WithMany()
                      .HasForeignKey("drafter_team_id")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired()
                      .HasConstraintName("fk_drafts_drafter_teams_drafter_teams_drafter_team_id");
          });

      modelBuilder.Entity("drafts_drafters", b =>
          {
            b.HasOne("ScreenDrafts.Modules.Drafts.Domain.Drafts.Draft", null)
                      .WithMany()
                      .HasForeignKey("draft_id")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired()
                      .HasConstraintName("fk_drafts_drafters_drafts_draft_id");

            b.HasOne("ScreenDrafts.Modules.Drafts.Domain.Drafters.Drafter", null)
                      .WithMany()
                      .HasForeignKey("drafter_id")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired()
                      .HasConstraintName("fk_drafts_drafters_drafters_drafter_id");
          });

      modelBuilder.Entity("ScreenDrafts.Modules.Drafts.Domain.Drafters.Drafter", b =>
          {
            b.Navigation("DraftStats");

            b.Navigation("Picks");

            b.Navigation("RolloverVeto");

            b.Navigation("RolloverVetoOverride");

            b.Navigation("VetoOverrides");

            b.Navigation("Vetoes");
          });

      modelBuilder.Entity("ScreenDrafts.Modules.Drafts.Domain.Drafters.DrafterTeam", b =>
          {
            b.Navigation("DraftStats");

            b.Navigation("Picks");

            b.Navigation("RolloverVeto");

            b.Navigation("RolloverVetoOverride");

            b.Navigation("VetoOverrides");

            b.Navigation("Vetoes");
          });

      modelBuilder.Entity("ScreenDrafts.Modules.Drafts.Domain.Drafters.Entities.Veto", b =>
          {
            b.Navigation("VetoOverride")
                      .IsRequired();
          });

      modelBuilder.Entity("ScreenDrafts.Modules.Drafts.Domain.Drafts.Draft", b =>
          {
            b.Navigation("DraftCategories");

            b.Navigation("DraftHosts");

            b.Navigation("DrafterStats");

            b.Navigation("GameBoard");

            b.Navigation("Parts");

            b.Navigation("Picks");

            b.Navigation("TriviaResults");
          });

      modelBuilder.Entity("ScreenDrafts.Modules.Drafts.Domain.Drafts.Entities.Category", b =>
          {
            b.Navigation("DraftCategories");
          });

      modelBuilder.Entity("ScreenDrafts.Modules.Drafts.Domain.Drafts.Entities.DraftPart", b =>
          {
            b.Navigation("Releases");
          });

      modelBuilder.Entity("ScreenDrafts.Modules.Drafts.Domain.Drafts.Entities.GameBoard", b =>
          {
            b.Navigation("DraftPositions");
          });

      modelBuilder.Entity("ScreenDrafts.Modules.Drafts.Domain.Drafts.Entities.Host", b =>
          {
            b.Navigation("Drafts");
          });

      modelBuilder.Entity("ScreenDrafts.Modules.Drafts.Domain.Drafts.Entities.Movie", b =>
          {
            b.Navigation("Picks");
          });

      modelBuilder.Entity("ScreenDrafts.Modules.Drafts.Domain.Drafts.Entities.Pick", b =>
          {
            b.Navigation("CommissionerOverride")
                      .IsRequired();

            b.Navigation("Veto");
          });

      modelBuilder.Entity("ScreenDrafts.Modules.Drafts.Domain.People.Person", b =>
          {
            b.Navigation("DrafterProfile");

            b.Navigation("HostProfile");
          });
#pragma warning restore 612, 618
    }
  }
}
