// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ScreenDrafts.Modules.GuestDrafts.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class Expand_Guest_Drafts : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<int>(
                name: "awarded_fungible_tokens",
                schema: "guest_drafts",
                table: "guest_draft_participants",
                type: "integer",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<int>(
                name: "awarded_veto_overrides",
                schema: "guest_drafts",
                table: "guest_draft_participants",
                type: "integer",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<int>(
                name: "awarded_vetoes",
                schema: "guest_drafts",
                table: "guest_draft_participants",
                type: "integer",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<int>(
                name: "commissioner_overrides",
                schema: "guest_drafts",
                table: "guest_draft_participants",
                type: "integer",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<int>(
                name: "fungible_tokens",
                schema: "guest_drafts",
                table: "guest_draft_participants",
                type: "integer",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<int>(
                name: "fungible_tokens_used",
                schema: "guest_drafts",
                table: "guest_draft_participants",
                type: "integer",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<int>(
                name: "starting_vetoes",
                schema: "guest_drafts",
                table: "guest_draft_participants",
                type: "integer",
                nullable: false,
                defaultValue: 1);

            migrationBuilder.AddColumn<int>(
                name: "veto_overrides_used",
                schema: "guest_drafts",
                table: "guest_draft_participants",
                type: "integer",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<int>(
                name: "vetoes_used",
                schema: "guest_drafts",
                table: "guest_draft_participants",
                type: "integer",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.CreateTable(
                name: "guest_draft_game_boards",
                schema: "guest_drafts",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    guest_draft_id = table.Column<Guid>(type: "uuid", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_guest_draft_game_boards", x => x.id);
                    table.ForeignKey(
                        name: "fk_guest_draft_game_boards_guest_drafts_guest_draft_id",
                        column: x => x.guest_draft_id,
                        principalSchema: "guest_drafts",
                        principalTable: "guest_drafts",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "guest_draft_picks",
                schema: "guest_drafts",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    guest_draft_id = table.Column<Guid>(type: "uuid", nullable: false),
                    position = table.Column<int>(type: "integer", nullable: false),
                    play_order = table.Column<int>(type: "integer", nullable: false),
                    movie_public_id = table.Column<string>(type: "character varying(19)", maxLength: 19, nullable: false),
                    played_by_participant_id = table.Column<Guid>(type: "uuid", nullable: false),
                    reveal_authorized_participant_id = table.Column<Guid>(type: "uuid", nullable: true),
                    acted_by_public_id = table.Column<string>(type: "character varying(19)", maxLength: 19, nullable: true),
                    revealed_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_guest_draft_picks", x => x.id);
                    table.ForeignKey(
                        name: "fk_guest_draft_picks_guest_draft_participants_played_by_partic",
                        column: x => x.played_by_participant_id,
                        principalSchema: "guest_drafts",
                        principalTable: "guest_draft_participants",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_guest_draft_picks_guest_draft_participants_reveal_authorize",
                        column: x => x.reveal_authorized_participant_id,
                        principalSchema: "guest_drafts",
                        principalTable: "guest_draft_participants",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_guest_draft_picks_guest_drafts_guest_draft_id",
                        column: x => x.guest_draft_id,
                        principalSchema: "guest_drafts",
                        principalTable: "guest_drafts",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "guest_draft_positions",
                schema: "guest_drafts",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    game_board_id = table.Column<Guid>(type: "uuid", nullable: false),
                    public_id = table.Column<string>(type: "character varying(19)", maxLength: 19, nullable: false),
                    name = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: false),
                    picks = table.Column<int[]>(type: "integer[]", nullable: false),
                    has_bonus_veto = table.Column<bool>(type: "boolean", nullable: false),
                    has_bonus_veto_override = table.Column<bool>(type: "boolean", nullable: false),
                    has_bonus_fungible_token = table.Column<bool>(type: "boolean", nullable: false),
                    assigned_to_participant_id = table.Column<Guid>(type: "uuid", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_guest_draft_positions", x => x.id);
                    table.ForeignKey(
                        name: "fk_guest_draft_positions_guest_draft_game_boards_game_board_id",
                        column: x => x.game_board_id,
                        principalSchema: "guest_drafts",
                        principalTable: "guest_draft_game_boards",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "guest_draft_commissioner_overrides",
                schema: "guest_drafts",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    pick_id = table.Column<Guid>(type: "uuid", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_guest_draft_commissioner_overrides", x => x.id);
                    table.ForeignKey(
                        name: "fk_guest_draft_commissioner_overrides_guest_draft_picks_pick_id",
                        column: x => x.pick_id,
                        principalSchema: "guest_drafts",
                        principalTable: "guest_draft_picks",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "guest_draft_pick_history",
                schema: "guest_drafts",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    kind = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: false),
                    issuer_participant_id = table.Column<Guid>(type: "uuid", nullable: true),
                    note = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: true),
                    occurred_on_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    guest_draft_pick_id = table.Column<Guid>(type: "uuid", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_guest_draft_pick_history", x => x.id);
                    table.ForeignKey(
                        name: "fk_guest_draft_pick_history_guest_draft_picks_guest_draft_pick",
                        column: x => x.guest_draft_pick_id,
                        principalSchema: "guest_drafts",
                        principalTable: "guest_draft_picks",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "guest_draft_vetoes",
                schema: "guest_drafts",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    target_pick_id = table.Column<Guid>(type: "uuid", nullable: false),
                    sequence = table.Column<int>(type: "integer", nullable: false),
                    issued_by_participant_id = table.Column<Guid>(type: "uuid", nullable: false),
                    acted_by_public_id = table.Column<string>(type: "character varying(19)", maxLength: 19, nullable: true),
                    spent_from_fungible_pool = table.Column<bool>(type: "boolean", nullable: false),
                    is_overridden = table.Column<bool>(type: "boolean", nullable: false),
                    occurred_on = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    note = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_guest_draft_vetoes", x => x.id);
                    table.ForeignKey(
                        name: "fk_guest_draft_vetoes_guest_draft_participants_issued_by_parti",
                        column: x => x.issued_by_participant_id,
                        principalSchema: "guest_drafts",
                        principalTable: "guest_draft_participants",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_guest_draft_vetoes_guest_draft_picks_target_pick_id",
                        column: x => x.target_pick_id,
                        principalSchema: "guest_drafts",
                        principalTable: "guest_draft_picks",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "guest_draft_veto_overrides",
                schema: "guest_drafts",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    veto_id = table.Column<Guid>(type: "uuid", nullable: false),
                    issued_by_participant_id = table.Column<Guid>(type: "uuid", nullable: false),
                    acted_by_public_id = table.Column<string>(type: "character varying(19)", maxLength: 19, nullable: true),
                    spent_from_fungible_pool = table.Column<bool>(type: "boolean", nullable: false),
                    note = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_guest_draft_veto_overrides", x => x.id);
                    table.ForeignKey(
                        name: "fk_guest_draft_veto_overrides_guest_draft_participants_issued_",
                        column: x => x.issued_by_participant_id,
                        principalSchema: "guest_drafts",
                        principalTable: "guest_draft_participants",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_guest_draft_veto_overrides_guest_draft_vetoes_veto_id",
                        column: x => x.veto_id,
                        principalSchema: "guest_drafts",
                        principalTable: "guest_draft_vetoes",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "ix_guest_draft_commissioner_overrides_pick_id",
                schema: "guest_drafts",
                table: "guest_draft_commissioner_overrides",
                column: "pick_id",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_guest_draft_game_boards_guest_draft_id",
                schema: "guest_drafts",
                table: "guest_draft_game_boards",
                column: "guest_draft_id",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_guest_draft_pick_history_guest_draft_pick_id",
                schema: "guest_drafts",
                table: "guest_draft_pick_history",
                column: "guest_draft_pick_id");

            migrationBuilder.CreateIndex(
                name: "ix_guest_draft_picks_guest_draft_id_play_order",
                schema: "guest_drafts",
                table: "guest_draft_picks",
                columns: new[] { "guest_draft_id", "play_order" });

            migrationBuilder.CreateIndex(
                name: "ix_guest_draft_picks_played_by_participant_id",
                schema: "guest_drafts",
                table: "guest_draft_picks",
                column: "played_by_participant_id");

            migrationBuilder.CreateIndex(
                name: "ix_guest_draft_picks_reveal_authorized_participant_id",
                schema: "guest_drafts",
                table: "guest_draft_picks",
                column: "reveal_authorized_participant_id");

            migrationBuilder.CreateIndex(
                name: "ix_guest_draft_positions_game_board_id",
                schema: "guest_drafts",
                table: "guest_draft_positions",
                column: "game_board_id");

            migrationBuilder.CreateIndex(
                name: "ix_guest_draft_positions_public_id",
                schema: "guest_drafts",
                table: "guest_draft_positions",
                column: "public_id",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_guest_draft_veto_overrides_issued_by_participant_id",
                schema: "guest_drafts",
                table: "guest_draft_veto_overrides",
                column: "issued_by_participant_id");

            migrationBuilder.CreateIndex(
                name: "ix_guest_draft_veto_overrides_veto_id",
                schema: "guest_drafts",
                table: "guest_draft_veto_overrides",
                column: "veto_id",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_guest_draft_vetoes_issued_by_participant_id",
                schema: "guest_drafts",
                table: "guest_draft_vetoes",
                column: "issued_by_participant_id");

            migrationBuilder.CreateIndex(
                name: "ix_guest_draft_vetoes_target_pick_id_sequence",
                schema: "guest_drafts",
                table: "guest_draft_vetoes",
                columns: new[] { "target_pick_id", "sequence" },
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "guest_draft_commissioner_overrides",
                schema: "guest_drafts");

            migrationBuilder.DropTable(
                name: "guest_draft_pick_history",
                schema: "guest_drafts");

            migrationBuilder.DropTable(
                name: "guest_draft_positions",
                schema: "guest_drafts");

            migrationBuilder.DropTable(
                name: "guest_draft_veto_overrides",
                schema: "guest_drafts");

            migrationBuilder.DropTable(
                name: "guest_draft_game_boards",
                schema: "guest_drafts");

            migrationBuilder.DropTable(
                name: "guest_draft_vetoes",
                schema: "guest_drafts");

            migrationBuilder.DropTable(
                name: "guest_draft_picks",
                schema: "guest_drafts");

            migrationBuilder.DropColumn(
                name: "awarded_fungible_tokens",
                schema: "guest_drafts",
                table: "guest_draft_participants");

            migrationBuilder.DropColumn(
                name: "awarded_veto_overrides",
                schema: "guest_drafts",
                table: "guest_draft_participants");

            migrationBuilder.DropColumn(
                name: "awarded_vetoes",
                schema: "guest_drafts",
                table: "guest_draft_participants");

            migrationBuilder.DropColumn(
                name: "commissioner_overrides",
                schema: "guest_drafts",
                table: "guest_draft_participants");

            migrationBuilder.DropColumn(
                name: "fungible_tokens",
                schema: "guest_drafts",
                table: "guest_draft_participants");

            migrationBuilder.DropColumn(
                name: "fungible_tokens_used",
                schema: "guest_drafts",
                table: "guest_draft_participants");

            migrationBuilder.DropColumn(
                name: "starting_vetoes",
                schema: "guest_drafts",
                table: "guest_draft_participants");

            migrationBuilder.DropColumn(
                name: "veto_overrides_used",
                schema: "guest_drafts",
                table: "guest_draft_participants");

            migrationBuilder.DropColumn(
                name: "vetoes_used",
                schema: "guest_drafts",
                table: "guest_draft_participants");
        }
    }
}

