// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ScreenDrafts.Modules.GuestDrafts.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class Refactor_GuestDrafts_Module : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "guest_draft_commissioner_overrides",
                schema: "guest_drafts");

            migrationBuilder.DropTable(
                name: "guest_draft_pick_history",
                schema: "guest_drafts");

            migrationBuilder.DropTable(
                name: "guest_draft_positions",
                schema: "guest_drafts");

            migrationBuilder.DropTable(
                name: "guest_draft_veto_overrides",
                schema: "guest_drafts");

            migrationBuilder.DropTable(
                name: "guest_drafter_team_members",
                schema: "guest_drafts");

            migrationBuilder.DropTable(
                name: "guest_draft_game_boards",
                schema: "guest_drafts");

            migrationBuilder.DropTable(
                name: "guest_draft_vetoes",
                schema: "guest_drafts");

            migrationBuilder.DropTable(
                name: "guest_drafter_teams",
                schema: "guest_drafts");

            migrationBuilder.DropTable(
                name: "guest_drafters",
                schema: "guest_drafts");

            migrationBuilder.DropTable(
                name: "guest_draft_picks",
                schema: "guest_drafts");

            migrationBuilder.DropTable(
                name: "guest_draft_participants",
                schema: "guest_drafts");

            migrationBuilder.DropTable(
                name: "guest_drafts",
                schema: "guest_drafts");

            migrationBuilder.CreateTable(
                name: "drafter_teams",
                schema: "guest_drafts",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    name = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    public_id = table.Column<string>(type: "character varying(19)", maxLength: 19, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_drafter_teams", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "drafters",
                schema: "guest_drafts",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    public_id = table.Column<string>(type: "character varying(19)", maxLength: 19, nullable: false),
                    user_id = table.Column<Guid>(type: "uuid", nullable: false),
                    first_name = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    last_name = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_drafters", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "drafts",
                schema: "guest_drafts",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    public_id = table.Column<string>(type: "character varying(19)", maxLength: 19, nullable: false),
                    owner_user_id = table.Column<Guid>(type: "uuid", nullable: false),
                    title = table.Column<string>(type: "character varying(150)", maxLength: 150, nullable: false),
                    guest_draft_type = table.Column<int>(type: "integer", nullable: false),
                    guest_draft_status = table.Column<int>(type: "integer", nullable: false),
                    share_token = table.Column<string>(type: "character varying(19)", maxLength: 19, nullable: true),
                    created_on_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    updated_on_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                    draft_date = table.Column<DateOnly>(type: "date", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_drafts", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "drafter_team_members",
                schema: "guest_drafts",
                columns: table => new
                {
                    drafter_team_id = table.Column<Guid>(type: "uuid", nullable: false),
                    drafters_id = table.Column<Guid>(type: "uuid", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_drafter_team_members", x => new { x.drafter_team_id, x.drafters_id });
                    table.ForeignKey(
                        name: "fk_drafter_team_members_drafter_teams_drafter_team_id",
                        column: x => x.drafter_team_id,
                        principalSchema: "guest_drafts",
                        principalTable: "drafter_teams",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "fk_drafter_team_members_drafters_drafters_id",
                        column: x => x.drafters_id,
                        principalSchema: "guest_drafts",
                        principalTable: "drafters",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "draft_participants",
                schema: "guest_drafts",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    draft_id = table.Column<Guid>(type: "uuid", nullable: false),
                    participant_id_value = table.Column<Guid>(type: "uuid", nullable: false),
                    participant_kind_value = table.Column<int>(type: "integer", nullable: false),
                    is_owner = table.Column<bool>(type: "boolean", nullable: false),
                    joined_on_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    starting_vetoes = table.Column<int>(type: "integer", nullable: false, defaultValue: 1),
                    awarded_vetoes = table.Column<int>(type: "integer", nullable: false, defaultValue: 0),
                    awarded_veto_overrides = table.Column<int>(type: "integer", nullable: false, defaultValue: 0),
                    commissioner_overrides = table.Column<int>(type: "integer", nullable: false, defaultValue: 0),
                    fungible_tokens = table.Column<int>(type: "integer", nullable: false, defaultValue: 0),
                    awarded_fungible_tokens = table.Column<int>(type: "integer", nullable: false, defaultValue: 0),
                    vetoes_used = table.Column<int>(type: "integer", nullable: false, defaultValue: 0),
                    veto_overrides_used = table.Column<int>(type: "integer", nullable: false, defaultValue: 0),
                    fungible_tokens_used = table.Column<int>(type: "integer", nullable: false, defaultValue: 0)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_draft_participants", x => x.id);
                    table.ForeignKey(
                        name: "fk_draft_participants_drafts_draft_id",
                        column: x => x.draft_id,
                        principalSchema: "guest_drafts",
                        principalTable: "drafts",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "game_boards",
                schema: "guest_drafts",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    draft_id = table.Column<Guid>(type: "uuid", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_game_boards", x => x.id);
                    table.ForeignKey(
                        name: "fk_game_boards_drafts_draft_id",
                        column: x => x.draft_id,
                        principalSchema: "guest_drafts",
                        principalTable: "drafts",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "picks",
                schema: "guest_drafts",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    guest_draft_id = table.Column<Guid>(type: "uuid", nullable: false),
                    position = table.Column<int>(type: "integer", nullable: false),
                    play_order = table.Column<int>(type: "integer", nullable: false),
                    movie_public_id = table.Column<string>(type: "character varying(19)", maxLength: 19, nullable: false),
                    movie_id = table.Column<Guid>(type: "uuid", nullable: false),
                    played_by_participant_id = table.Column<Guid>(type: "uuid", nullable: false),
                    reveal_authorized_participant_id = table.Column<Guid>(type: "uuid", nullable: true),
                    acted_by_public_id = table.Column<string>(type: "character varying(19)", maxLength: 19, nullable: true),
                    revealed_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_picks", x => x.id);
                    table.ForeignKey(
                        name: "fk_picks_draft_participants_played_by_participant_id",
                        column: x => x.played_by_participant_id,
                        principalSchema: "guest_drafts",
                        principalTable: "draft_participants",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_picks_draft_participants_reveal_authorized_participant_id",
                        column: x => x.reveal_authorized_participant_id,
                        principalSchema: "guest_drafts",
                        principalTable: "draft_participants",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_picks_drafts_guest_draft_id",
                        column: x => x.guest_draft_id,
                        principalSchema: "guest_drafts",
                        principalTable: "drafts",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "fk_picks_movies_movie_id",
                        column: x => x.movie_id,
                        principalSchema: "guest_drafts",
                        principalTable: "movies",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "draft_positions",
                schema: "guest_drafts",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    game_board_id = table.Column<Guid>(type: "uuid", nullable: false),
                    public_id = table.Column<string>(type: "character varying(19)", maxLength: 19, nullable: false),
                    name = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: false),
                    picks = table.Column<int[]>(type: "integer[]", nullable: false),
                    has_bonus_veto = table.Column<bool>(type: "boolean", nullable: false),
                    has_bonus_veto_override = table.Column<bool>(type: "boolean", nullable: false),
                    has_bonus_fungible_token = table.Column<bool>(type: "boolean", nullable: false),
                    assigned_to_participant_id = table.Column<Guid>(type: "uuid", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_draft_positions", x => x.id);
                    table.ForeignKey(
                        name: "fk_draft_positions_game_boards_game_board_id",
                        column: x => x.game_board_id,
                        principalSchema: "guest_drafts",
                        principalTable: "game_boards",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "commissioner_overrides",
                schema: "guest_drafts",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    pick_id = table.Column<Guid>(type: "uuid", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_commissioner_overrides", x => x.id);
                    table.ForeignKey(
                        name: "fk_commissioner_overrides_picks_pick_id",
                        column: x => x.pick_id,
                        principalSchema: "guest_drafts",
                        principalTable: "picks",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "pick_history",
                schema: "guest_drafts",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    kind = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: false),
                    issuer_participant_id = table.Column<Guid>(type: "uuid", nullable: true),
                    note = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: true),
                    occurred_on_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    pick_id = table.Column<Guid>(type: "uuid", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_pick_history", x => x.id);
                    table.ForeignKey(
                        name: "fk_pick_history_picks_pick_id",
                        column: x => x.pick_id,
                        principalSchema: "guest_drafts",
                        principalTable: "picks",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "vetoes",
                schema: "guest_drafts",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    target_pick_id = table.Column<Guid>(type: "uuid", nullable: false),
                    sequence = table.Column<int>(type: "integer", nullable: false),
                    issued_by_participant_id = table.Column<Guid>(type: "uuid", nullable: false),
                    acted_by_public_id = table.Column<string>(type: "character varying(19)", maxLength: 19, nullable: true),
                    spent_from_fungible_pool = table.Column<bool>(type: "boolean", nullable: false),
                    is_overridden = table.Column<bool>(type: "boolean", nullable: false),
                    occurred_on = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    note = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_vetoes", x => x.id);
                    table.ForeignKey(
                        name: "fk_vetoes_draft_participants_issued_by_participant_id",
                        column: x => x.issued_by_participant_id,
                        principalSchema: "guest_drafts",
                        principalTable: "draft_participants",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_vetoes_picks_target_pick_id",
                        column: x => x.target_pick_id,
                        principalSchema: "guest_drafts",
                        principalTable: "picks",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "veto_overrides",
                schema: "guest_drafts",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    veto_id = table.Column<Guid>(type: "uuid", nullable: false),
                    issued_by_participant_id = table.Column<Guid>(type: "uuid", nullable: false),
                    acted_by_public_id = table.Column<string>(type: "character varying(19)", maxLength: 19, nullable: true),
                    spent_from_fungible_pool = table.Column<bool>(type: "boolean", nullable: false),
                    note = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_veto_overrides", x => x.id);
                    table.ForeignKey(
                        name: "fk_veto_overrides_draft_participants_issued_by_participant_id",
                        column: x => x.issued_by_participant_id,
                        principalSchema: "guest_drafts",
                        principalTable: "draft_participants",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_veto_overrides_vetoes_veto_id",
                        column: x => x.veto_id,
                        principalSchema: "guest_drafts",
                        principalTable: "vetoes",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "ix_commissioner_overrides_pick_id",
                schema: "guest_drafts",
                table: "commissioner_overrides",
                column: "pick_id",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_draft_participants_draft_id_participant_id_value_participan",
                schema: "guest_drafts",
                table: "draft_participants",
                columns: new[] { "draft_id", "participant_id_value", "participant_kind_value" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_draft_positions_game_board_id",
                schema: "guest_drafts",
                table: "draft_positions",
                column: "game_board_id");

            migrationBuilder.CreateIndex(
                name: "ix_draft_positions_public_id",
                schema: "guest_drafts",
                table: "draft_positions",
                column: "public_id",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_drafter_team_members_drafters_id",
                schema: "guest_drafts",
                table: "drafter_team_members",
                column: "drafters_id");

            migrationBuilder.CreateIndex(
                name: "ix_drafter_teams_public_id",
                schema: "guest_drafts",
                table: "drafter_teams",
                column: "public_id",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_drafters_public_id",
                schema: "guest_drafts",
                table: "drafters",
                column: "public_id",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_drafters_user_id",
                schema: "guest_drafts",
                table: "drafters",
                column: "user_id",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_drafts_public_id",
                schema: "guest_drafts",
                table: "drafts",
                column: "public_id",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_drafts_share_token",
                schema: "guest_drafts",
                table: "drafts",
                column: "share_token",
                unique: true,
                filter: "share_token IS NOT NULL");

            migrationBuilder.CreateIndex(
                name: "ix_game_boards_draft_id",
                schema: "guest_drafts",
                table: "game_boards",
                column: "draft_id",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_pick_history_pick_id",
                schema: "guest_drafts",
                table: "pick_history",
                column: "pick_id");

            migrationBuilder.CreateIndex(
                name: "ix_picks_guest_draft_id_play_order",
                schema: "guest_drafts",
                table: "picks",
                columns: new[] { "guest_draft_id", "play_order" });

            migrationBuilder.CreateIndex(
                name: "ix_picks_movie_id",
                schema: "guest_drafts",
                table: "picks",
                column: "movie_id");

            migrationBuilder.CreateIndex(
                name: "ix_picks_played_by_participant_id",
                schema: "guest_drafts",
                table: "picks",
                column: "played_by_participant_id");

            migrationBuilder.CreateIndex(
                name: "ix_picks_reveal_authorized_participant_id",
                schema: "guest_drafts",
                table: "picks",
                column: "reveal_authorized_participant_id");

            migrationBuilder.CreateIndex(
                name: "ix_veto_overrides_issued_by_participant_id",
                schema: "guest_drafts",
                table: "veto_overrides",
                column: "issued_by_participant_id");

            migrationBuilder.CreateIndex(
                name: "ix_veto_overrides_veto_id",
                schema: "guest_drafts",
                table: "veto_overrides",
                column: "veto_id",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_vetoes_issued_by_participant_id",
                schema: "guest_drafts",
                table: "vetoes",
                column: "issued_by_participant_id");

            migrationBuilder.CreateIndex(
                name: "ix_vetoes_target_pick_id_sequence",
                schema: "guest_drafts",
                table: "vetoes",
                columns: new[] { "target_pick_id", "sequence" },
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "commissioner_overrides",
                schema: "guest_drafts");

            migrationBuilder.DropTable(
                name: "draft_positions",
                schema: "guest_drafts");

            migrationBuilder.DropTable(
                name: "drafter_team_members",
                schema: "guest_drafts");

            migrationBuilder.DropTable(
                name: "pick_history",
                schema: "guest_drafts");

            migrationBuilder.DropTable(
                name: "veto_overrides",
                schema: "guest_drafts");

            migrationBuilder.DropTable(
                name: "game_boards",
                schema: "guest_drafts");

            migrationBuilder.DropTable(
                name: "drafter_teams",
                schema: "guest_drafts");

            migrationBuilder.DropTable(
                name: "drafters",
                schema: "guest_drafts");

            migrationBuilder.DropTable(
                name: "vetoes",
                schema: "guest_drafts");

            migrationBuilder.DropTable(
                name: "picks",
                schema: "guest_drafts");

            migrationBuilder.DropTable(
                name: "draft_participants",
                schema: "guest_drafts");

            migrationBuilder.DropTable(
                name: "drafts",
                schema: "guest_drafts");

            migrationBuilder.CreateTable(
                name: "guest_drafter_teams",
                schema: "guest_drafts",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    name = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    public_id = table.Column<string>(type: "character varying(19)", maxLength: 19, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_guest_drafter_teams", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "guest_drafters",
                schema: "guest_drafts",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    first_name = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    last_name = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    public_id = table.Column<string>(type: "character varying(19)", maxLength: 19, nullable: false),
                    user_id = table.Column<Guid>(type: "uuid", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_guest_drafters", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "guest_drafts",
                schema: "guest_drafts",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    created_on_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    draft_date = table.Column<DateOnly>(type: "date", nullable: true),
                    guest_draft_status = table.Column<int>(type: "integer", nullable: false),
                    guest_draft_type = table.Column<int>(type: "integer", nullable: false),
                    owner_user_id = table.Column<Guid>(type: "uuid", nullable: false),
                    public_id = table.Column<string>(type: "character varying(19)", maxLength: 19, nullable: false),
                    share_token = table.Column<string>(type: "character varying(19)", maxLength: 19, nullable: true),
                    title = table.Column<string>(type: "character varying(150)", maxLength: 150, nullable: false),
                    updated_on_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_guest_drafts", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "guest_drafter_team_members",
                schema: "guest_drafts",
                columns: table => new
                {
                    drafters_id = table.Column<Guid>(type: "uuid", nullable: false),
                    guest_drafter_team_id = table.Column<Guid>(type: "uuid", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_guest_drafter_team_members", x => new { x.drafters_id, x.guest_drafter_team_id });
                    table.ForeignKey(
                        name: "fk_guest_drafter_team_members_guest_drafter_teams_guest_drafte",
                        column: x => x.guest_drafter_team_id,
                        principalSchema: "guest_drafts",
                        principalTable: "guest_drafter_teams",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "fk_guest_drafter_team_members_guest_drafters_drafters_id",
                        column: x => x.drafters_id,
                        principalSchema: "guest_drafts",
                        principalTable: "guest_drafters",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "guest_draft_game_boards",
                schema: "guest_drafts",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    guest_draft_id = table.Column<Guid>(type: "uuid", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_guest_draft_game_boards", x => x.id);
                    table.ForeignKey(
                        name: "fk_guest_draft_game_boards_guest_drafts_guest_draft_id",
                        column: x => x.guest_draft_id,
                        principalSchema: "guest_drafts",
                        principalTable: "guest_drafts",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "guest_draft_participants",
                schema: "guest_drafts",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    guest_draft_id = table.Column<Guid>(type: "uuid", nullable: false),
                    awarded_fungible_tokens = table.Column<int>(type: "integer", nullable: false, defaultValue: 0),
                    awarded_veto_overrides = table.Column<int>(type: "integer", nullable: false, defaultValue: 0),
                    awarded_vetoes = table.Column<int>(type: "integer", nullable: false, defaultValue: 0),
                    commissioner_overrides = table.Column<int>(type: "integer", nullable: false, defaultValue: 0),
                    fungible_tokens = table.Column<int>(type: "integer", nullable: false, defaultValue: 0),
                    fungible_tokens_used = table.Column<int>(type: "integer", nullable: false, defaultValue: 0),
                    is_owner = table.Column<bool>(type: "boolean", nullable: false),
                    joined_on_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    participant_id_value = table.Column<Guid>(type: "uuid", nullable: false),
                    participant_kind_value = table.Column<int>(type: "integer", nullable: false),
                    starting_vetoes = table.Column<int>(type: "integer", nullable: false, defaultValue: 1),
                    veto_overrides_used = table.Column<int>(type: "integer", nullable: false, defaultValue: 0),
                    vetoes_used = table.Column<int>(type: "integer", nullable: false, defaultValue: 0)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_guest_draft_participants", x => x.id);
                    table.ForeignKey(
                        name: "fk_guest_draft_participants_guest_drafts_guest_draft_id",
                        column: x => x.guest_draft_id,
                        principalSchema: "guest_drafts",
                        principalTable: "guest_drafts",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "guest_draft_positions",
                schema: "guest_drafts",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    assigned_to_participant_id = table.Column<Guid>(type: "uuid", nullable: true),
                    game_board_id = table.Column<Guid>(type: "uuid", nullable: false),
                    has_bonus_fungible_token = table.Column<bool>(type: "boolean", nullable: false),
                    has_bonus_veto = table.Column<bool>(type: "boolean", nullable: false),
                    has_bonus_veto_override = table.Column<bool>(type: "boolean", nullable: false),
                    name = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: false),
                    picks = table.Column<int[]>(type: "integer[]", nullable: false),
                    public_id = table.Column<string>(type: "character varying(19)", maxLength: 19, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_guest_draft_positions", x => x.id);
                    table.ForeignKey(
                        name: "fk_guest_draft_positions_guest_draft_game_boards_game_board_id",
                        column: x => x.game_board_id,
                        principalSchema: "guest_drafts",
                        principalTable: "guest_draft_game_boards",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "guest_draft_picks",
                schema: "guest_drafts",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    played_by_participant_id = table.Column<Guid>(type: "uuid", nullable: false),
                    reveal_authorized_participant_id = table.Column<Guid>(type: "uuid", nullable: true),
                    acted_by_public_id = table.Column<string>(type: "character varying(19)", maxLength: 19, nullable: true),
                    guest_draft_id = table.Column<Guid>(type: "uuid", nullable: false),
                    movie_id = table.Column<Guid>(type: "uuid", nullable: false),
                    movie_public_id = table.Column<string>(type: "character varying(19)", maxLength: 19, nullable: false),
                    play_order = table.Column<int>(type: "integer", nullable: false),
                    position = table.Column<int>(type: "integer", nullable: false),
                    revealed_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_guest_draft_picks", x => x.id);
                    table.ForeignKey(
                        name: "fk_guest_draft_picks_guest_draft_participants_played_by_partic",
                        column: x => x.played_by_participant_id,
                        principalSchema: "guest_drafts",
                        principalTable: "guest_draft_participants",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_guest_draft_picks_guest_draft_participants_reveal_authorize",
                        column: x => x.reveal_authorized_participant_id,
                        principalSchema: "guest_drafts",
                        principalTable: "guest_draft_participants",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_guest_draft_picks_guest_drafts_guest_draft_id",
                        column: x => x.guest_draft_id,
                        principalSchema: "guest_drafts",
                        principalTable: "guest_drafts",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "fk_guest_draft_picks_movies_movie_id",
                        column: x => x.movie_id,
                        principalSchema: "guest_drafts",
                        principalTable: "movies",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "guest_draft_commissioner_overrides",
                schema: "guest_drafts",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    pick_id = table.Column<Guid>(type: "uuid", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_guest_draft_commissioner_overrides", x => x.id);
                    table.ForeignKey(
                        name: "fk_guest_draft_commissioner_overrides_guest_draft_picks_pick_id",
                        column: x => x.pick_id,
                        principalSchema: "guest_drafts",
                        principalTable: "guest_draft_picks",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "guest_draft_pick_history",
                schema: "guest_drafts",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    guest_draft_pick_id = table.Column<Guid>(type: "uuid", nullable: false),
                    issuer_participant_id = table.Column<Guid>(type: "uuid", nullable: true),
                    kind = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: false),
                    note = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: true),
                    occurred_on_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_guest_draft_pick_history", x => x.id);
                    table.ForeignKey(
                        name: "fk_guest_draft_pick_history_guest_draft_picks_guest_draft_pick",
                        column: x => x.guest_draft_pick_id,
                        principalSchema: "guest_drafts",
                        principalTable: "guest_draft_picks",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "guest_draft_vetoes",
                schema: "guest_drafts",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    issued_by_participant_id = table.Column<Guid>(type: "uuid", nullable: false),
                    target_pick_id = table.Column<Guid>(type: "uuid", nullable: false),
                    acted_by_public_id = table.Column<string>(type: "character varying(19)", maxLength: 19, nullable: true),
                    is_overridden = table.Column<bool>(type: "boolean", nullable: false),
                    note = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: true),
                    occurred_on = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    sequence = table.Column<int>(type: "integer", nullable: false),
                    spent_from_fungible_pool = table.Column<bool>(type: "boolean", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_guest_draft_vetoes", x => x.id);
                    table.ForeignKey(
                        name: "fk_guest_draft_vetoes_guest_draft_participants_issued_by_parti",
                        column: x => x.issued_by_participant_id,
                        principalSchema: "guest_drafts",
                        principalTable: "guest_draft_participants",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_guest_draft_vetoes_guest_draft_picks_target_pick_id",
                        column: x => x.target_pick_id,
                        principalSchema: "guest_drafts",
                        principalTable: "guest_draft_picks",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "guest_draft_veto_overrides",
                schema: "guest_drafts",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    issued_by_participant_id = table.Column<Guid>(type: "uuid", nullable: false),
                    veto_id = table.Column<Guid>(type: "uuid", nullable: false),
                    acted_by_public_id = table.Column<string>(type: "character varying(19)", maxLength: 19, nullable: true),
                    note = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: true),
                    spent_from_fungible_pool = table.Column<bool>(type: "boolean", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_guest_draft_veto_overrides", x => x.id);
                    table.ForeignKey(
                        name: "fk_guest_draft_veto_overrides_guest_draft_participants_issued_",
                        column: x => x.issued_by_participant_id,
                        principalSchema: "guest_drafts",
                        principalTable: "guest_draft_participants",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_guest_draft_veto_overrides_guest_draft_vetoes_veto_id",
                        column: x => x.veto_id,
                        principalSchema: "guest_drafts",
                        principalTable: "guest_draft_vetoes",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "ix_guest_draft_commissioner_overrides_pick_id",
                schema: "guest_drafts",
                table: "guest_draft_commissioner_overrides",
                column: "pick_id",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_guest_draft_game_boards_guest_draft_id",
                schema: "guest_drafts",
                table: "guest_draft_game_boards",
                column: "guest_draft_id",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_guest_draft_participants_guest_draft_id_participant_id_valu",
                schema: "guest_drafts",
                table: "guest_draft_participants",
                columns: new[] { "guest_draft_id", "participant_id_value", "participant_kind_value" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_guest_draft_pick_history_guest_draft_pick_id",
                schema: "guest_drafts",
                table: "guest_draft_pick_history",
                column: "guest_draft_pick_id");

            migrationBuilder.CreateIndex(
                name: "ix_guest_draft_picks_guest_draft_id_play_order",
                schema: "guest_drafts",
                table: "guest_draft_picks",
                columns: new[] { "guest_draft_id", "play_order" });

            migrationBuilder.CreateIndex(
                name: "ix_guest_draft_picks_movie_id",
                schema: "guest_drafts",
                table: "guest_draft_picks",
                column: "movie_id");

            migrationBuilder.CreateIndex(
                name: "ix_guest_draft_picks_played_by_participant_id",
                schema: "guest_drafts",
                table: "guest_draft_picks",
                column: "played_by_participant_id");

            migrationBuilder.CreateIndex(
                name: "ix_guest_draft_picks_reveal_authorized_participant_id",
                schema: "guest_drafts",
                table: "guest_draft_picks",
                column: "reveal_authorized_participant_id");

            migrationBuilder.CreateIndex(
                name: "ix_guest_draft_positions_game_board_id",
                schema: "guest_drafts",
                table: "guest_draft_positions",
                column: "game_board_id");

            migrationBuilder.CreateIndex(
                name: "ix_guest_draft_positions_public_id",
                schema: "guest_drafts",
                table: "guest_draft_positions",
                column: "public_id",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_guest_draft_veto_overrides_issued_by_participant_id",
                schema: "guest_drafts",
                table: "guest_draft_veto_overrides",
                column: "issued_by_participant_id");

            migrationBuilder.CreateIndex(
                name: "ix_guest_draft_veto_overrides_veto_id",
                schema: "guest_drafts",
                table: "guest_draft_veto_overrides",
                column: "veto_id",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_guest_draft_vetoes_issued_by_participant_id",
                schema: "guest_drafts",
                table: "guest_draft_vetoes",
                column: "issued_by_participant_id");

            migrationBuilder.CreateIndex(
                name: "ix_guest_draft_vetoes_target_pick_id_sequence",
                schema: "guest_drafts",
                table: "guest_draft_vetoes",
                columns: new[] { "target_pick_id", "sequence" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_guest_drafter_team_members_guest_drafter_team_id",
                schema: "guest_drafts",
                table: "guest_drafter_team_members",
                column: "guest_drafter_team_id");

            migrationBuilder.CreateIndex(
                name: "ix_guest_drafter_teams_public_id",
                schema: "guest_drafts",
                table: "guest_drafter_teams",
                column: "public_id",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_guest_drafters_public_id",
                schema: "guest_drafts",
                table: "guest_drafters",
                column: "public_id",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_guest_drafters_user_id",
                schema: "guest_drafts",
                table: "guest_drafters",
                column: "user_id",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_guest_drafts_public_id",
                schema: "guest_drafts",
                table: "guest_drafts",
                column: "public_id",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_guest_drafts_share_token",
                schema: "guest_drafts",
                table: "guest_drafts",
                column: "share_token",
                unique: true,
                filter: "share_token IS NOT NULL");
        }
    }
}

