// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ScreenDrafts.Modules.GuestDrafts.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class Update_to_Scheduled_For_Utc : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "draft_date",
                schema: "guest_drafts",
                table: "drafts");

            migrationBuilder.AddColumn<DateTime>(
                name: "scheduled_for_utc",
                schema: "guest_drafts",
                table: "drafts",
                type: "timestamp with time zone",
                nullable: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "scheduled_for_utc",
                schema: "guest_drafts",
                table: "drafts");

            migrationBuilder.AddColumn<DateOnly>(
                name: "draft_date",
                schema: "guest_drafts",
                table: "drafts",
                type: "date",
                nullable: true);
        }
    }
}

