// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ScreenDrafts.Modules.GuestDrafts.Infrastructure.Database;

#nullable disable

namespace ScreenDrafts.Modules.GuestDrafts.Infrastructure.Database.Migrations
{
    [DbContext(typeof(GuestDraftsDbContext))]
    [Migration("20260906145553_Update_GuestDrafters")]
    partial class Update_GuestDrafters
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("guest_drafts")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GuestDrafterGuestDrafterTeam", b =>
                {
                    b.Property<Guid>("DraftersId")
                        .HasColumnType("uuid")
                        .HasColumnName("drafters_id");

                    b.Property<Guid>("GuestDrafterTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("guest_drafter_team_id");

                    b.HasKey("DraftersId", "GuestDrafterTeamId")
                        .HasName("pk_guest_drafter_team_members");

                    b.HasIndex("GuestDrafterTeamId")
                        .HasDatabaseName("ix_guest_drafter_team_members_guest_drafter_team_id");

                    b.ToTable("guest_drafter_team_members", "guest_drafts");
                });

            modelBuilder.Entity("ScreenDrafts.Common.Infrastructure.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_inbox_messages");

                    b.ToTable("inbox_messages", "guest_drafts");
                });

            modelBuilder.Entity("ScreenDrafts.Common.Infrastructure.Inbox.InboxMessageConsumer", b =>
                {
                    b.Property<Guid>("InboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("inbox_message_id");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("InboxMessageId", "Name")
                        .HasName("pk_inbox_message_consumers");

                    b.ToTable("inbox_message_consumers", "guest_drafts");
                });

            modelBuilder.Entity("ScreenDrafts.Common.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.ToTable("outbox_messages", "guest_drafts");
                });

            modelBuilder.Entity("ScreenDrafts.Common.Infrastructure.Outbox.OutboxMessageConsumer", b =>
                {
                    b.Property<Guid>("OutboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_message_id");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("OutboxMessageId", "Name")
                        .HasName("pk_outbox_message_consumers");

                    b.ToTable("outbox_message_consumers", "guest_drafts");
                });

            modelBuilder.Entity("ScreenDrafts.Modules.GuestDrafts.Domain.GuestDrafterTeams.GuestDrafterTeam", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(19)
                        .HasColumnType("character varying(19)")
                        .HasColumnName("public_id");

                    b.HasKey("Id")
                        .HasName("pk_guest_drafter_teams");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_guest_drafter_teams_public_id");

                    b.ToTable("guest_drafter_teams", "guest_drafts");
                });

            modelBuilder.Entity("ScreenDrafts.Modules.GuestDrafts.Domain.GuestDrafters.GuestDrafter", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(19)
                        .HasColumnType("character varying(19)")
                        .HasColumnName("public_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_guest_drafters");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_guest_drafters_public_id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_guest_drafters_user_id");

                    b.ToTable("guest_drafters", "guest_drafts");
                });

            modelBuilder.Entity("ScreenDrafts.Modules.GuestDrafts.Domain.GuestDrafts.Entities.GuestDraftCommissionerOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("PickId")
                        .HasColumnType("uuid")
                        .HasColumnName("pick_id");

                    b.HasKey("Id")
                        .HasName("pk_guest_draft_commissioner_overrides");

                    b.HasIndex("PickId")
                        .IsUnique()
                        .HasDatabaseName("ix_guest_draft_commissioner_overrides_pick_id");

                    b.ToTable("guest_draft_commissioner_overrides", "guest_drafts");
                });

            modelBuilder.Entity("ScreenDrafts.Modules.GuestDrafts.Domain.GuestDrafts.Entities.GuestDraftGameBoard", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("GuestDraftId")
                        .HasColumnType("uuid")
                        .HasColumnName("guest_draft_id");

                    b.HasKey("Id")
                        .HasName("pk_guest_draft_game_boards");

                    b.HasIndex("GuestDraftId")
                        .IsUnique()
                        .HasDatabaseName("ix_guest_draft_game_boards_guest_draft_id");

                    b.ToTable("guest_draft_game_boards", "guest_drafts");
                });

            modelBuilder.Entity("ScreenDrafts.Modules.GuestDrafts.Domain.GuestDrafts.Entities.GuestDraftPick", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActedByPublicId")
                        .HasMaxLength(19)
                        .HasColumnType("character varying(19)")
                        .HasColumnName("acted_by_public_id");

                    b.Property<Guid>("GuestDraftId")
                        .HasColumnType("uuid")
                        .HasColumnName("guest_draft_id");

                    b.Property<string>("MoviePublicId")
                        .IsRequired()
                        .HasMaxLength(19)
                        .HasColumnType("character varying(19)")
                        .HasColumnName("movie_public_id");

                    b.Property<int>("PlayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("play_order");

                    b.Property<Guid>("PlayedByParticipantId")
                        .HasColumnType("uuid")
                        .HasColumnName("played_by_participant_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid?>("RevealAuthorizedParticipantId")
                        .HasColumnType("uuid")
                        .HasColumnName("reveal_authorized_participant_id");

                    b.Property<DateTimeOffset?>("RevealedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revealed_at");

                    b.HasKey("Id")
                        .HasName("pk_guest_draft_picks");

                    b.HasIndex("PlayedByParticipantId")
                        .HasDatabaseName("ix_guest_draft_picks_played_by_participant_id");

                    b.HasIndex("RevealAuthorizedParticipantId")
                        .HasDatabaseName("ix_guest_draft_picks_reveal_authorized_participant_id");

                    b.HasIndex("GuestDraftId", "PlayOrder")
                        .HasDatabaseName("ix_guest_draft_picks_guest_draft_id_play_order");

                    b.ToTable("guest_draft_picks", "guest_drafts");
                });

            modelBuilder.Entity("ScreenDrafts.Modules.GuestDrafts.Domain.GuestDrafts.Entities.GuestDraftPosition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssignedToParticipantId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_to_participant_id");

                    b.Property<Guid>("GameBoardId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_board_id");

                    b.Property<bool>("HasBonusFungibleToken")
                        .HasColumnType("boolean")
                        .HasColumnName("has_bonus_fungible_token");

                    b.Property<bool>("HasBonusVeto")
                        .HasColumnType("boolean")
                        .HasColumnName("has_bonus_veto");

                    b.Property<bool>("HasBonusVetoOverride")
                        .HasColumnType("boolean")
                        .HasColumnName("has_bonus_veto_override");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.PrimitiveCollection<int[]>("Picks")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("picks");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(19)
                        .HasColumnType("character varying(19)")
                        .HasColumnName("public_id");

                    b.HasKey("Id")
                        .HasName("pk_guest_draft_positions");

                    b.HasIndex("GameBoardId")
                        .HasDatabaseName("ix_guest_draft_positions_game_board_id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_guest_draft_positions_public_id");

                    b.ToTable("guest_draft_positions", "guest_drafts");
                });

            modelBuilder.Entity("ScreenDrafts.Modules.GuestDrafts.Domain.GuestDrafts.Entities.GuestDraftVeto", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActedByPublicId")
                        .HasMaxLength(19)
                        .HasColumnType("character varying(19)")
                        .HasColumnName("acted_by_public_id");

                    b.Property<bool>("IsOverridden")
                        .HasColumnType("boolean")
                        .HasColumnName("is_overridden");

                    b.Property<Guid>("IssuedByParticipantId")
                        .HasColumnType("uuid")
                        .HasColumnName("issued_by_participant_id");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<DateTime>("OccurredOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<bool>("SpentFromFungiblePool")
                        .HasColumnType("boolean")
                        .HasColumnName("spent_from_fungible_pool");

                    b.Property<Guid>("TargetPickId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_pick_id");

                    b.HasKey("Id")
                        .HasName("pk_guest_draft_vetoes");

                    b.HasIndex("IssuedByParticipantId")
                        .HasDatabaseName("ix_guest_draft_vetoes_issued_by_participant_id");

                    b.HasIndex("TargetPickId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ix_guest_draft_vetoes_target_pick_id_sequence");

                    b.ToTable("guest_draft_vetoes", "guest_drafts");
                });

            modelBuilder.Entity("ScreenDrafts.Modules.GuestDrafts.Domain.GuestDrafts.Entities.GuestDraftVetoOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActedByPublicId")
                        .HasMaxLength(19)
                        .HasColumnType("character varying(19)")
                        .HasColumnName("acted_by_public_id");

                    b.Property<Guid>("IssuedByParticipantId")
                        .HasColumnType("uuid")
                        .HasColumnName("issued_by_participant_id");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<bool>("SpentFromFungiblePool")
                        .HasColumnType("boolean")
                        .HasColumnName("spent_from_fungible_pool");

                    b.Property<Guid>("VetoId")
                        .HasColumnType("uuid")
                        .HasColumnName("veto_id");

                    b.HasKey("Id")
                        .HasName("pk_guest_draft_veto_overrides");

                    b.HasIndex("IssuedByParticipantId")
                        .HasDatabaseName("ix_guest_draft_veto_overrides_issued_by_participant_id");

                    b.HasIndex("VetoId")
                        .IsUnique()
                        .HasDatabaseName("ix_guest_draft_veto_overrides_veto_id");

                    b.ToTable("guest_draft_veto_overrides", "guest_drafts");
                });

            modelBuilder.Entity("ScreenDrafts.Modules.GuestDrafts.Domain.GuestDrafts.GuestDraft", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<DateOnly?>("DraftDate")
                        .HasColumnType("date")
                        .HasColumnName("draft_date");

                    b.Property<int>("GuestDraftStatus")
                        .HasColumnType("integer")
                        .HasColumnName("guest_draft_status");

                    b.Property<int>("GuestDraftType")
                        .HasColumnType("integer")
                        .HasColumnName("guest_draft_type");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(19)
                        .HasColumnType("character varying(19)")
                        .HasColumnName("public_id");

                    b.Property<string>("ShareToken")
                        .HasMaxLength(19)
                        .HasColumnType("character varying(19)")
                        .HasColumnName("share_token");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on_utc");

                    b.HasKey("Id")
                        .HasName("pk_guest_drafts");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_guest_drafts_public_id");

                    b.HasIndex("ShareToken")
                        .IsUnique()
                        .HasDatabaseName("ix_guest_drafts_share_token")
                        .HasFilter("share_token IS NOT NULL");

                    b.ToTable("guest_drafts", "guest_drafts");
                });

            modelBuilder.Entity("ScreenDrafts.Modules.GuestDrafts.Domain.GuestDrafts.GuestDraftParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AwardedFungibleTokens")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("awarded_fungible_tokens");

                    b.Property<int>("AwardedVetoOverrides")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("awarded_veto_overrides");

                    b.Property<int>("AwardedVetoes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("awarded_vetoes");

                    b.Property<int>("CommissionerOverrides")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("commissioner_overrides");

                    b.Property<int>("FungibleTokens")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("fungible_tokens");

                    b.Property<int>("FungibleTokensUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("fungible_tokens_used");

                    b.Property<Guid>("GuestDraftId")
                        .HasColumnType("uuid")
                        .HasColumnName("guest_draft_id");

                    b.Property<bool>("IsOwner")
                        .HasColumnType("boolean")
                        .HasColumnName("is_owner");

                    b.Property<DateTime>("JoinedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_on_utc");

                    b.Property<Guid>("ParticipantIdValue")
                        .HasColumnType("uuid")
                        .HasColumnName("participant_id_value");

                    b.Property<int>("ParticipantKindValue")
                        .HasColumnType("integer")
                        .HasColumnName("participant_kind_value");

                    b.Property<int>("StartingVetoes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("starting_vetoes");

                    b.Property<int>("VetoOverridesUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("veto_overrides_used");

                    b.Property<int>("VetoesUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("vetoes_used");

                    b.HasKey("Id")
                        .HasName("pk_guest_draft_participants");

                    b.HasIndex("GuestDraftId", "ParticipantIdValue", "ParticipantKindValue")
                        .IsUnique()
                        .HasDatabaseName("ix_guest_draft_participants_guest_draft_id_participant_id_valu");

                    b.ToTable("guest_draft_participants", "guest_drafts");
                });

            modelBuilder.Entity("GuestDrafterGuestDrafterTeam", b =>
                {
                    b.HasOne("ScreenDrafts.Modules.GuestDrafts.Domain.GuestDrafters.GuestDrafter", null)
                        .WithMany()
                        .HasForeignKey("DraftersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_guest_drafter_team_members_guest_drafters_drafters_id");

                    b.HasOne("ScreenDrafts.Modules.GuestDrafts.Domain.GuestDrafterTeams.GuestDrafterTeam", null)
                        .WithMany()
                        .HasForeignKey("GuestDrafterTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_guest_drafter_team_members_guest_drafter_teams_guest_drafte");
                });

            modelBuilder.Entity("ScreenDrafts.Modules.GuestDrafts.Domain.GuestDrafts.Entities.GuestDraftCommissionerOverride", b =>
                {
                    b.HasOne("ScreenDrafts.Modules.GuestDrafts.Domain.GuestDrafts.Entities.GuestDraftPick", "Pick")
                        .WithOne("CommissionerOverride")
                        .HasForeignKey("ScreenDrafts.Modules.GuestDrafts.Domain.GuestDrafts.Entities.GuestDraftCommissionerOverride", "PickId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_guest_draft_commissioner_overrides_guest_draft_picks_pick_id");

                    b.Navigation("Pick");
                });

            modelBuilder.Entity("ScreenDrafts.Modules.GuestDrafts.Domain.GuestDrafts.Entities.GuestDraftGameBoard", b =>
                {
                    b.HasOne("ScreenDrafts.Modules.GuestDrafts.Domain.GuestDrafts.GuestDraft", null)
                        .WithOne("GameBoard")
                        .HasForeignKey("ScreenDrafts.Modules.GuestDrafts.Domain.GuestDrafts.Entities.GuestDraftGameBoard", "GuestDraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_guest_draft_game_boards_guest_drafts_guest_draft_id");
                });

            modelBuilder.Entity("ScreenDrafts.Modules.GuestDrafts.Domain.GuestDrafts.Entities.GuestDraftPick", b =>
                {
                    b.HasOne("ScreenDrafts.Modules.GuestDrafts.Domain.GuestDrafts.GuestDraft", null)
                        .WithMany("Picks")
                        .HasForeignKey("GuestDraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_guest_draft_picks_guest_drafts_guest_draft_id");

                    b.HasOne("ScreenDrafts.Modules.GuestDrafts.Domain.GuestDrafts.GuestDraftParticipant", "PlayedByParticipant")
                        .WithMany()
                        .HasForeignKey("PlayedByParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_guest_draft_picks_guest_draft_participants_played_by_partic");

                    b.HasOne("ScreenDrafts.Modules.GuestDrafts.Domain.GuestDrafts.GuestDraftParticipant", "RevealAuthorizedParticipant")
                        .WithMany()
                        .HasForeignKey("RevealAuthorizedParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_guest_draft_picks_guest_draft_participants_reveal_authorize");

                    b.OwnsMany("ScreenDrafts.Modules.GuestDrafts.Domain.GuestDrafts.Entities.GuestDraftPickEvent", "History", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("GuestDraftPickId")
                                .HasColumnType("uuid")
                                .HasColumnName("guest_draft_pick_id");

                            b1.Property<Guid?>("IssuerParticipantId")
                                .HasColumnType("uuid")
                                .HasColumnName("issuer_participant_id");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("kind");

                            b1.Property<string>("Note")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("note");

                            b1.Property<DateTime>("OccurredOnUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("occurred_on_utc");

                            b1.HasKey("Id")
                                .HasName("pk_guest_draft_pick_history");

                            b1.HasIndex("GuestDraftPickId")
                                .HasDatabaseName("ix_guest_draft_pick_history_guest_draft_pick_id");

                            b1.ToTable("guest_draft_pick_history", "guest_drafts");

                            b1.WithOwner()
                                .HasForeignKey("GuestDraftPickId")
                                .HasConstraintName("fk_guest_draft_pick_history_guest_draft_picks_guest_draft_pick");
                        });

                    b.Navigation("History");

                    b.Navigation("PlayedByParticipant");

                    b.Navigation("RevealAuthorizedParticipant");
                });

            modelBuilder.Entity("ScreenDrafts.Modules.GuestDrafts.Domain.GuestDrafts.Entities.GuestDraftPosition", b =>
                {
                    b.HasOne("ScreenDrafts.Modules.GuestDrafts.Domain.GuestDrafts.Entities.GuestDraftGameBoard", null)
                        .WithMany("Positions")
                        .HasForeignKey("GameBoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_guest_draft_positions_guest_draft_game_boards_game_board_id");
                });

            modelBuilder.Entity("ScreenDrafts.Modules.GuestDrafts.Domain.GuestDrafts.Entities.GuestDraftVeto", b =>
                {
                    b.HasOne("ScreenDrafts.Modules.GuestDrafts.Domain.GuestDrafts.GuestDraftParticipant", "IssuedByParticipant")
                        .WithMany()
                        .HasForeignKey("IssuedByParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_guest_draft_vetoes_guest_draft_participants_issued_by_parti");

                    b.HasOne("ScreenDrafts.Modules.GuestDrafts.Domain.GuestDrafts.Entities.GuestDraftPick", "TargetPick")
                        .WithMany("Vetoes")
                        .HasForeignKey("TargetPickId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_guest_draft_vetoes_guest_draft_picks_target_pick_id");

                    b.Navigation("IssuedByParticipant");

                    b.Navigation("TargetPick");
                });

            modelBuilder.Entity("ScreenDrafts.Modules.GuestDrafts.Domain.GuestDrafts.Entities.GuestDraftVetoOverride", b =>
                {
                    b.HasOne("ScreenDrafts.Modules.GuestDrafts.Domain.GuestDrafts.GuestDraftParticipant", "IssuedByParticipant")
                        .WithMany()
                        .HasForeignKey("IssuedByParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_guest_draft_veto_overrides_guest_draft_participants_issued_");

                    b.HasOne("ScreenDrafts.Modules.GuestDrafts.Domain.GuestDrafts.Entities.GuestDraftVeto", "Veto")
                        .WithOne("VetoOverride")
                        .HasForeignKey("ScreenDrafts.Modules.GuestDrafts.Domain.GuestDrafts.Entities.GuestDraftVetoOverride", "VetoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_guest_draft_veto_overrides_guest_draft_vetoes_veto_id");

                    b.Navigation("IssuedByParticipant");

                    b.Navigation("Veto");
                });

            modelBuilder.Entity("ScreenDrafts.Modules.GuestDrafts.Domain.GuestDrafts.GuestDraftParticipant", b =>
                {
                    b.HasOne("ScreenDrafts.Modules.GuestDrafts.Domain.GuestDrafts.GuestDraft", "GuestDraft")
                        .WithMany("Participants")
                        .HasForeignKey("GuestDraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_guest_draft_participants_guest_drafts_guest_draft_id");

                    b.Navigation("GuestDraft");
                });

            modelBuilder.Entity("ScreenDrafts.Modules.GuestDrafts.Domain.GuestDrafts.Entities.GuestDraftGameBoard", b =>
                {
                    b.Navigation("Positions");
                });

            modelBuilder.Entity("ScreenDrafts.Modules.GuestDrafts.Domain.GuestDrafts.Entities.GuestDraftPick", b =>
                {
                    b.Navigation("CommissionerOverride");

                    b.Navigation("Vetoes");
                });

            modelBuilder.Entity("ScreenDrafts.Modules.GuestDrafts.Domain.GuestDrafts.Entities.GuestDraftVeto", b =>
                {
                    b.Navigation("VetoOverride");
                });

            modelBuilder.Entity("ScreenDrafts.Modules.GuestDrafts.Domain.GuestDrafts.GuestDraft", b =>
                {
                    b.Navigation("GameBoard");

                    b.Navigation("Participants");

                    b.Navigation("Picks");
                });
#pragma warning restore 612, 618
        }
    }
}
