services:
  # Backend API
  screendrafts.web:
    image: ${DOCKER_REGISTRY-}screendraftsweb
    build:
      context: .
      dockerfile: src/api/ScreenDrafts.Web/Dockerfile
    volumes:
      - ./data:/app/data
    environment:
      - DATA_PATH=/app/data
    ports:
      - 5000:8080
      - 5001:8081
    networks:
      - screendrafts
    depends_on:
      - screendrafts.database
      - screendrafts.identity
      - screendrafts.seq
      - screendrafts.redis
      - screendrafts.jaeger
      - screendrafts.queue
      - screendrafts.mongo
      - screendrafts.email
      - screendrafts.elk

  # YARP Gateway
  screendrafts.gateway:
    image: ${DOCKER_REGISTRY-}screendraftsgateway
    build:
      context: .
      dockerfile: src/api/ScreenDrafts.Gateway/Dockerfile
    ports:
     - 3000:8080
     - 3001:8081
    networks:
      - screendrafts

  # Main App DB
  screendrafts.database:
    image: postgres:latest
    environment:
      - POSTGRES_DB=screendrafts
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - screendrafts

  screendrafts.identity:
    image: quay.io/keycloak/keycloak:latest
    command: start-dev --import-realm
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://keycloak-db:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloakpass
      - KC_HEALTH_ENABLED=true
      - KC_LEGACY_OBSERVABILITY_INTERFACE=true
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./.files:/opt/keycloak/data/import
    ports:
      - 18080:8080
    depends_on:
      - keycloak-db
    networks:
      - screendrafts

  keycloak-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloakpass
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:
      - screendrafts

  screendrafts.seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80
    networks:
      - screendrafts

  screendrafts.redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    networks:
      - screendrafts

  screendrafts.jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: ScreenDrafts.Jaeger
    ports:
      - 4317:4317
      - 4318:4318
      - 16686:16686
    networks:
      - screendrafts

  screendrafts.queue:
    image: rabbitmq:management-alpine
    hostname: screendrafts-queue
    volumes:
        - ./.containers/queue/data/:/var/lib/rabbitmq
        - ./.containers/queue/log/:/var/log/rabbitmq
    environment:
        RABBITMQ_DEFAULT_USER: guest
        RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - screendrafts

  screendrafts.mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - ./.containers/mongo:/data/db
    ports:
      - 27017:27017
    networks:
      - screendrafts

  screendrafts.email:
    image: changemakerstudiosus/papercut-smtp:latest
    ports:
      - "8085:80"
      - "25:25"
    networks:
      - screendrafts

  screendrafts.elk:
    image: sebp/elk
    volumes:
      - ./.containers/elk:/usr/share/elk/data
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    networks:
      - screendrafts

volumes:
  keycloak-db-data:

networks:
  screendrafts:
    name: screendrafts
    driver: bridge
