services:
  screendrafts.web:
    image: ${DOCKER_REGISTRY-}screendraftsweb
    container_name: ScreenDrafts.Api
    build:
      context: .
      dockerfile: src/api/ScreenDrafts.Web/Dockerfile
    volumes:
      - ./data:/app/data
    environment:
      - DATA_PATH=/app/data
    
    ports:
      - 5000:8080
      - 5001:8081

  screendrafts.gateway:
    image: ${DOCKER_REGISTRY-}screendraftsgateway
    container_name: ScreenDrafts.Gateway
    build:
      context: .
      dockerfile: src/api/ScreenDrafts.Gateway/Dockerfile
    ports:
     - 3000:8080
     - 3001:8081

  screendrafts.database:
    image: postgres:latest
    container_name: ScreenDrafts.Database
    environment:
      - POSTGRES_DB=screendrafts
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  screendrafts.identity:
    image: quay.io/keycloak/keycloak:latest
    container_name: ScreenDrafts.Identity
    command: start-dev --import-realm
    environment:
      - KC_HEALTH_ENABLED=true
      - KC_LEGACY_OBSERVABILITY_INTERFACE=true
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./.containers/identity:/opt/keycloak/data
      - ./.files:/opt/keycloak/data/import
    ports:
      - 18080:8080


  screendrafts.seq:
    image: datalust/seq:latest
    container_name: ScreenDrafts.Seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80

  screendrafts.redis:
    image: redis:latest
    container_name: ScreenDrafts.Redis
    restart: always
    ports:
      - 6379:6379 

  screendrafts.jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: ScreenDrafts.Jaeger
    ports:
      - 4317:4317
      - 4318:4318
      - 16686:16686

  screendrafts.queue:
    image: rabbitmq:management-alpine
    container_name: ScreenDrafts.Queue
    hostname: screendrafts-queue
    volumes:
        - ./.containers/queue/data/:/var/lib/rabbitmq
        - ./.containers/queue/log/:/var/log/rabbitmq
    environment:
        RABBITMQ_DEFAULT_USER: guest
        RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 5672:5672
      - 15672:15672

  screendrafts.mongo:
    image: mongo:latest
    container_name: ScreenDrafts.Mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - ./.containers/mongo:/data/db
    ports:
      - 27017:27017

  screendrafts.email:
    image: changemakerstudiosus/papercut-smtp:latest
    container_name: ScreenDrafts.Email
    ports:
      - "8085:80"
      - "25:25"

  screendrafts.elk:
    image: sebp/elk
    container_name: ScreenDrafts.Elk
    volumes:
      - ./.containers/elk:/usr/share/elk/data
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"

  
  

    

