DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'drafts') THEN
        CREATE SCHEMA drafts;
    END IF;
END $EF$;
CREATE TABLE IF NOT EXISTS drafts."__EFMigrationsHistory" (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);

START TRANSACTION;
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'drafts') THEN
        CREATE SCHEMA drafts;
    END IF;
END $EF$;

CREATE TABLE drafts.drafter_teams (
    id uuid NOT NULL,
    name character varying(100) NOT NULL,
    CONSTRAINT pk_drafter_teams PRIMARY KEY (id)
);

CREATE TABLE drafts.drafters (
    id uuid NOT NULL,
    readable_id integer GENERATED BY DEFAULT AS IDENTITY,
    user_id uuid,
    name character varying(100) NOT NULL,
    CONSTRAINT pk_drafters PRIMARY KEY (id)
);

CREATE TABLE drafts.drafts (
    id uuid NOT NULL,
    readable_id integer GENERATED BY DEFAULT AS IDENTITY,
    title character varying(255) NOT NULL,
    draft_type integer NOT NULL,
    episode_type integer NOT NULL,
    total_picks integer NOT NULL,
    total_drafters integer NOT NULL,
    total_drafter_teams integer NOT NULL,
    total_hosts integer NOT NULL,
    episode_number text,
    draft_status integer NOT NULL,
    created_at_utc timestamp with time zone NOT NULL,
    updated_at_utc timestamp with time zone,
    is_patreon_only boolean NOT NULL,
    CONSTRAINT pk_drafts PRIMARY KEY (id)
);

CREATE TABLE drafts.hosts (
    id uuid NOT NULL,
    readable_id integer GENERATED BY DEFAULT AS IDENTITY,
    user_id uuid,
    host_name text NOT NULL,
    CONSTRAINT pk_hosts PRIMARY KEY (id)
);

CREATE TABLE drafts.inbox_message_consumers (
    inbox_message_id uuid NOT NULL,
    name character varying(500) NOT NULL,
    CONSTRAINT pk_inbox_message_consumers PRIMARY KEY (inbox_message_id, name)
);

CREATE TABLE drafts.inbox_messages (
    id uuid NOT NULL,
    type text NOT NULL,
    content jsonb NOT NULL,
    occurred_on_utc timestamp with time zone NOT NULL,
    processed_on_utc timestamp with time zone,
    error text,
    CONSTRAINT pk_inbox_messages PRIMARY KEY (id)
);

CREATE TABLE drafts.movies (
    id uuid NOT NULL,
    movie_title text NOT NULL,
    imdb_id text NOT NULL,
    CONSTRAINT pk_movies PRIMARY KEY (id)
);

CREATE TABLE drafts.outbox_message_consumers (
    outbox_message_id uuid NOT NULL,
    name character varying(500) NOT NULL,
    CONSTRAINT pk_outbox_message_consumers PRIMARY KEY (outbox_message_id, name)
);

CREATE TABLE drafts.outbox_messages (
    id uuid NOT NULL,
    type text NOT NULL,
    content jsonb NOT NULL,
    occurred_on_utc timestamp with time zone NOT NULL,
    processed_on_utc timestamp with time zone,
    error text,
    CONSTRAINT pk_outbox_messages PRIMARY KEY (id)
);

CREATE TABLE drafts.drafter_team_drafter (
    drafter_id uuid NOT NULL,
    drafter_team_id uuid NOT NULL,
    CONSTRAINT pk_drafter_team_drafter PRIMARY KEY (drafter_id, drafter_team_id),
    CONSTRAINT fk_drafter_team_drafter_drafter_teams_drafter_team_id FOREIGN KEY (drafter_team_id) REFERENCES drafts.drafter_teams (id) ON DELETE CASCADE,
    CONSTRAINT fk_drafter_team_drafter_drafters_drafter_id FOREIGN KEY (drafter_id) REFERENCES drafts.drafters (id) ON DELETE CASCADE
);

CREATE TABLE drafts.rollover_veto_overrides (
    id uuid NOT NULL,
    drafter_id uuid NOT NULL,
    from_draft_id uuid NOT NULL,
    to_draft_id uuid,
    is_used boolean NOT NULL,
    CONSTRAINT pk_rollover_veto_overrides PRIMARY KEY (id),
    CONSTRAINT fk_rollover_veto_overrides_drafters_drafter_id FOREIGN KEY (drafter_id) REFERENCES drafts.drafters (id) ON DELETE CASCADE
);

CREATE TABLE drafts.rollover_vetoes (
    id uuid NOT NULL,
    drafter_id uuid NOT NULL,
    from_draft_id uuid NOT NULL,
    to_draft_id uuid,
    is_used boolean NOT NULL,
    CONSTRAINT pk_rollover_vetoes PRIMARY KEY (id),
    CONSTRAINT fk_rollover_vetoes_drafters_drafter_id FOREIGN KEY (drafter_id) REFERENCES drafts.drafters (id) ON DELETE CASCADE
);

CREATE TABLE drafts.vetoes (
    id uuid NOT NULL,
    is_used boolean NOT NULL,
    drafter_id uuid,
    drafter_team_id uuid,
    CONSTRAINT pk_vetoes PRIMARY KEY (id),
    CONSTRAINT fk_vetoes_drafter_teams_drafter_team_id FOREIGN KEY (drafter_team_id) REFERENCES drafts.drafter_teams (id),
    CONSTRAINT fk_vetoes_drafters_drafter_id FOREIGN KEY (drafter_id) REFERENCES drafts.drafters (id)
);

CREATE TABLE drafts.draft_release_date (
    draft_id uuid NOT NULL,
    release_date date NOT NULL,
    CONSTRAINT pk_draft_release_date PRIMARY KEY (draft_id, release_date),
    CONSTRAINT fk_draft_release_date_drafts_draft_id FOREIGN KEY (draft_id) REFERENCES drafts.drafts (id) ON DELETE CASCADE
);

CREATE TABLE drafts.drafter_draft_stats (
    id uuid NOT NULL,
    drafter_id uuid NOT NULL,
    draft_id uuid NOT NULL,
    starting_vetoes integer NOT NULL DEFAULT 1,
    starting_veto_overrides integer NOT NULL DEFAULT 0,
    commissioner_overrides integer NOT NULL,
    rollovers_applied integer NOT NULL DEFAULT 0,
    trivia_vetoes integer NOT NULL DEFAULT 0,
    trivia_veto_overrides integer NOT NULL,
    drafter_team_id uuid,
    CONSTRAINT pk_drafter_draft_stats PRIMARY KEY (id, drafter_id, draft_id),
    CONSTRAINT fk_drafter_draft_stats_drafter_teams_drafter_team_id FOREIGN KEY (drafter_team_id) REFERENCES drafts.drafter_teams (id),
    CONSTRAINT fk_drafter_draft_stats_drafters_drafter_id FOREIGN KEY (drafter_id) REFERENCES drafts.drafters (id) ON DELETE CASCADE,
    CONSTRAINT fk_drafter_draft_stats_drafts_draft_id FOREIGN KEY (draft_id) REFERENCES drafts.drafts (id) ON DELETE CASCADE
);

CREATE TABLE drafts.drafts_drafter_teams (
    draft_id uuid NOT NULL,
    drafter_team_id uuid NOT NULL,
    CONSTRAINT pk_drafts_drafter_teams PRIMARY KEY (draft_id, drafter_team_id),
    CONSTRAINT fk_drafts_drafter_teams_drafter_teams_drafter_team_id FOREIGN KEY (drafter_team_id) REFERENCES drafts.drafter_teams (id) ON DELETE CASCADE,
    CONSTRAINT fk_drafts_drafter_teams_drafts_draft_id FOREIGN KEY (draft_id) REFERENCES drafts.drafts (id) ON DELETE CASCADE
);

CREATE TABLE drafts.drafts_drafters (
    draft_id uuid NOT NULL,
    drafter_id uuid NOT NULL,
    CONSTRAINT pk_drafts_drafters PRIMARY KEY (draft_id, drafter_id),
    CONSTRAINT fk_drafts_drafters_drafters_drafter_id FOREIGN KEY (drafter_id) REFERENCES drafts.drafters (id) ON DELETE CASCADE,
    CONSTRAINT fk_drafts_drafters_drafts_draft_id FOREIGN KEY (draft_id) REFERENCES drafts.drafts (id) ON DELETE CASCADE
);

CREATE TABLE drafts.game_boards (
    id uuid NOT NULL,
    draft_id uuid NOT NULL,
    CONSTRAINT pk_game_boards PRIMARY KEY (id),
    CONSTRAINT fk_game_boards_drafts_draft_id FOREIGN KEY (draft_id) REFERENCES drafts.drafts (id) ON DELETE CASCADE
);

CREATE TABLE drafts.trivia_results (
    id uuid NOT NULL,
    draft_id uuid NOT NULL,
    drafter_id uuid NOT NULL,
    position integer NOT NULL,
    questions_won integer NOT NULL,
    CONSTRAINT pk_trivia_results PRIMARY KEY (id),
    CONSTRAINT fk_trivia_results_drafters_drafter_id FOREIGN KEY (drafter_id) REFERENCES drafts.drafters (id) ON DELETE CASCADE,
    CONSTRAINT fk_trivia_results_drafts_draft_id FOREIGN KEY (draft_id) REFERENCES drafts.drafts (id) ON DELETE CASCADE
);

CREATE TABLE drafts.draft_host (
    hosted_drafts_id uuid NOT NULL,
    hosts_id uuid NOT NULL,
    CONSTRAINT pk_draft_host PRIMARY KEY (hosted_drafts_id, hosts_id),
    CONSTRAINT fk_draft_host_drafts_hosted_drafts_id FOREIGN KEY (hosted_drafts_id) REFERENCES drafts.drafts (id) ON DELETE CASCADE,
    CONSTRAINT fk_draft_host_hosts_hosts_id FOREIGN KEY (hosts_id) REFERENCES drafts.hosts (id) ON DELETE CASCADE
);

CREATE TABLE drafts.picks (
    id uuid NOT NULL,
    position integer NOT NULL,
    movie_id uuid NOT NULL,
    veto_id uuid,
    drafter_id uuid NOT NULL,
    draft_id uuid NOT NULL,
    drafter_team_id uuid,
    CONSTRAINT pk_picks PRIMARY KEY (id),
    CONSTRAINT fk_picks_drafter_teams_drafter_team_id FOREIGN KEY (drafter_team_id) REFERENCES drafts.drafter_teams (id),
    CONSTRAINT fk_picks_drafters_drafter_id FOREIGN KEY (drafter_id) REFERENCES drafts.drafters (id) ON DELETE CASCADE,
    CONSTRAINT fk_picks_drafts_draft_id FOREIGN KEY (draft_id) REFERENCES drafts.drafts (id) ON DELETE CASCADE,
    CONSTRAINT fk_picks_movies_movie_id FOREIGN KEY (movie_id) REFERENCES drafts.movies (id) ON DELETE CASCADE,
    CONSTRAINT fk_picks_vetoes_veto_id FOREIGN KEY (veto_id) REFERENCES drafts.vetoes (id)
);

CREATE TABLE drafts.veto_overrides (
    id uuid NOT NULL,
    veto_id uuid NOT NULL,
    is_used boolean NOT NULL,
    drafter_id uuid,
    drafter_team_id uuid,
    CONSTRAINT pk_veto_overrides PRIMARY KEY (id),
    CONSTRAINT fk_veto_overrides_drafter_teams_drafter_team_id FOREIGN KEY (drafter_team_id) REFERENCES drafts.drafter_teams (id),
    CONSTRAINT fk_veto_overrides_drafters_drafter_id FOREIGN KEY (drafter_id) REFERENCES drafts.drafters (id),
    CONSTRAINT fk_veto_overrides_vetoes_veto_id FOREIGN KEY (veto_id) REFERENCES drafts.vetoes (id) ON DELETE CASCADE
);

CREATE TABLE drafts.draft_positions (
    id uuid NOT NULL,
    game_board_id uuid NOT NULL,
    name character varying(50) NOT NULL,
    picks text NOT NULL,
    has_bonus_veto boolean NOT NULL,
    has_bonus_veto_override boolean NOT NULL,
    drafter_id uuid,
    drafter_team_id uuid,
    CONSTRAINT pk_draft_positions PRIMARY KEY (id),
    CONSTRAINT fk_draft_positions_drafter_teams_drafter_team_id FOREIGN KEY (drafter_team_id) REFERENCES drafts.drafter_teams (id) ON DELETE RESTRICT,
    CONSTRAINT fk_draft_positions_drafters_drafter_id FOREIGN KEY (drafter_id) REFERENCES drafts.drafters (id) ON DELETE RESTRICT,
    CONSTRAINT fk_draft_positions_game_boards_game_board_id FOREIGN KEY (game_board_id) REFERENCES drafts.game_boards (id) ON DELETE CASCADE
);

CREATE TABLE drafts.commissioner_overrides (
    id uuid NOT NULL,
    pick_id uuid NOT NULL,
    draft_id uuid,
    CONSTRAINT pk_commissioner_overrides PRIMARY KEY (id),
    CONSTRAINT fk_commissioner_overrides_drafts_draft_id FOREIGN KEY (draft_id) REFERENCES drafts.drafts (id),
    CONSTRAINT fk_commissioner_overrides_picks_pick_id FOREIGN KEY (pick_id) REFERENCES drafts.picks (id) ON DELETE CASCADE
);

CREATE INDEX ix_commissioner_overrides_draft_id ON drafts.commissioner_overrides (draft_id);

CREATE UNIQUE INDEX ix_commissioner_overrides_pick_id ON drafts.commissioner_overrides (pick_id);

CREATE INDEX ix_draft_host_hosts_id ON drafts.draft_host (hosts_id);

CREATE INDEX ix_draft_positions_drafter_id ON drafts.draft_positions (drafter_id);

CREATE INDEX ix_draft_positions_drafter_team_id ON drafts.draft_positions (drafter_team_id);

CREATE INDEX ix_draft_positions_game_board_id ON drafts.draft_positions (game_board_id);

CREATE INDEX ix_drafter_draft_stats_draft_id ON drafts.drafter_draft_stats (draft_id);

CREATE INDEX ix_drafter_draft_stats_drafter_id ON drafts.drafter_draft_stats (drafter_id);

CREATE INDEX ix_drafter_draft_stats_drafter_team_id ON drafts.drafter_draft_stats (drafter_team_id);

CREATE INDEX ix_drafter_team_drafter_drafter_team_id ON drafts.drafter_team_drafter (drafter_team_id);

CREATE UNIQUE INDEX ix_drafts_readable_id ON drafts.drafts (readable_id);

CREATE INDEX ix_drafts_drafter_teams_drafter_team_id ON drafts.drafts_drafter_teams (drafter_team_id);

CREATE INDEX ix_drafts_drafters_drafter_id ON drafts.drafts_drafters (drafter_id);

CREATE UNIQUE INDEX ix_game_boards_draft_id ON drafts.game_boards (draft_id);

CREATE INDEX ix_picks_draft_id ON drafts.picks (draft_id);

CREATE INDEX ix_picks_drafter_id ON drafts.picks (drafter_id);

CREATE INDEX ix_picks_drafter_team_id ON drafts.picks (drafter_team_id);

CREATE INDEX ix_picks_movie_id ON drafts.picks (movie_id);

CREATE UNIQUE INDEX ix_picks_veto_id ON drafts.picks (veto_id);

CREATE UNIQUE INDEX ix_rollover_veto_overrides_drafter_id ON drafts.rollover_veto_overrides (drafter_id);

CREATE UNIQUE INDEX ix_rollover_vetoes_drafter_id ON drafts.rollover_vetoes (drafter_id);

CREATE INDEX ix_trivia_results_draft_id ON drafts.trivia_results (draft_id);

CREATE INDEX ix_trivia_results_drafter_id ON drafts.trivia_results (drafter_id);

CREATE INDEX ix_veto_overrides_drafter_id ON drafts.veto_overrides (drafter_id);

CREATE INDEX ix_veto_overrides_drafter_team_id ON drafts.veto_overrides (drafter_team_id);

CREATE UNIQUE INDEX ix_veto_overrides_veto_id ON drafts.veto_overrides (veto_id);

CREATE INDEX ix_vetoes_drafter_id ON drafts.vetoes (drafter_id);

CREATE INDEX ix_vetoes_drafter_team_id ON drafts.vetoes (drafter_team_id);

INSERT INTO drafts."__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20250326005222_Add_Initial', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE drafts.picks DROP CONSTRAINT fk_picks_drafter_teams_drafter_team_id;

ALTER TABLE drafts.picks ALTER COLUMN drafter_id DROP NOT NULL;

ALTER TABLE drafts.drafts ADD non_canonical boolean NOT NULL DEFAULT FALSE;

ALTER TABLE drafts.picks ADD CONSTRAINT fk_picks_drafter_teams_drafter_team_id FOREIGN KEY (drafter_team_id) REFERENCES drafts.drafter_teams (id) ON DELETE CASCADE;

INSERT INTO drafts."__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20250327185320_Update_Picks', '10.0.1');

COMMIT;

START TRANSACTION;
DROP INDEX drafts.ix_picks_draft_id;

CREATE UNIQUE INDEX ix_picks_draft_id_position_movie_id ON drafts.picks (draft_id, position, movie_id);

INSERT INTO drafts."__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20250330004752_Update_Pick_Index', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE drafts.picks DROP CONSTRAINT fk_picks_vetoes_veto_id;

ALTER TABLE drafts.veto_overrides DROP CONSTRAINT fk_veto_overrides_drafter_teams_drafter_team_id;

ALTER TABLE drafts.veto_overrides DROP CONSTRAINT fk_veto_overrides_drafters_drafter_id;

ALTER TABLE drafts.vetoes DROP CONSTRAINT fk_vetoes_drafter_teams_drafter_team_id;

ALTER TABLE drafts.vetoes DROP CONSTRAINT fk_vetoes_drafters_drafter_id;

DROP INDEX drafts.ix_picks_draft_id_position_movie_id;

DROP INDEX drafts.ix_picks_veto_id;

ALTER TABLE drafts.vetoes DROP COLUMN is_used;

ALTER TABLE drafts.veto_overrides DROP COLUMN is_used;

ALTER TABLE drafts.picks DROP COLUMN veto_id;

ALTER TABLE drafts.vetoes ADD pick_id uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000';

ALTER TABLE drafts.picks ADD play_order integer NOT NULL DEFAULT 0;

CREATE UNIQUE INDEX ix_vetoes_pick_id ON drafts.vetoes (pick_id);

CREATE INDEX ix_picks_draft_id_play_order ON drafts.picks (draft_id, play_order);

CREATE UNIQUE INDEX ix_picks_draft_id_position_movie_id_play_order ON drafts.picks (draft_id, position, movie_id, play_order);

ALTER TABLE drafts.veto_overrides ADD CONSTRAINT fk_veto_overrides_drafter_teams_drafter_team_id FOREIGN KEY (drafter_team_id) REFERENCES drafts.drafter_teams (id) ON DELETE CASCADE;

ALTER TABLE drafts.veto_overrides ADD CONSTRAINT fk_veto_overrides_drafters_drafter_id FOREIGN KEY (drafter_id) REFERENCES drafts.drafters (id) ON DELETE CASCADE;

ALTER TABLE drafts.vetoes ADD CONSTRAINT fk_vetoes_drafter_teams_drafter_team_id FOREIGN KEY (drafter_team_id) REFERENCES drafts.drafter_teams (id) ON DELETE CASCADE;

ALTER TABLE drafts.vetoes ADD CONSTRAINT fk_vetoes_drafters_drafter_id FOREIGN KEY (drafter_id) REFERENCES drafts.drafters (id) ON DELETE CASCADE;

ALTER TABLE drafts.vetoes ADD CONSTRAINT fk_vetoes_picks_pick_id FOREIGN KEY (pick_id) REFERENCES drafts.picks (id) ON DELETE CASCADE;

INSERT INTO drafts."__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20250404010150_UpdatePickVetoVetoOverride', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE drafts.drafter_draft_stats DROP CONSTRAINT fk_drafter_draft_stats_drafters_drafter_id;

ALTER TABLE drafts.drafter_draft_stats DROP CONSTRAINT pk_drafter_draft_stats;

ALTER TABLE drafts.trivia_results ALTER COLUMN drafter_id DROP NOT NULL;

ALTER TABLE drafts.trivia_results ADD drafter_team_id uuid;

ALTER TABLE drafts.drafter_draft_stats ALTER COLUMN drafter_id DROP NOT NULL;

ALTER TABLE drafts.drafter_draft_stats ADD CONSTRAINT pk_drafter_draft_stats PRIMARY KEY (id, draft_id);

CREATE INDEX ix_trivia_results_drafter_team_id ON drafts.trivia_results (drafter_team_id);

ALTER TABLE drafts.drafter_draft_stats ADD CONSTRAINT fk_drafter_draft_stats_drafters_drafter_id FOREIGN KEY (drafter_id) REFERENCES drafts.drafters (id);

ALTER TABLE drafts.trivia_results ADD CONSTRAINT fk_trivia_results_drafter_teams_drafter_team_id FOREIGN KEY (drafter_team_id) REFERENCES drafts.drafter_teams (id) ON DELETE CASCADE;

INSERT INTO drafts."__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20250412183100_UpdateDraftStats', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE drafts.commissioner_overrides DROP COLUMN draft_id;

INSERT INTO drafts."__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20250417162209_UpdatePick', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE drafts.rollover_vetoes ALTER COLUMN drafter_id DROP NOT NULL;

ALTER TABLE drafts.rollover_vetoes ADD drafter_team_id uuid;

ALTER TABLE drafts.rollover_veto_overrides ALTER COLUMN drafter_id DROP NOT NULL;

ALTER TABLE drafts.rollover_veto_overrides ADD drafter_team_id uuid;

ALTER TABLE drafts.drafter_teams ADD number_of_drafters integer NOT NULL DEFAULT 0;

CREATE UNIQUE INDEX ix_rollover_vetoes_drafter_team_id ON drafts.rollover_vetoes (drafter_team_id);

CREATE UNIQUE INDEX ix_rollover_veto_overrides_drafter_team_id ON drafts.rollover_veto_overrides (drafter_team_id);

ALTER TABLE drafts.rollover_veto_overrides ADD CONSTRAINT fk_rollover_veto_overrides_drafter_teams_drafter_team_id FOREIGN KEY (drafter_team_id) REFERENCES drafts.drafter_teams (id) ON DELETE CASCADE;

ALTER TABLE drafts.rollover_vetoes ADD CONSTRAINT fk_rollover_vetoes_drafter_teams_drafter_team_id FOREIGN KEY (drafter_team_id) REFERENCES drafts.drafter_teams (id) ON DELETE CASCADE;

INSERT INTO drafts."__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20250420202542_Update_RolloverVeto', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE drafts.drafter_draft_stats DROP COLUMN rollovers_applied;

ALTER TABLE drafts.drafter_draft_stats DROP COLUMN starting_veto_overrides;

ALTER TABLE drafts.drafter_draft_stats ALTER COLUMN trivia_vetoes DROP DEFAULT;

ALTER TABLE drafts.drafter_draft_stats ALTER COLUMN trivia_veto_overrides DROP NOT NULL;

ALTER TABLE drafts.drafter_draft_stats ADD rollover_veto integer NOT NULL DEFAULT 0;

ALTER TABLE drafts.drafter_draft_stats ADD rollover_veto_override integer;

ALTER TABLE drafts.drafter_draft_stats ADD veto_overrides_used integer;

ALTER TABLE drafts.drafter_draft_stats ADD vetoes_used integer NOT NULL DEFAULT 0;

INSERT INTO drafts."__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20250422202514_Update_DraftStats', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE drafts.drafts ADD description text;

INSERT INTO drafts."__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20250624013436_Add_Draft_Description', '10.0.1');

COMMIT;

START TRANSACTION;
UPDATE drafts.drafts
SET episode_number = TRIM(episode_number)
WHERE episode_number !~ '^\s*\d+\s*$';

ALTER TABLE drafts.drafts
  ALTER COLUMN episode_number
  TYPE integer
  USING NULLIF(episode_number, '')::integer

ALTER TABLE drafts.drafts ALTER COLUMN episode_number TYPE integer;
COMMENT ON COLUMN drafts.drafts.episode_number IS 'Episode number (int)';

INSERT INTO drafts."__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20250625111619_ConvertEpisodeNumberToText', '10.0.1');

COMMIT;

START TRANSACTION;
CREATE TABLE drafts.people (
    id uuid NOT NULL,
    user_id uuid,
    first_name text NOT NULL,
    last_name text NOT NULL,
    display_name text,
    CONSTRAINT pk_people PRIMARY KEY (id)
);

ALTER TABLE drafts.hosts ADD person_id uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000';

ALTER TABLE drafts.drafters ADD person_id uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000';

WITH AllNames AS (
    SELECT DISTINCT host_name AS display_name FROM drafts.hosts
    UNION
    SELECT DISTINCT name AS display_name FROM drafts.drafters
),
SplitNames AS (
    SELECT 
        display_name,
        regexp_replace(display_name, '\s+[^ ]+$', '') AS first_name,
        split_part(display_name, ' ', array_length(string_to_array(display_name, ' '), 1)) AS last_name
    FROM AllNames
)
INSERT INTO drafts.people (id, first_name, last_name, display_name)
SELECT 
    gen_random_uuid() AS id,
    first_name,
    last_name,
    display_name
FROM SplitNames
WHERE display_name IS NOT NULL AND display_name <> '';

UPDATE drafts.hosts
SET person_id = p.id
FROM drafts.people p
WHERE drafts.hosts.host_name = p.display_name

UPDATE drafts.drafters
SET person_id = p.id
FROM drafts.people p
WHERE drafts.drafters.name = p.display_name;

ALTER TABLE drafts.hosts DROP COLUMN host_name;

ALTER TABLE drafts.hosts DROP COLUMN user_id;

ALTER TABLE drafts.drafters DROP COLUMN name;

ALTER TABLE drafts.drafters DROP COLUMN user_id;

ALTER TABLE drafts.hosts ALTER COLUMN person_id SET NOT NULL;

ALTER TABLE drafts.drafters ALTER COLUMN person_id SET NOT NULL;

CREATE UNIQUE INDEX ix_hosts_person_id ON drafts.hosts (person_id);

CREATE UNIQUE INDEX ix_drafters_person_id ON drafts.drafters (person_id);

ALTER TABLE drafts.drafters ADD CONSTRAINT fk_drafters_people_person_id FOREIGN KEY (person_id) REFERENCES drafts.people (id) ON DELETE CASCADE;

ALTER TABLE drafts.hosts ADD CONSTRAINT fk_hosts_people_person_id FOREIGN KEY (person_id) REFERENCES drafts.people (id) ON DELETE CASCADE;

INSERT INTO drafts."__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20250718183045_Add_People_Upadate_Drafters_and_Hosts', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE drafts.drafter_draft_stats DROP CONSTRAINT fk_drafter_draft_stats_drafter_teams_drafter_team_id;

ALTER TABLE drafts.drafter_draft_stats DROP CONSTRAINT fk_drafter_draft_stats_drafters_drafter_id;

ALTER TABLE drafts.drafter_draft_stats ADD CONSTRAINT fk_drafter_draft_stats_drafter_teams_drafter_team_id FOREIGN KEY (drafter_team_id) REFERENCES drafts.drafter_teams (id) ON DELETE CASCADE;

ALTER TABLE drafts.drafter_draft_stats ADD CONSTRAINT fk_drafter_draft_stats_drafters_drafter_id FOREIGN KEY (drafter_id) REFERENCES drafts.drafters (id) ON DELETE CASCADE;

INSERT INTO drafts."__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20250728145834_Update_DraftStatsConfig', '10.0.1');

COMMIT;

START TRANSACTION;
INSERT INTO drafts."__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20250728155836_UpdateDraftDraftStatsConfiguration', '10.0.1');

COMMIT;

START TRANSACTION;
CREATE TABLE drafts.draft_hosts (
    draft_id uuid NOT NULL,
    host_id uuid NOT NULL,
    role integer NOT NULL,
    CONSTRAINT pk_draft_hosts PRIMARY KEY (draft_id, host_id),
    CONSTRAINT fk_draft_hosts_drafts_draft_id FOREIGN KEY (draft_id) REFERENCES drafts.drafts (id) ON DELETE CASCADE,
    CONSTRAINT fk_draft_hosts_hosts_host_id FOREIGN KEY (host_id) REFERENCES drafts.hosts (id) ON DELETE RESTRICT
);

WITH ranked AS (
  SELECT
    dh.hosted_drafts_id,
    dh.hosts_id,
    ROW_NUMBER() OVER (PARTITION BY dh.hosted_drafts_id ORDER BY dh.hosts_id) AS rn
  FROM
    drafts.draft_host dh
)
INSERT INTO drafts.draft_hosts (draft_id, host_id, role)
SELECT
  r.hosted_drafts_id AS draft_id,
  r.hosts_id AS host_id,
  CASE WHEN r.rn = 1 THEN 0 ELSE 1 END AS role
FROM
  ranked r

CREATE INDEX ix_draft_hosts_host_id ON drafts.draft_hosts (host_id);

CREATE UNIQUE INDEX ux_draft_hosts_one_primary_per_draft ON drafts.draft_hosts (draft_id) WHERE role = 0;

DROP TABLE drafts.draft_host;

INSERT INTO drafts."__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20250820111844_UpdateHostsAndCoHosts', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE drafts.drafts ADD is_scream_drafts boolean NOT NULL DEFAULT FALSE;

INSERT INTO drafts."__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20250826141221_Add_ScreamDraftsFlag', '10.0.1');

COMMIT;

START TRANSACTION;
CREATE TABLE drafts.categories (
    id uuid NOT NULL,
    name character varying(100) NOT NULL,
    description character varying(500),
    created_on_utc timestamp with time zone NOT NULL,
    modified_on_utc timestamp with time zone,
    CONSTRAINT pk_categories PRIMARY KEY (id)
);

CREATE TABLE drafts.draft_categories (
    draft_id uuid NOT NULL,
    category_id uuid NOT NULL,
    CONSTRAINT pk_draft_categories PRIMARY KEY (draft_id, category_id),
    CONSTRAINT fk_draft_categories_categories_category_id FOREIGN KEY (category_id) REFERENCES drafts.categories (id) ON DELETE CASCADE,
    CONSTRAINT fk_draft_categories_drafts_draft_id FOREIGN KEY (draft_id) REFERENCES drafts.drafts (id) ON DELETE CASCADE
);

CREATE INDEX ix_draft_categories_category_id ON drafts.draft_categories (category_id);

INSERT INTO drafts."__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20250827112302_Add_Draft_Categories', '10.0.1');

COMMIT;

START TRANSACTION;
CREATE TABLE drafts.series (
    id uuid NOT NULL,
    name text NOT NULL,
    kind integer NOT NULL,
    canonical_policy integer NOT NULL,
    continuity_scope integer NOT NULL,
    continuity_date_rule integer NOT NULL,
    required_draft_type integer,
    default_draft_type integer,
    allowed_draft_types integer NOT NULL,
    CONSTRAINT pk_series PRIMARY KEY (id)
);

ALTER TABLE drafts.drafts ADD series_id uuid;

CREATE INDEX ix_drafts_series_id ON drafts.drafts (series_id);

ALTER TABLE drafts.drafts ADD CONSTRAINT fk_drafts_series_series_id FOREIGN KEY (series_id) REFERENCES drafts.series (id);

CREATE TABLE drafts.campaigns (
    id uuid NOT NULL,
    slug text NOT NULL,
    name text NOT NULL,
    CONSTRAINT pk_campaigns PRIMARY KEY (id)
);

CREATE INDEX ix_campaigns_id ON drafts.campaigns (id);

CREATE UNIQUE INDEX ix_campaigns_slug ON drafts.campaigns (slug);

CREATE TABLE drafts.drafts_campaigns (
    campaign_id uuid NOT NULL,
    draft_id uuid NOT NULL,
    CONSTRAINT pk_drafts_campaigns PRIMARY KEY (campaign_id, draft_id),
    CONSTRAINT fk_drafts_campaigns_campaign_id FOREIGN KEY (campaign_id) REFERENCES drafts.campaigns (id) ON DELETE CASCADE,
    CONSTRAINT fk_drafts_campaigns_draft_id FOREIGN KEY (draft_id) REFERENCES drafts.drafts (id) ON DELETE CASCADE
);

CREATE INDEX ix_drafts_campaigns_draft_id ON drafts.drafts_campaigns (draft_id);

CREATE TABLE drafts.draft_parts (
    id uuid NOT NULL,
    draft_id uuid NOT NULL,
    part_index integer NOT NULL,
    CONSTRAINT pk_draft_parts PRIMARY KEY (id),
    CONSTRAINT fk_draft_parts_drafts_draft_id FOREIGN KEY (draft_id) REFERENCES drafts.drafts (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX ix_draft_parts_draft_id_part_index ON drafts.draft_parts (draft_id, part_index);

CREATE TABLE drafts.draft_releases (
    part_id uuid NOT NULL,
    release_channel integer NOT NULL,
    release_date date NOT NULL,
    created_on_utc timestamp with time zone NOT NULL,
    CONSTRAINT pk_draft_releases PRIMARY KEY (part_id, release_channel, release_date),
    CONSTRAINT fk_draft_releases_draft_parts_part_id FOREIGN KEY (part_id) REFERENCES drafts.draft_parts (id) ON DELETE RESTRICT
);

CREATE INDEX ix_draft_releases_release_channel_release_date ON drafts.draft_releases (release_channel, release_date);

INSERT INTO drafts.series (id, name, kind, canonical_policy, continuity_scope, continuity_date_rule, required_draft_type, default_draft_type, allowed_draft_types)
VALUES ('901f5660-b28d-4dd8-a721-e544e1a9746a', 'Default', 0, 0, 2, 0, NULL, NULL, 31);
INSERT INTO drafts.series (id, name, kind, canonical_policy, continuity_scope, continuity_date_rule, required_draft_type, default_draft_type, allowed_draft_types)
VALUES ('1da3abf9-45b4-4f06-8449-3f385d439747', 'Franchise mini-Super', 1, 1, 0, 0, 4, 4, 16);
INSERT INTO drafts.series (id, name, kind, canonical_policy, continuity_scope, continuity_date_rule, required_draft_type, default_draft_type, allowed_draft_types)
VALUES ('6e6316a3-db93-47a3-8193-56e4d6fe52f7', 'Bryan and Billy Ray''s Nonagenarian In-Memoream', 2, 2, 1, 1, 0, 0, 1);
INSERT INTO drafts.series (id, name, kind, canonical_policy, continuity_scope, continuity_date_rule, required_draft_type, default_draft_type, allowed_draft_types)
VALUES ('b433551b-58b3-41a8-b2de-850a8769a7c9', 'Legends Invitational', 3, 1, 0, 0, 2, 2, 4);
INSERT INTO drafts.series (id, name, kind, canonical_policy, continuity_scope, continuity_date_rule, required_draft_type, default_draft_type, allowed_draft_types)
VALUES ('ef974663-1947-4a1e-8db9-ff65e55b99a9', 'Best Picture Nominee mini-Super', 4, 1, 0, 0, 4, 4, 16);
INSERT INTO drafts.series (id, name, kind, canonical_policy, continuity_scope, continuity_date_rule, required_draft_type, default_draft_type, allowed_draft_types)
VALUES ('061dc243-973d-4adc-a57a-1a28ed1f73bb', 'Patreon vs.', 5, 2, 2, 1, 0, 0, 1);
INSERT INTO drafts.series (id, name, kind, canonical_policy, continuity_scope, continuity_date_rule, required_draft_type, default_draft_type, allowed_draft_types)
VALUES ('c778f314-f7e6-4d0c-b2ec-c413e81a178c', 'Live Drafts', 6, 2, 2, 1, NULL, NULL, 15);
INSERT INTO drafts.series (id, name, kind, canonical_policy, continuity_scope, continuity_date_rule, required_draft_type, default_draft_type, allowed_draft_types)
VALUES ('dc6b9480-620d-4bd1-9703-81e456334c03', 'Special Drafts', 7, 1, 0, 0, NULL, 0, 15);
INSERT INTO drafts.series (id, name, kind, canonical_policy, continuity_scope, continuity_date_rule, required_draft_type, default_draft_type, allowed_draft_types)
VALUES ('e91c99b1-c0b5-4868-a991-bd2e72b79315', 'Speed Drafts', 8, 1, 1, 0, 0, 0, 1);

INSERT INTO drafts.campaigns (id, slug, name)
VALUES ('489463a8-0859-4e5d-8c54-2dd0f8ccd524', 'scream-drafts', 'Scream Drafts');
INSERT INTO drafts.campaigns (id, slug, name)
VALUES ('c3533677-6677-401c-8cc4-394afba79e61', 'billy-ray-vs-kyle', 'Billy Ray vs. Kyle');
INSERT INTO drafts.campaigns (id, slug, name)
VALUES ('9fdcaecf-36b0-49d1-93d6-50b710762faa', 'kristmas-eve', 'Kristmas Eve');
INSERT INTO drafts.campaigns (id, slug, name)
VALUES ('a44e539e-79de-48aa-80a5-637b7573025c', 'phil-vs-dana', 'Phil vs. Dana');

  insert into drafts.draft_parts (id, draft_id, part_index)
  select gen_random_uuid(), d.id, 1
  from drafts.drafts d
  where not exists (
    select 1 
    from drafts.draft_parts dp 
    where dp.draft_id = d.id
  );

  create temporary table temp_draft_part_map(
    draft_id uuid primary key,
    part_id uuid not null
  ) on commit drop;

  insert into temp_draft_part_map (draft_id, part_id)
  select dp.draft_id, dp.id
  from drafts.draft_parts dp
  where dp.part_index = 1;

  do $$
  begin
    if exists (select 1 from information_schema.columns
               where table_schema='drafts' and table_name='drafts' and column_name='episode_type' and data_type in ('integer','smallint','bigint')) then
      insert into drafts.draft_releases(part_id, release_channel, release_date, created_on_utc)
      select m.part_id,
             case when d.episode_type = 0 then 0 else 1 end,
             drd.release_date,
             now()
      from drafts.draft_release_date drd
      join temp_draft_part_map m on m.draft_id = drd.draft_id
      join drafts.drafts d on d.id = drd.draft_id;
    end if;
  end$$;

  do $$
  begin
    if exists (select 1 from information_schema.columns
               where table_schema='drafts' and table_name='drafts' and column_name='episode_type' and data_type in ('integer','smallint','bigint')) then
      update drafts.drafts d set series_id = s.id
      from drafts.series s
      where (d.episode_type = 3 and s.name = 'Legends')      
         or (d.episode_type = 1 and s.name = 'Franchise mini-Super')       
         or (d.episode_type = 4 and s.name = 'Best Picture Nominee')      
         or (d.episode_type = 2 and s.name = 'In Memoriam')               
         or (d.episode_type = 5 and s.name = 'Patreon vs')                
         or (d.episode_type = 6 and s.name = 'Live Draft')
         or (d.episode_type = 7 and s.name = 'Special');                  
    end if;
  end$$;

  do $$
  declare scream_id uuid;
  begin
    select id into scream_id from drafts.campaigns where slug='scream-drafts';
    if exists (select 1 from information_schema.columns
                where table_schema='drafts' and table_name='drafts' and column_name='is_screamdrafts') then
      insert into drafts.draft_campaigns(draft_id, campaign_id)
      select d.id, scream_id
      from drafts.drafts d
      where coalesce((d.is_screamdrafts)::boolean, false) = true
      on conflict do nothing;
    end if;
  end$$;

do $$
begin
  -- 1) ALWAYS (Regular) => every legacy date is MainFeed
  insert into drafts.draft_releases(part_id, release_channel, release_date, created_on_utc)
  select distinct
    m.part_id,
    0,
    drd.release_date,
    now()
  from drafts.draft_release_date drd
  join temp_draft_part_map m on m.draft_id = drd.draft_id
  left join drafts.drafts d on d.id = drd.draft_id
  left join drafts.series s on s.id = d.series_id
  where d.series_id is null or s.canonical_policy = 0
  on conflict (part_id, release_channel, release_date) do nothing;

  -- 2) NEVER => every legacy date is Patreon
  insert into drafts.draft_releases(part_id, release_channel, release_date, created_on_utc)
  select distinct
    m.part_id,
    1,
    drd.release_date,
    now()
  from drafts.draft_release_date drd
  join temp_draft_part_map m on m.draft_id = drd.draft_id
  join drafts.drafts d on d.id = drd.draft_id
  join drafts.series s on s.id = d.series_id
  where s.canonical_policy = 1
  on conflict (part_id, release_channel, release_date) do nothing;

  -- 3) ON_MAIN_FEED:
  -- 3a) Insert Patreon for the earliest date
  insert into drafts.draft_releases(part_id, release_channel, release_date, created_on_utc)
  select distinct
    m.part_id,
    1,
    drd.release_date,
    now()
  from drafts.draft_release_date drd
  join temp_draft_part_map m on m.draft_id = drd.draft_id
  join drafts.drafts d on d.id = drd.draft_id
  join drafts.series s on s.id = d.series_id
  join (
    select drd.draft_id, min(drd.release_date) as min_date
    from drafts.draft_release_date drd
    group by drd.draft_id
  ) mi on mi.draft_id = drd.draft_id
  where s.canonical_policy = 2
    and drd.release_date = mi.min_date
  on conflict (part_id, release_channel, release_date) do nothing;

  -- 3b) If the earliest date appears twice (Patreon + MainFeed same day), also insert MainFeed for that date
  insert into drafts.draft_releases(part_id, release_channel, release_date, created_on_utc)
  select distinct
    m.part_id,
    0,
    dc.release_date,
    now()
  from (
    select drd.draft_id, drd.release_date, count(*) as cnt
    from drafts.draft_release_date drd
    group by drd.draft_id, drd.release_date
  ) dc
  join temp_draft_part_map m on m.draft_id = dc.draft_id
  join drafts.drafts d on d.id = dc.draft_id
  join drafts.series s on s.id = d.series_id
  join (
    select drd.draft_id, min(drd.release_date) as min_date
    from drafts.draft_release_date drd
    group by drd.draft_id
  ) mi on mi.draft_id = dc.draft_id
  where s.canonical_policy = 2
    and dc.release_date = mi.min_date
    and dc.cnt >= 2
  on conflict (part_id, release_channel, release_date) do nothing;

  -- 3c) Any later dates (strictly after the min) are MainFeed
  insert into drafts.draft_releases(part_id, release_channel, release_date, created_on_utc)
  select distinct
    m.part_id,
    0,
    drd.release_date,
    now()
  from drafts.draft_release_date drd
  join temp_draft_part_map m on m.draft_id = drd.draft_id
  join drafts.drafts d on d.id = drd.draft_id
  join drafts.series s on s.id = d.series_id
  join (
    select drd.draft_id, min(drd.release_date) as min_date
    from drafts.draft_release_date drd
    group by drd.draft_id
  ) mi on mi.draft_id = drd.draft_id
  where s.canonical_policy = 2
    and drd.release_date > mi.min_date
  on conflict (part_id, release_channel, release_date) do nothing;
end $$;

do $$ begin
  if exists (select 1 from information_schema.columns
             where table_schema='drafts' and table_name='draft_releases' and column_name='draft_id')
  then
    alter table drafts.draft_releases drop column draft_id;
  end if;
end$$;

DROP TABLE drafts.draft_release_date;

ALTER TABLE drafts.drafts DROP COLUMN episode_type;

ALTER TABLE drafts.drafts DROP COLUMN is_patreon_only;

ALTER TABLE drafts.drafts DROP COLUMN is_scream_drafts;

ALTER TABLE drafts.drafts DROP COLUMN non_canonical;

INSERT INTO drafts."__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20250903200832_Update_Drafts_with_Series_Parts', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE drafts.draft_categories DROP CONSTRAINT fk_draft_categories_categories_category_id;

ALTER TABLE drafts.draft_hosts DROP CONSTRAINT fk_draft_hosts_drafts_draft_id;

ALTER TABLE drafts.draft_positions DROP CONSTRAINT fk_draft_positions_drafter_teams_drafter_team_id;

ALTER TABLE drafts.draft_positions DROP CONSTRAINT fk_draft_positions_drafters_drafter_id;

ALTER TABLE drafts.draft_releases DROP CONSTRAINT fk_draft_releases_draft_parts_part_id;

ALTER TABLE drafts.drafters DROP CONSTRAINT fk_drafters_people_person_id;

ALTER TABLE drafts.drafts DROP CONSTRAINT fk_drafts_series_series_id;

ALTER TABLE drafts.game_boards DROP CONSTRAINT fk_game_boards_drafts_draft_id;

ALTER TABLE drafts.picks DROP CONSTRAINT fk_picks_drafter_teams_drafter_team_id;

ALTER TABLE drafts.picks DROP CONSTRAINT fk_picks_drafters_drafter_id;

ALTER TABLE drafts.picks DROP CONSTRAINT fk_picks_drafts_draft_id;

ALTER TABLE drafts.picks DROP CONSTRAINT fk_picks_movies_movie_id;

ALTER TABLE drafts.trivia_results DROP CONSTRAINT fk_trivia_results_drafter_teams_drafter_team_id;

ALTER TABLE drafts.trivia_results DROP CONSTRAINT fk_trivia_results_drafters_drafter_id;

ALTER TABLE drafts.trivia_results DROP CONSTRAINT fk_trivia_results_drafts_draft_id;

ALTER TABLE drafts.veto_overrides DROP CONSTRAINT fk_veto_overrides_drafter_teams_drafter_team_id;

ALTER TABLE drafts.veto_overrides DROP CONSTRAINT fk_veto_overrides_drafters_drafter_id;

ALTER TABLE drafts.vetoes DROP CONSTRAINT fk_vetoes_drafter_teams_drafter_team_id;

ALTER TABLE drafts.vetoes DROP CONSTRAINT fk_vetoes_drafters_drafter_id;

ALTER TABLE drafts.vetoes DROP CONSTRAINT fk_vetoes_picks_pick_id;

DROP TABLE drafts.drafter_draft_stats;

DROP TABLE drafts.drafts_campaigns;

DROP TABLE drafts.drafts_drafter_teams;

DROP TABLE drafts.drafts_drafters;

DROP TABLE drafts.rollover_veto_overrides;

DROP TABLE drafts.rollover_vetoes;

DROP INDEX drafts.ix_vetoes_drafter_id;

DROP INDEX drafts.ix_vetoes_drafter_team_id;

DROP INDEX drafts.ix_veto_overrides_drafter_id;

DROP INDEX drafts.ix_veto_overrides_drafter_team_id;

DROP INDEX drafts.ix_trivia_results_draft_id;

DROP INDEX drafts.ix_trivia_results_drafter_id;

DROP INDEX drafts.ix_trivia_results_drafter_team_id;

DROP INDEX drafts.ix_picks_draft_id_position_movie_id_play_order;

DROP INDEX drafts.ix_picks_drafter_id;

DROP INDEX drafts.ix_picks_drafter_team_id;

DROP INDEX drafts.ix_drafts_readable_id;

DROP INDEX drafts.ix_draft_positions_drafter_id;

DROP INDEX drafts.ix_draft_positions_drafter_team_id;

ALTER TABLE drafts.vetoes DROP COLUMN drafter_id;

ALTER TABLE drafts.vetoes DROP COLUMN drafter_team_id;

ALTER TABLE drafts.veto_overrides DROP COLUMN drafter_id;

ALTER TABLE drafts.veto_overrides DROP COLUMN drafter_team_id;

ALTER TABLE drafts.trivia_results DROP COLUMN drafter_id;

ALTER TABLE drafts.trivia_results DROP COLUMN drafter_team_id;

ALTER TABLE drafts.series DROP COLUMN required_draft_type;

ALTER TABLE drafts.picks DROP COLUMN drafter_id;

ALTER TABLE drafts.picks DROP COLUMN drafter_team_id;

ALTER TABLE drafts.hosts DROP COLUMN readable_id;

ALTER TABLE drafts.drafts DROP COLUMN episode_number;

ALTER TABLE drafts.drafts DROP COLUMN readable_id;

ALTER TABLE drafts.drafts DROP COLUMN total_drafter_teams;

ALTER TABLE drafts.drafts DROP COLUMN total_drafters;

ALTER TABLE drafts.drafts DROP COLUMN total_hosts;

ALTER TABLE drafts.drafts DROP COLUMN total_picks;

ALTER TABLE drafts.drafters DROP COLUMN readable_id;

ALTER TABLE drafts.draft_positions DROP COLUMN drafter_id;

ALTER TABLE drafts.vetoes RENAME COLUMN pick_id TO target_pick_id;

ALTER INDEX drafts.ix_vetoes_pick_id RENAME TO ix_vetoes_target_pick_id;

ALTER TABLE drafts.trivia_results RENAME COLUMN draft_id TO participant_id;

ALTER TABLE drafts.picks RENAME COLUMN draft_id TO played_by_participant_id;

ALTER INDEX drafts.ix_picks_draft_id_play_order RENAME TO ix_picks_played_by_participant_id_play_order;

ALTER TABLE drafts.game_boards RENAME COLUMN draft_id TO draft_part_id;

ALTER INDEX drafts.ix_game_boards_draft_id RENAME TO ix_game_boards_draft_part_id;

ALTER TABLE drafts.draft_positions RENAME COLUMN drafter_team_id TO assigned_to_id;

ALTER TABLE drafts.draft_hosts RENAME COLUMN draft_id TO draft_part_id;

ALTER INDEX drafts.ux_draft_hosts_one_primary_per_draft RENAME TO ux_draft_hosts_one_primary_per_draft_part;

ALTER TABLE drafts.vetoes ADD is_overridden boolean NOT NULL DEFAULT FALSE;

ALTER TABLE drafts.vetoes ADD issued_by_participant_id uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000';

ALTER TABLE drafts.vetoes ADD note character varying(1000);

ALTER TABLE drafts.vetoes ADD occurred_on timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE drafts.veto_overrides ADD issued_by_participant_id uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000';

ALTER TABLE drafts.trivia_results ADD draft_part_id uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000';

ALTER TABLE drafts.trivia_results ADD participant_kind integer NOT NULL DEFAULT 0;

ALTER TABLE drafts.series ALTER COLUMN name TYPE character varying(200);

ALTER TABLE drafts.series ADD created_at_utc timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE drafts.series ADD public_id character varying(19) NOT NULL DEFAULT '';

ALTER TABLE drafts.series ADD updated_at_utc timestamp with time zone;

ALTER TABLE drafts.picks ADD commissioner_override_id uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000';

ALTER TABLE drafts.picks ADD draft_part_id uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000';

ALTER TABLE drafts.picks ADD movie_version_name character varying(100);

ALTER TABLE drafts.people ADD public_id text NOT NULL DEFAULT '';

ALTER TABLE drafts.hosts ADD public_id character varying(19) NOT NULL DEFAULT '';

UPDATE drafts.drafts SET series_id = '00000000-0000-0000-0000-000000000000' WHERE series_id IS NULL;
ALTER TABLE drafts.drafts ALTER COLUMN series_id SET NOT NULL;
ALTER TABLE drafts.drafts ALTER COLUMN series_id SET DEFAULT '00000000-0000-0000-0000-000000000000';

ALTER TABLE drafts.drafts ADD campaign_id uuid;

ALTER TABLE drafts.drafts ADD public_id character varying(19) NOT NULL DEFAULT '';

ALTER TABLE drafts.drafters ADD is_retired boolean NOT NULL DEFAULT FALSE;

ALTER TABLE drafts.drafters ADD public_id character varying(19) NOT NULL DEFAULT '';

ALTER TABLE drafts.drafters ADD retired_at_utc timestamp with time zone;

ALTER TABLE drafts.draft_releases ADD episode_number integer;

ALTER TABLE drafts.draft_positions ADD assigned_to_kind integer;

ALTER TABLE drafts.draft_parts ADD created_at_utc timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE drafts.draft_parts ADD draft_type integer NOT NULL DEFAULT 0;

ALTER TABLE drafts.draft_parts ADD max_position integer NOT NULL DEFAULT 0;

ALTER TABLE drafts.draft_parts ADD min_position integer NOT NULL DEFAULT 0;

ALTER TABLE drafts.draft_parts ADD movie_version_policy_type integer NOT NULL DEFAULT 0;

ALTER TABLE drafts.draft_parts ADD scheduled_for_utc timestamp with time zone;

ALTER TABLE drafts.draft_parts ADD series_id uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000';

ALTER TABLE drafts.draft_parts ADD status integer NOT NULL DEFAULT 0;

ALTER TABLE drafts.draft_parts ADD updated_at_utc timestamp with time zone;

ALTER TABLE drafts.categories ADD is_deleted boolean NOT NULL DEFAULT FALSE;

ALTER TABLE drafts.categories ADD public_id character varying(19) NOT NULL DEFAULT '';

ALTER TABLE drafts.campaigns ALTER COLUMN slug TYPE character varying(100);

ALTER TABLE drafts.campaigns ALTER COLUMN name TYPE character varying(200);

ALTER TABLE drafts.campaigns ADD created_at_utc timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE drafts.campaigns ADD is_deleted boolean NOT NULL DEFAULT FALSE;

ALTER TABLE drafts.campaigns ADD public_id character varying(19) NOT NULL DEFAULT '';

ALTER TABLE drafts.campaigns ADD updated_at_utc timestamp with time zone;

CREATE TABLE drafts.draft_part_participants (
    id uuid NOT NULL,
    draft_part_id uuid NOT NULL,
    participant_id_value uuid NOT NULL,
    participant_kind_value integer NOT NULL,
    starting_vetoes integer NOT NULL,
    rollover_veto integer NOT NULL,
    rollover_veto_override integer NOT NULL,
    trivia_vetoes integer NOT NULL,
    trivia_veto_overrides integer NOT NULL,
    commissioner_overrides integer NOT NULL,
    vetoes_used integer NOT NULL,
    veto_overrides_used integer NOT NULL,
    CONSTRAINT pk_draft_part_participants PRIMARY KEY (id),
    CONSTRAINT fk_draft_part_participants_draft_parts_draft_part_id FOREIGN KEY (draft_part_id) REFERENCES drafts.draft_parts (id) ON DELETE CASCADE
);

CREATE TABLE drafts.draft_part_required_movie_versions (
    id uuid NOT NULL,
    movie_id uuid NOT NULL,
    version_name character varying(100) NOT NULL,
    draft_part_id uuid NOT NULL,
    CONSTRAINT pk_draft_part_required_movie_versions PRIMARY KEY (id),
    CONSTRAINT fk_draft_part_required_movie_versions_draft_parts_draft_part_id FOREIGN KEY (draft_part_id) REFERENCES drafts.draft_parts (id) ON DELETE CASCADE
);

CREATE TABLE drafts.movie_versions (
    id uuid NOT NULL,
    name character varying(100) NOT NULL,
    movie_id uuid NOT NULL,
    CONSTRAINT pk_movie_versions PRIMARY KEY (id),
    CONSTRAINT fk_movie_versions_movies_movie_id FOREIGN KEY (movie_id) REFERENCES drafts.movies (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX ix_vetoes_issued_by_participant_id_target_pick_id ON drafts.vetoes (issued_by_participant_id, target_pick_id);

CREATE INDEX ix_veto_overrides_issued_by_participant_id ON drafts.veto_overrides (issued_by_participant_id);

CREATE UNIQUE INDEX ix_veto_overrides_veto_id_issued_by_participant_id ON drafts.veto_overrides (veto_id, issued_by_participant_id);

CREATE INDEX ix_trivia_results_draft_part_id ON drafts.trivia_results (draft_part_id);

CREATE UNIQUE INDEX ix_series_public_id ON drafts.series (public_id);

CREATE UNIQUE INDEX ix_picks_commissioner_override_id ON drafts.picks (commissioner_override_id);

CREATE UNIQUE INDEX ix_picks_draft_part_id_play_order ON drafts.picks (draft_part_id, play_order);

CREATE INDEX ix_picks_draft_part_id_position ON drafts.picks (draft_part_id, position);

CREATE UNIQUE INDEX ix_people_public_id ON drafts.people (public_id);

CREATE UNIQUE INDEX ix_hosts_public_id ON drafts.hosts (public_id);

CREATE INDEX ix_drafts_campaign_id ON drafts.drafts (campaign_id);

CREATE UNIQUE INDEX ix_drafts_public_id ON drafts.drafts (public_id);

CREATE UNIQUE INDEX ix_drafters_public_id ON drafts.drafters (public_id);

CREATE UNIQUE INDEX ux_draft_releases_mainfeed_episode_number ON drafts.draft_releases (episode_number) WHERE release_channel = 0 AND episode_number is not null;

CREATE UNIQUE INDEX ix_categories_public_id ON drafts.categories (public_id);

CREATE UNIQUE INDEX ix_campaigns_public_id ON drafts.campaigns (public_id);

CREATE UNIQUE INDEX ux_draft_part_participants_unique ON drafts.draft_part_participants (draft_part_id, participant_id_value, participant_kind_value);

CREATE UNIQUE INDEX ix_draft_part_required_movie_versions_draft_part_id_movie_id ON drafts.draft_part_required_movie_versions (draft_part_id, movie_id);

CREATE UNIQUE INDEX ix_movie_versions_movie_id_name ON drafts.movie_versions (movie_id, name);

ALTER TABLE drafts.draft_categories ADD CONSTRAINT fk_draft_categories_categories_category_id FOREIGN KEY (category_id) REFERENCES drafts.categories (id) ON DELETE RESTRICT;

ALTER TABLE drafts.draft_hosts ADD CONSTRAINT fk_draft_hosts_draft_parts_draft_part_id FOREIGN KEY (draft_part_id) REFERENCES drafts.draft_parts (id) ON DELETE CASCADE;

ALTER TABLE drafts.draft_releases ADD CONSTRAINT fk_draft_releases_draft_parts_part_id FOREIGN KEY (part_id) REFERENCES drafts.draft_parts (id) ON DELETE CASCADE;

ALTER TABLE drafts.drafters ADD CONSTRAINT fk_drafters_people_person_id FOREIGN KEY (person_id) REFERENCES drafts.people (id) ON DELETE RESTRICT;

ALTER TABLE drafts.drafts ADD CONSTRAINT fk_drafts_campaigns_campaign_id FOREIGN KEY (campaign_id) REFERENCES drafts.campaigns (id) ON DELETE SET NULL;

ALTER TABLE drafts.drafts ADD CONSTRAINT fk_drafts_series_series_id FOREIGN KEY (series_id) REFERENCES drafts.series (id) ON DELETE RESTRICT;

ALTER TABLE drafts.game_boards ADD CONSTRAINT fk_game_boards_draft_parts_draft_part_id FOREIGN KEY (draft_part_id) REFERENCES drafts.draft_parts (id) ON DELETE CASCADE;

ALTER TABLE drafts.picks ADD CONSTRAINT fk_picks_commissioner_overrides_commissioner_override_id FOREIGN KEY (commissioner_override_id) REFERENCES drafts.commissioner_overrides (id) ON DELETE CASCADE;

ALTER TABLE drafts.picks ADD CONSTRAINT fk_picks_draft_part_participants_played_by_participant_id FOREIGN KEY (played_by_participant_id) REFERENCES drafts.draft_part_participants (id) ON DELETE RESTRICT;

ALTER TABLE drafts.picks ADD CONSTRAINT fk_picks_draft_parts_draft_part_id FOREIGN KEY (draft_part_id) REFERENCES drafts.draft_parts (id) ON DELETE CASCADE;

ALTER TABLE drafts.picks ADD CONSTRAINT fk_picks_movies_movie_id FOREIGN KEY (movie_id) REFERENCES drafts.movies (id) ON DELETE RESTRICT;

ALTER TABLE drafts.trivia_results ADD CONSTRAINT fk_trivia_results_draft_parts_draft_part_id FOREIGN KEY (draft_part_id) REFERENCES drafts.draft_parts (id) ON DELETE CASCADE;

ALTER TABLE drafts.veto_overrides ADD CONSTRAINT fk_veto_overrides_draft_part_participants_issued_by_participan FOREIGN KEY (issued_by_participant_id) REFERENCES drafts.draft_part_participants (id) ON DELETE RESTRICT;

ALTER TABLE drafts.vetoes ADD CONSTRAINT fk_vetoes_draft_part_participants_issued_by_participant_id FOREIGN KEY (issued_by_participant_id) REFERENCES drafts.draft_part_participants (id) ON DELETE RESTRICT;

ALTER TABLE drafts.vetoes ADD CONSTRAINT fk_vetoes_picks_target_pick_id FOREIGN KEY (target_pick_id) REFERENCES drafts.picks (id) ON DELETE CASCADE;

INSERT INTO drafts."__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20260209130408_Database_Refactor', '10.0.1');

COMMIT;

