// <auto-generated>
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ScreenDrafts.Modules.Users.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class Update_ProfilePicture : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.RenameColumn(
                name: "profile_picture_url",
                schema: "users",
                table: "users",
                newName: "profile_picture_path");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.RenameColumn(
                name: "profile_picture_path",
                schema: "users",
                table: "users",
                newName: "profile_picture_url");
        }
    }
}
