// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ScreenDrafts.Modules.Users.Infrastructure.Database;

#nullable disable

namespace ScreenDrafts.Modules.Users.Infrastructure.Database.Migrations
{
    [DbContext(typeof(UsersDbContext))]
    partial class UsersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("users")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PermissionRole", b =>
                {
                    b.Property<string>("PermissionCode")
                        .HasColumnType("character varying(100)")
                        .HasColumnName("permission_code");

                    b.Property<string>("RoleName")
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role_name");

                    b.HasKey("PermissionCode", "RoleName")
                        .HasName("pk_role_permissions");

                    b.HasIndex("RoleName")
                        .HasDatabaseName("ix_role_permissions_role_name");

                    b.ToTable("role_permissions", "users");

                    b.HasData(
                        new
                        {
                            PermissionCode = "users:read",
                            RoleName = "Guest"
                        },
                        new
                        {
                            PermissionCode = "users:update",
                            RoleName = "Guest"
                        },
                        new
                        {
                            PermissionCode = "drafts:list",
                            RoleName = "Guest"
                        },
                        new
                        {
                            PermissionCode = "draft-parts:list",
                            RoleName = "Guest"
                        },
                        new
                        {
                            PermissionCode = "drafts:search",
                            RoleName = "Guest"
                        },
                        new
                        {
                            PermissionCode = "movies:search",
                            RoleName = "Guest"
                        },
                        new
                        {
                            PermissionCode = "actors:search",
                            RoleName = "Guest"
                        },
                        new
                        {
                            PermissionCode = "crew:search",
                            RoleName = "Guest"
                        },
                        new
                        {
                            PermissionCode = "genres:search",
                            RoleName = "Guest"
                        },
                        new
                        {
                            PermissionCode = "studios:search",
                            RoleName = "Guest"
                        },
                        new
                        {
                            PermissionCode = "people:search",
                            RoleName = "Guest"
                        },
                        new
                        {
                            PermissionCode = "categories:search",
                            RoleName = "Guest"
                        },
                        new
                        {
                            PermissionCode = "drafters:read",
                            RoleName = "Guest"
                        },
                        new
                        {
                            PermissionCode = "drafters:list",
                            RoleName = "Guest"
                        },
                        new
                        {
                            PermissionCode = "hosts:read",
                            RoleName = "Guest"
                        },
                        new
                        {
                            PermissionCode = "hosts:list",
                            RoleName = "Guest"
                        },
                        new
                        {
                            PermissionCode = "drafter-teams:read",
                            RoleName = "Guest"
                        },
                        new
                        {
                            PermissionCode = "drafter-teams:list",
                            RoleName = "Guest"
                        },
                        new
                        {
                            PermissionCode = "sub-drafts:read",
                            RoleName = "Guest"
                        },
                        new
                        {
                            PermissionCode = "predictions:read",
                            RoleName = "Guest"
                        },
                        new
                        {
                            PermissionCode = "users:read",
                            RoleName = "Host"
                        },
                        new
                        {
                            PermissionCode = "users:update",
                            RoleName = "Host"
                        },
                        new
                        {
                            PermissionCode = "drafts:read",
                            RoleName = "Host"
                        },
                        new
                        {
                            PermissionCode = "drafts:list",
                            RoleName = "Host"
                        },
                        new
                        {
                            PermissionCode = "drafts:search",
                            RoleName = "Host"
                        },
                        new
                        {
                            PermissionCode = "draft-parts:read",
                            RoleName = "Host"
                        },
                        new
                        {
                            PermissionCode = "draft-parts:list",
                            RoleName = "Host"
                        },
                        new
                        {
                            PermissionCode = "draft-boards:read",
                            RoleName = "Host"
                        },
                        new
                        {
                            PermissionCode = "draft-pools:read",
                            RoleName = "Host"
                        },
                        new
                        {
                            PermissionCode = "draft-pools:create",
                            RoleName = "Host"
                        },
                        new
                        {
                            PermissionCode = "draft-pools:update",
                            RoleName = "Host"
                        },
                        new
                        {
                            PermissionCode = "candidate-lists:create",
                            RoleName = "Host"
                        },
                        new
                        {
                            PermissionCode = "candidate-lists:update",
                            RoleName = "Host"
                        },
                        new
                        {
                            PermissionCode = "candidate-lists:read",
                            RoleName = "Host"
                        },
                        new
                        {
                            PermissionCode = "picks:commissioner-override",
                            RoleName = "Host"
                        },
                        new
                        {
                            PermissionCode = "drafters:read",
                            RoleName = "Host"
                        },
                        new
                        {
                            PermissionCode = "drafters:list",
                            RoleName = "Host"
                        },
                        new
                        {
                            PermissionCode = "hosts:read",
                            RoleName = "Host"
                        },
                        new
                        {
                            PermissionCode = "hosts:list",
                            RoleName = "Host"
                        },
                        new
                        {
                            PermissionCode = "people:read",
                            RoleName = "Host"
                        },
                        new
                        {
                            PermissionCode = "people:list",
                            RoleName = "Host"
                        },
                        new
                        {
                            PermissionCode = "people:search",
                            RoleName = "Host"
                        },
                        new
                        {
                            PermissionCode = "movies:search",
                            RoleName = "Host"
                        },
                        new
                        {
                            PermissionCode = "actors:search",
                            RoleName = "Host"
                        },
                        new
                        {
                            PermissionCode = "crew:search",
                            RoleName = "Host"
                        },
                        new
                        {
                            PermissionCode = "genres:search",
                            RoleName = "Host"
                        },
                        new
                        {
                            PermissionCode = "studios:search",
                            RoleName = "Host"
                        },
                        new
                        {
                            PermissionCode = "categories:search",
                            RoleName = "Host"
                        },
                        new
                        {
                            PermissionCode = "series:read",
                            RoleName = "Host"
                        },
                        new
                        {
                            PermissionCode = "series:list",
                            RoleName = "Host"
                        },
                        new
                        {
                            PermissionCode = "campaigns:read",
                            RoleName = "Host"
                        },
                        new
                        {
                            PermissionCode = "campaigns:list",
                            RoleName = "Host"
                        },
                        new
                        {
                            PermissionCode = "sub-drafts:read",
                            RoleName = "Host"
                        },
                        new
                        {
                            PermissionCode = "sub-drafts:create",
                            RoleName = "Host"
                        },
                        new
                        {
                            PermissionCode = "sub-drafts:update",
                            RoleName = "Host"
                        },
                        new
                        {
                            PermissionCode = "predictions:submit",
                            RoleName = "Host"
                        },
                        new
                        {
                            PermissionCode = "predictions:read",
                            RoleName = "Host"
                        },
                        new
                        {
                            PermissionCode = "users:read",
                            RoleName = "Drafter"
                        },
                        new
                        {
                            PermissionCode = "users:update",
                            RoleName = "Drafter"
                        },
                        new
                        {
                            PermissionCode = "drafts:read",
                            RoleName = "Drafter"
                        },
                        new
                        {
                            PermissionCode = "drafts:list",
                            RoleName = "Drafter"
                        },
                        new
                        {
                            PermissionCode = "drafts:search",
                            RoleName = "Drafter"
                        },
                        new
                        {
                            PermissionCode = "draft-parts:read",
                            RoleName = "Drafter"
                        },
                        new
                        {
                            PermissionCode = "draft-parts:list",
                            RoleName = "Drafter"
                        },
                        new
                        {
                            PermissionCode = "draft-boards:read",
                            RoleName = "Drafter"
                        },
                        new
                        {
                            PermissionCode = "draft-pools:read",
                            RoleName = "Drafter"
                        },
                        new
                        {
                            PermissionCode = "draft-boards:create",
                            RoleName = "Drafter"
                        },
                        new
                        {
                            PermissionCode = "draft-boards:delete",
                            RoleName = "Drafter"
                        },
                        new
                        {
                            PermissionCode = "draft-boards:update",
                            RoleName = "Drafter"
                        },
                        new
                        {
                            PermissionCode = "candidate-lists:create",
                            RoleName = "Drafter"
                        },
                        new
                        {
                            PermissionCode = "candidate-lists:update",
                            RoleName = "Drafter"
                        },
                        new
                        {
                            PermissionCode = "candidate-lists:read",
                            RoleName = "Drafter"
                        },
                        new
                        {
                            PermissionCode = "picks:add",
                            RoleName = "Drafter"
                        },
                        new
                        {
                            PermissionCode = "picks:veto",
                            RoleName = "Drafter"
                        },
                        new
                        {
                            PermissionCode = "picks:veto-override",
                            RoleName = "Drafter"
                        },
                        new
                        {
                            PermissionCode = "drafters:read",
                            RoleName = "Drafter"
                        },
                        new
                        {
                            PermissionCode = "drafters:list",
                            RoleName = "Drafter"
                        },
                        new
                        {
                            PermissionCode = "hosts:read",
                            RoleName = "Drafter"
                        },
                        new
                        {
                            PermissionCode = "people:read",
                            RoleName = "Drafter"
                        },
                        new
                        {
                            PermissionCode = "people:search",
                            RoleName = "Drafter"
                        },
                        new
                        {
                            PermissionCode = "movies:search",
                            RoleName = "Drafter"
                        },
                        new
                        {
                            PermissionCode = "actors:search",
                            RoleName = "Drafter"
                        },
                        new
                        {
                            PermissionCode = "crew:search",
                            RoleName = "Drafter"
                        },
                        new
                        {
                            PermissionCode = "genres:search",
                            RoleName = "Drafter"
                        },
                        new
                        {
                            PermissionCode = "studios:search",
                            RoleName = "Drafter"
                        },
                        new
                        {
                            PermissionCode = "categories:search",
                            RoleName = "Drafter"
                        },
                        new
                        {
                            PermissionCode = "series:read",
                            RoleName = "Drafter"
                        },
                        new
                        {
                            PermissionCode = "series:list",
                            RoleName = "Drafter"
                        },
                        new
                        {
                            PermissionCode = "sub-drafts:read",
                            RoleName = "Drafter"
                        },
                        new
                        {
                            PermissionCode = "sub-drafts:create",
                            RoleName = "Drafter"
                        },
                        new
                        {
                            PermissionCode = "predictions:read",
                            RoleName = "Drafter"
                        },
                        new
                        {
                            PermissionCode = "users:read",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "users:update",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "drafts:read",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "drafts:list",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "drafts:create",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "drafts:update",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "drafts:delete",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "drafts:search",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "drafts:read-patreon",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "draft-parts:read",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "draft-parts:list",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "draft-parts:create",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "draft-parts:update",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "draft-parts:set-status",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "draft-boards:read",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "draft-boards:list",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "draft-boards:create",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "draft-boards:update",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "draft-boards:delete",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "draft-pools:create",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "draft-pools:update",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "draft-pools:read",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "picks:add",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "picks:create",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "picks:update",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "picks:undo",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "picks:veto",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "picks:veto-override",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "picks:commissioner-override",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "people:create",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "people:read",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "people:list",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "people:update",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "people:search",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "drafters:add",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "drafters:create",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "drafters:remove",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "drafters:update",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "drafters:read",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "drafters:list",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "hosts:add",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "hosts:create",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "hosts:remove",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "hosts:update",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "hosts:read",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "hosts:list",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "drafter-teams:read",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "drafter-teams:list",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "drafter-teams:create",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "drafter-teams:update",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "drafter-teams:members",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "game-boards:create",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "game-boards:update",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "movies:create",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "movies:read",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "movies:search",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "actors:search",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "crew:search",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "genres:search",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "studios:search",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "series:read",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "series:list",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "series:create",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "series:update",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "series:delete",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "categories:create",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "categories:update",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "categories:read",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "categories:search",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "categories:delete",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "campaigns:create",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "campaigns:update",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "campaigns:read",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "campaigns:list",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "campaigns:delete",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "campaigns:restore",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "candidate-lists:read",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "candidate-lists:list",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "candidate-lists:create",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "candidate-lists:update",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "candidate-lists:delete",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "sub-drafts:read",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "sub-drafts:create",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "sub-drafts:update",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "predictions:manage",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "predictions:submit",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "predictions:read",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "users:read",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "users:update",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "roles:read",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "roles:update",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "permissions:read",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "permissions:update",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "drafts:read",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "drafts:list",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "drafts:create",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "drafts:update",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "drafts:delete",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "drafts:search",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "drafts:read-patreon",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "draft-parts:read",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "draft-parts:list",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "draft-parts:create",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "draft-parts:update",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "draft-parts:set-status",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "draft-boards:read",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "draft-boards:list",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "draft-boards:create",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "draft-boards:update",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "draft-boards:delete",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "draft-pools:create",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "draft-pools:update",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "draft-pools:read",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "picks:add",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "picks:create",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "picks:update",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "picks:undo",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "picks:veto",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "picks:veto-override",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "picks:commissioner-override",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "people:create",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "people:read",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "people:list",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "people:update",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "people:search",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "drafters:add",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "drafters:create",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "drafters:remove",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "drafters:update",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "drafters:read",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "drafters:list",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "hosts:add",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "hosts:create",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "hosts:remove",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "hosts:update",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "hosts:read",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "hosts:list",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "drafter-teams:read",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "drafter-teams:list",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "drafter-teams:create",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "drafter-teams:update",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "drafter-teams:members",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "game-boards:create",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "game-boards:update",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "movies:create",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "movies:read",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "movies:search",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "actors:search",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "crew:search",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "genres:search",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "studios:search",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "series:read",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "series:list",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "series:create",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "series:update",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "series:delete",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "categories:create",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "categories:update",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "categories:read",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "categories:search",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "categories:delete",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "campaigns:create",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "campaigns:update",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "campaigns:read",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "campaigns:list",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "campaigns:delete",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "campaigns:restore",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "candidate-lists:read",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "candidate-lists:list",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "candidate-lists:create",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "candidate-lists:update",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "candidate-lists:delete",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "sub-drafts:read",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "sub-drafts:create",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "sub-drafts:update",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "predictions:manage",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "predictions:submit",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "predictions:read",
                            RoleName = "SuperAdministrator"
                        },
                        new
                        {
                            PermissionCode = "patreon:search",
                            RoleName = "Patreon"
                        });
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<string>("RolesName")
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("RolesName", "UserId")
                        .HasName("pk_user_roles");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_roles_user_id");

                    b.ToTable("user_roles", "users");
                });

            modelBuilder.Entity("ScreenDrafts.Common.Infrastructure.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_inbox_messages");

                    b.ToTable("inbox_messages", "users");
                });

            modelBuilder.Entity("ScreenDrafts.Common.Infrastructure.Inbox.InboxMessageConsumer", b =>
                {
                    b.Property<Guid>("InboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("inbox_message_id");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("InboxMessageId", "Name")
                        .HasName("pk_inbox_message_consumers");

                    b.ToTable("inbox_message_consumers", "users");
                });

            modelBuilder.Entity("ScreenDrafts.Common.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.ToTable("outbox_messages", "users");
                });

            modelBuilder.Entity("ScreenDrafts.Common.Infrastructure.Outbox.OutboxMessageConsumer", b =>
                {
                    b.Property<Guid>("OutboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_message_id");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("OutboxMessageId", "Name")
                        .HasName("pk_outbox_message_consumers");

                    b.ToTable("outbox_message_consumers", "users");
                });

            modelBuilder.Entity("ScreenDrafts.Modules.Users.Domain.Users.Permission", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.HasKey("Code")
                        .HasName("pk_permissions");

                    b.ToTable("permissions", "users");

                    b.HasData(
                        new
                        {
                            Code = "users:read"
                        },
                        new
                        {
                            Code = "users:update"
                        },
                        new
                        {
                            Code = "roles:read"
                        },
                        new
                        {
                            Code = "roles:update"
                        },
                        new
                        {
                            Code = "permissions:read"
                        },
                        new
                        {
                            Code = "permissions:update"
                        },
                        new
                        {
                            Code = "drafts:read"
                        },
                        new
                        {
                            Code = "drafts:list"
                        },
                        new
                        {
                            Code = "drafts:create"
                        },
                        new
                        {
                            Code = "drafts:update"
                        },
                        new
                        {
                            Code = "drafts:delete"
                        },
                        new
                        {
                            Code = "drafts:search"
                        },
                        new
                        {
                            Code = "drafts:read-patreon"
                        },
                        new
                        {
                            Code = "patreon:search"
                        },
                        new
                        {
                            Code = "draft-parts:read"
                        },
                        new
                        {
                            Code = "draft-parts:list"
                        },
                        new
                        {
                            Code = "draft-parts:create"
                        },
                        new
                        {
                            Code = "draft-parts:update"
                        },
                        new
                        {
                            Code = "draft-parts:set-status"
                        },
                        new
                        {
                            Code = "draft-boards:read"
                        },
                        new
                        {
                            Code = "draft-boards:list"
                        },
                        new
                        {
                            Code = "draft-boards:create"
                        },
                        new
                        {
                            Code = "draft-boards:update"
                        },
                        new
                        {
                            Code = "draft-boards:delete"
                        },
                        new
                        {
                            Code = "draft-pools:create"
                        },
                        new
                        {
                            Code = "draft-pools:update"
                        },
                        new
                        {
                            Code = "draft-pools:read"
                        },
                        new
                        {
                            Code = "picks:add"
                        },
                        new
                        {
                            Code = "picks:create"
                        },
                        new
                        {
                            Code = "picks:update"
                        },
                        new
                        {
                            Code = "picks:undo"
                        },
                        new
                        {
                            Code = "picks:veto"
                        },
                        new
                        {
                            Code = "picks:veto-override"
                        },
                        new
                        {
                            Code = "picks:commissioner-override"
                        },
                        new
                        {
                            Code = "people:create"
                        },
                        new
                        {
                            Code = "people:read"
                        },
                        new
                        {
                            Code = "people:list"
                        },
                        new
                        {
                            Code = "people:update"
                        },
                        new
                        {
                            Code = "people:search"
                        },
                        new
                        {
                            Code = "drafters:add"
                        },
                        new
                        {
                            Code = "drafters:create"
                        },
                        new
                        {
                            Code = "drafters:remove"
                        },
                        new
                        {
                            Code = "drafters:update"
                        },
                        new
                        {
                            Code = "drafters:read"
                        },
                        new
                        {
                            Code = "drafters:list"
                        },
                        new
                        {
                            Code = "hosts:add"
                        },
                        new
                        {
                            Code = "hosts:create"
                        },
                        new
                        {
                            Code = "hosts:remove"
                        },
                        new
                        {
                            Code = "hosts:update"
                        },
                        new
                        {
                            Code = "hosts:read"
                        },
                        new
                        {
                            Code = "hosts:list"
                        },
                        new
                        {
                            Code = "drafter-teams:read"
                        },
                        new
                        {
                            Code = "drafter-teams:list"
                        },
                        new
                        {
                            Code = "drafter-teams:create"
                        },
                        new
                        {
                            Code = "drafter-teams:update"
                        },
                        new
                        {
                            Code = "drafter-teams:members"
                        },
                        new
                        {
                            Code = "game-boards:create"
                        },
                        new
                        {
                            Code = "game-boards:update"
                        },
                        new
                        {
                            Code = "movies:create"
                        },
                        new
                        {
                            Code = "movies:read"
                        },
                        new
                        {
                            Code = "movies:search"
                        },
                        new
                        {
                            Code = "actors:search"
                        },
                        new
                        {
                            Code = "crew:search"
                        },
                        new
                        {
                            Code = "genres:search"
                        },
                        new
                        {
                            Code = "studios:search"
                        },
                        new
                        {
                            Code = "series:read"
                        },
                        new
                        {
                            Code = "series:list"
                        },
                        new
                        {
                            Code = "series:create"
                        },
                        new
                        {
                            Code = "series:update"
                        },
                        new
                        {
                            Code = "series:delete"
                        },
                        new
                        {
                            Code = "categories:create"
                        },
                        new
                        {
                            Code = "categories:update"
                        },
                        new
                        {
                            Code = "categories:read"
                        },
                        new
                        {
                            Code = "categories:search"
                        },
                        new
                        {
                            Code = "categories:delete"
                        },
                        new
                        {
                            Code = "campaigns:create"
                        },
                        new
                        {
                            Code = "campaigns:update"
                        },
                        new
                        {
                            Code = "campaigns:read"
                        },
                        new
                        {
                            Code = "campaigns:list"
                        },
                        new
                        {
                            Code = "campaigns:delete"
                        },
                        new
                        {
                            Code = "campaigns:restore"
                        },
                        new
                        {
                            Code = "candidate-lists:read"
                        },
                        new
                        {
                            Code = "candidate-lists:list"
                        },
                        new
                        {
                            Code = "candidate-lists:create"
                        },
                        new
                        {
                            Code = "candidate-lists:update"
                        },
                        new
                        {
                            Code = "candidate-lists:delete"
                        },
                        new
                        {
                            Code = "sub-drafts:read"
                        },
                        new
                        {
                            Code = "sub-drafts:create"
                        },
                        new
                        {
                            Code = "sub-drafts:update"
                        },
                        new
                        {
                            Code = "predictions:manage"
                        },
                        new
                        {
                            Code = "predictions:submit"
                        },
                        new
                        {
                            Code = "predictions:read"
                        });
                });

            modelBuilder.Entity("ScreenDrafts.Modules.Users.Domain.Users.Role", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Name")
                        .HasName("pk_roles");

                    b.ToTable("roles", "users");

                    b.HasData(
                        new
                        {
                            Name = "SuperAdministrator"
                        },
                        new
                        {
                            Name = "Administrator"
                        },
                        new
                        {
                            Name = "Guest"
                        },
                        new
                        {
                            Name = "Host"
                        },
                        new
                        {
                            Name = "Drafter"
                        },
                        new
                        {
                            Name = "Patreon"
                        });
                });

            modelBuilder.Entity("ScreenDrafts.Modules.Users.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BlueskyHandle")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bluesky_handle");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("IdentityId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("identity_id");

                    b.Property<string>("InstagramHandle")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("instagram_handle");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("LetterboxdHandle")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("letterboxd_handle");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text")
                        .HasColumnName("middle_name");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("PersonPublicId")
                        .HasColumnType("text")
                        .HasColumnName("person_public_id");

                    b.Property<string>("ProfilePicturePath")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("profile_picture_path");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("public_id");

                    b.Property<string>("TwitterHandle")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("twitter_handle");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("IdentityId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_identity_id");

                    b.HasIndex("PersonId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_person_id")
                        .HasFilter("\"person_id\" IS NOT NULL");

                    b.HasIndex("PersonPublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_person_public_id")
                        .HasFilter("\"person_public_id\" IS NOT NULL");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_public_id");

                    b.ToTable("users", "users");
                });

            modelBuilder.Entity("PermissionRole", b =>
                {
                    b.HasOne("ScreenDrafts.Modules.Users.Domain.Users.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_permissions_permission_code");

                    b.HasOne("ScreenDrafts.Modules.Users.Domain.Users.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_roles_role_name");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("ScreenDrafts.Modules.Users.Domain.Users.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_roles_name");

                    b.HasOne("ScreenDrafts.Modules.Users.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
