CREATE SCHEMA IF NOT EXISTS drafts;

GRANT USAGE ON SCHEMA drafts TO drafts_user;
GRANT CREATE ON SCHEMA drafts TO drafts_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA drafts
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO drafts_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA drafts
    GRANT USAGE, SELECT ON SEQUENCES TO drafts_user;