# New-Migration.ps1
# Run from: C:\Repos\ScreenDrafts\src\screendrafts.api
#
# Usage:
#   .\tools\New-Migration.ps1 -Name Add_Person_Profile_Picture -Module Drafts
#
# Supported modules: Administration, Audit, Communications, Drafts, Integrations, Movies, RealTimeUpdates, Reporting, Users

param(
    [Parameter(Mandatory)][string]$Name,
    [Parameter(Mandatory)][ValidateSet(
        "Administration",
        "Audit",
        "Communications",
        "Drafts",
        "Integrations",
        "Movies",
        "RealTimeUpdates",
        "Reporting",
        "Users"
    )][string]$Module
)

$startupProject  = ".\src\api\ScreenDrafts.Web\"
$migratorProject = ".\tools\ScreenDrafts.Tools.DbMigrator\"
$scriptsRoot     = ".\tools\ScreenDrafts.Tools.DbMigrator\Scripts"

$moduleConfig = @{
    Administration  = @{ Context = "AdministrationDbContext";  Project = ".\src\modules\administration\ScreenDrafts.Modules.Administration.Infrastructure\" }
    Audit           = @{ Context = "AuditDbContext";           Project = ".\src\modules\audit\ScreenDrafts.Modules.Audit.Infrastructure\" }
    Communications  = @{ Context = "CommunicationsDbContext";  Project = ".\src\modules\communications\ScreenDrafts.Modules.Communications.Infrastructure\" }
    Drafts          = @{ Context = "DraftsDbContext";          Project = ".\src\modules\drafts\ScreenDrafts.Modules.Drafts.Infrastructure\" }
    Integrations    = @{ Context = "IntegrationsDbContext";    Project = ".\src\modules\integrations\ScreenDrafts.Modules.Integrations.Infrastructure\" }
    Movies          = @{ Context = "MoviesDbContext";          Project = ".\src\modules\movies\ScreenDrafts.Modules.Movies.Infrastructure\" }
    RealTimeUpdates = @{ Context = "RealTimeUpdatesDbContext"; Project = ".\src\modules\real-time-updates\ScreenDrafts.Modules.RealTimeUpdates.Infrastructure\" }
    Reporting       = @{ Context = "ReportingDbContext";       Project = ".\src\modules\reporting\ScreenDrafts.Modules.Reporting.Infrastructure\" }
    Users           = @{ Context = "UsersDbContext";           Project = ".\src\modules\users\ScreenDrafts.Modules.Users.Infrastructure\" }
}

# ── helpers ───────────────────────────────────────────────────────────────────

function Get-NextScriptNumber {
    param([string]$ModuleScriptsPath)

    if (-not (Test-Path $ModuleScriptsPath)) {
        return "0001"
    }

    $highest = Get-ChildItem -Path $ModuleScriptsPath -Filter "*.sql" -File |
        ForEach-Object {
            if ($_.Name -match '^(\d+)_') { [int]$Matches[1] } else { 0 }
        } |
        Measure-Object -Maximum |
        Select-Object -ExpandProperty Maximum

    return "{0:D4}" -f ([int]($highest ?? 0) + 1)
}

function ConvertTo-SnakeCase {
    param([string]$PascalName)
    # Insert underscore before each uppercase letter that follows a lowercase
    # letter or digit, then lowercase the whole string.
    # "AddPersonProfilePicture" -> "add_person_profile_picture"
    return [regex]::Replace($PascalName, '(?<=[a-z0-9])([A-Z])', '_$1').ToLower()
}

# ── 1. Generate EF migration ──────────────────────────────────────────────────

$config  = $moduleConfig[$Module]
$context = $config.Context
$project = $config.Project
$output  = "Database\Migrations"

Write-Host ""
Write-Host "[$Module] Generating migration '$Name'..." -ForegroundColor Cyan

dotnet ef migrations add $Name `
    -c $context `
    -p $project `
    -s $startupProject `
    -o $output

if ($LASTEXITCODE -ne 0) {
    Write-Host "Migration generation failed." -ForegroundColor Red
    exit 1
}

# ── 2. Add // <auto-generated /> header ───────────────────────────────────────

$migrationsPath = Join-Path $project $output
Get-ChildItem -Path $migrationsPath -Filter "*$Name*" -File | ForEach-Object {
    $content = Get-Content $_.FullName -Raw
    if (-not $content.StartsWith("// <auto-generated />")) {
        Set-Content $_.FullName -Value "// <auto-generated />`r`n$content"
        Write-Host "  Headered: $($_.Name)" -ForegroundColor DarkGray
    }
}

# ── 3. Resolve output SQL script path ─────────────────────────────────────────

$moduleScriptsPath = Join-Path $scriptsRoot $Module
$nextNumber        = Get-NextScriptNumber -ModuleScriptsPath $moduleScriptsPath
$snakeName         = ConvertTo-SnakeCase -PascalName $Name
$scriptFileName    = "${nextNumber}_ef_${snakeName}.sql"
$scriptOutputPath  = Join-Path $moduleScriptsPath $scriptFileName

if (-not (Test-Path $moduleScriptsPath)) {
    New-Item -ItemType Directory -Path $moduleScriptsPath | Out-Null
}

# ── 4. Generate idempotent SQL script ─────────────────────────────────────────

Write-Host ""
Write-Host "[$Module] Generating SQL script '$scriptFileName'..." -ForegroundColor Cyan

dotnet ef migrations script -i `
    -c $context `
    -p $project `
    -s $startupProject `
    -o $scriptOutputPath

if ($LASTEXITCODE -ne 0) {
    Write-Host "Script generation failed." -ForegroundColor Red
    exit 1
}

Write-Host "  Written:  $scriptOutputPath" -ForegroundColor DarkGray

# ── 5. Run DbMigrator ─────────────────────────────────────────────────────────

Write-Host ""
Write-Host "Running DbMigrator..." -ForegroundColor Cyan

dotnet run --project $migratorProject

if ($LASTEXITCODE -ne 0) {
    Write-Host "DbMigrator failed." -ForegroundColor Red
    exit 1
}

Write-Host ""
Write-Host "Done. '$scriptFileName' applied to database." -ForegroundColor Green