name: Build UI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/screendrafts.ui/**'
  pull_request:
    branches:
      - main
    paths:
      - 'src/screendrafts.ui/**'

env:
  NODE_VERSION: "22"

jobs:
  build-ui:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src/screendrafts.ui

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: src/screendrafts.ui/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          NEXT_PUBLIC_API_URL: http://localhost:5000